class WebRuRU {
  static Map<String, String> keys() {
    return {
      // common
      'common.cancel': 'Отмена',
      'common.ok': 'ОК',
      'common.confirm': 'Подтвердить',
      'common.error': 'Ошибка',
      'common.success': 'Успех',
      'common.failed': 'Ошибка',
      'common.retry': 'Повторить',
      'common.delete': 'Удалить',
      'common.reset': 'Сбросить',
      'common.clear': 'Очистить',
      'preset': 'Предустановка',
      'custom': 'Пользовательский',
      'common.refresh': 'Обновить',
      'common.loading': 'Загрузка...',
      'common.unknown': 'Неизвестно',
      'common.images': '@count изобр.',
      'common.pages': '@count стр.',
      'common.open': 'Открыть',
      'common.close': 'Закрыть',
      'localizedReason': 'Подтвердите доступ, чтобы продолжить',
      'passwordErrorHint': 'Неверный пароль, попробуйте ещё раз',
      'dawnOfaNewDay': 'Наступил рассвет нового дня!',
      'encounterMonster': 'Вы встретили монстра!',
      'encounterMonsterHint': 'Нажмите, чтобы сразиться в HentaiVerse.',

      'share': 'Поделиться',
      'save': 'Сохранить',
      'reload': 'Перезагрузить',
      'cancel': 'Отмена',
      'resampleImage': 'Сжатое',
      'originalImage': 'Оригинал',
      'downloadOriginalImage': 'Скачать оригинальное изображение',
      'downloadOriginalImageByDefault':
          'Выбирать оригинальное изображение по умолчанию',
      'downloadAllGallerysOfSamePriority':
          'Скачивать все галереи одного приоритета',
      'downloadAllGallerysOfSamePriorityHint':
          'По умолчанию одновременно скачивается только одна галерея каждого приоритета.',
      'useJH2UpdateGallery':
          'Использовать сервер JH для ускорения обновления галерей',
      'restoreDownloadTasks': 'Восстановить задачи загрузки',
      'restoreDownloadTasksHint': 'Восстановить задачи загрузки по метаданным',
      'restoreTasksAutomatically': 'Восстанавливать задачи автоматически',
      'restoreTasksAutomaticallyHint':
          'Восстанавливать задачи из метаданных загрузок при запуске сервера',
      'home.pasteAndSearch': 'Вставить и найти или открыть',
      'home.clipboardEmpty': 'Буфер обмена пуст',
      'home.clipboardReadFailed':
          'Не удалось прочитать буфер обмена. Разрешите доступ и повторите попытку.',
      'galleryUrlDetected': 'В буфере обмена найдена ссылка на галерею',
      'galleryUrlDetectedHint': 'Открыть найденную ссылку',
      'restoredGalleryCount': 'Восстановлено галерей',
      'restoredArchiveCount': 'Восстановлено архивов',
      'reDownload': 'Скачать снова',
      'deleteTask': 'Удалить только задачу',
      'deleteTaskAndImages': 'Удалить задачу и изображения',
      'hasCopiedToClipboard': 'Скопировано в буфер обмена',
      'autoModeStyle': 'Стиль авторежима',
      'scroll': 'Прокрутка',
      'turnPage': 'Перелистывание',
      'turnPageMode': 'Режим перелистывания',
      'turnPageModeHint': 'К следующему экрану или изображению',
      'image': 'Изображение',
      'screen': 'Экран',
      'adaptive': 'Адаптивный',
      'displayFirstPageAlone': 'Отдельно показывать первую страницу',
      'showThumbnails': 'Показывать миниатюры',
      'showScrollBar': 'Показывать полосу прокрутки',
      'showStatusInfo': 'Показывать статус снизу',
      'keepScreenAwakeWhenReading': 'Не выключать экран при чтении',
      'gestureRegionWidthRatio': 'Доля ширины области жеста меню',
      'imageRegionWidthRatio': 'Доля ширины области изображения',
      'spaceBetweenImages': 'Отступы между изображениями',
      'defaultTab': 'Вкладка по умолчанию',
      'enablePasswordAuth': 'Включить пароль',
      'enableAuthOnResume': 'Запрашивать пароль при возврате',
      'enableAuthOnResumeHints': 'Блокировать снова через 3 секунды в фоне',
      'setPasswordHint': 'Введите пароль',
      'confirmPasswordHint': 'Введите пароль ещё раз',
      'passwordNotMatchHint': 'Пароли не совпадают, попробуйте снова',

      // setup
      'setup.title': 'Настройка сервера JHenTai',
      'setup.description':
          'Введите API-токен из логов сервера для подключения.',
      'setup.tokenLabel': 'API-токен',
      'setup.connect': 'Подключить',
      'setup.emptyToken': 'Пожалуйста, введите токен',
      'setup.invalidToken': 'Недействительный токен. Проверьте логи сервера.',
      'setup.tokenHint':
          'Токен — 64 шестнадцатеричных символа в одной строке. Копируйте строку целиком.',
      'setup.tokenPasteHint': 'Вставьте полный 64-символьный токен из логов',
      'setup.tokenCharCount': '@current / @total символов',
      'setup.tokenWrongLength':
          'Токен должен быть ровно из 64 шестнадцатеричных символов (полная строка из docker logs).',
      'setup.tokenHelpTitle': 'Как найти токен в логах',
      'setup.tokenHelpP1': 'На хосте с Docker откройте терминал и выполните:',
      'setup.tokenHelpP2':
          'Найдите строку, начинающуюся с [JHenTai] API token for web UI. Скопируйте 64 шестнадцатеричных символа после двоеточия (весь токен в одной строке). Если имя контейнера не jhentai, замените его в командах ниже.',
      'setup.tokenHelpAlt':
          'Если такой строки нет, прочитайте токен из базы (имя контейнера по умолчанию jhentai, каталог данных /data):',

      // home
      'home.title': 'JHenTai',
      'home.search': 'Поиск галерей...',
      'home.advancedSearch': 'Расширенный поиск',
      'home.searchFilterSheetTitle': 'Категории и фильтры',
      'home.leftPaneWidthPx': '@w px',
      'home.twoPaneDividerTooltip':
          'Левая панель @w px · двойной щелчок по разделителю — ширина по умолчанию',
      'home.downloads': 'Загрузки',
      'home.localGalleries': 'Локальные галереи',
      'home.settings': 'Настройки',
      'home.subtitle': 'Клиент E-Hentai',
      'home.home': 'Главная',
      'home.popular': 'Популярное',
      'home.favorites': 'Избранное',
      'home.watched': 'Отслеживаемое',
      'home.noGalleries': 'Галереи не найдены',
      'home.previous': 'Назад',
      'home.next': 'Вперёд',
      'home.jumpDate': 'Перейти к дате',
      'home.page': 'Стр. @page',
      'home.loadFailed': 'Ошибка загрузки: @error',
      'home.favSortTitle': 'Сортировка избранного',
      'home.favSortFavorited': 'По дате добавления',
      'home.favSortPublished': 'По дате публикации',
      'home.favAllFolders': 'Все',
      'home.favSlotShort': 'Папка @n',
      'home.categoryFilter': 'Фильтр категорий',
      'home.minimumRating': 'Мин. рейтинг',
      'home.ratingAny': 'Любой',
      'home.searchIn': 'Искать в',
      'home.galleryName': 'Название галереи',
      'home.tags': 'Теги',
      'home.description': 'Описание',
      'home.showExpunged': 'Показать удалённые',
      'home.onlyShowGalleriesWithTorrents':
          'Показывать только галереи с торрентами',
      'home.pageRange': 'Диапазон страниц',
      'home.pageAtLeast': 'Минимум',
      'home.pageAtMost': 'Максимум',
      'home.language': 'Язык',
      'home.languageNone': 'Нет',
      'home.disableFilterForLanguage': 'Отключить фильтр языка',
      'home.disableFilterForUploader': 'Отключить фильтр загрузившего',
      'home.disableFilterForTags': 'Отключить фильтр тегов',
      'home.applySearch': 'Применить и искать',
      'home.history': 'История',
      'home.ranklist': 'Рейтинг',

      // category names
      'category.doujinshi': 'Додзинси',
      'category.manga': 'Манга',
      'category.artistCg': 'CG художника',
      'category.gameCg': 'CG игры',
      'category.western': 'Западное',
      'category.nonH': 'Non-H',
      'category.imageSet': 'Набор изображений',
      'category.cosplay': 'Косплей',
      'category.asianPorn': 'Азиатское',
      'category.misc': 'Разное',

      // gallery detail
      'detail.copyUrl': 'Копировать URL галереи',
      'detail.copied': 'Скопировано',
      'detail.removeFromFav': 'Удалить из избранного',
      'detail.addToFav': 'Добавить в избранное',
      'detail.addToFavTitle': 'Добавить в избранное',
      'detail.favRemoved': 'Удалено',
      'detail.favRemovedMsg': 'Удалено из избранного',
      'detail.favAdded': 'Добавлено',
      'detail.favAddedMsg': 'Добавлено в @name',
      'detail.favError': 'Ошибка операции с избранным: @error',
      'detail.favSlot': 'Избранное @n',
      'detail.favNoteHint': 'Заметка (необязательно)',
      'detail.favQuickAddTooltip': 'В папку по умолчанию (долгое нажатие)',
      'detail.rateTitle': 'Оценить галерею',
      'detail.rateSubmit': 'Отправить',
      'detail.rated': 'Оценено',
      'detail.ratedMsg': 'Ваша оценка: @rating',
      'detail.rateFailed': 'Ошибка оценки: @error',
      'detail.rateLoginRequired': 'Для оценки нужен вход',
      'detail.ratingCount': 'Оценок: @count',
      'detail.favoriteCount': 'В избранном: @count',
      'detail.readOnline': 'Читать онлайн',
      'detail.readOnlineResume': 'Читать онлайн (продолжить со стр. @page)',
      'detail.downloadGallery': 'Скачать галерею',
      'detail.archiveResample': 'Архив (сжатый)',
      'detail.archiveOriginal': 'Архив (оригинал)',
      'detail.downloadArchive': 'Скачать архив',
      'detail.downloadStarted': 'Загрузка началась',
      'detail.galleryQueued': 'Загрузка галереи добавлена в очередь',
      'detail.archiveQueued': 'Загрузка архива добавлена в очередь',
      'detail.downloadFailed': 'Ошибка загрузки: @error',
      'detail.archiveFailed': 'Ошибка загрузки архива: @error',
      'detail.loadArchiveInfoFailed':
          'Не удалось загрузить сведения об архиве: @error',
      'detail.noArchive': 'Архив недоступен',
      'detail.tags': 'Теги',
      'detail.comments': 'Комментарии (@count)',
      'detail.anonymous': 'Аноним',
      'detail.loadFailed': 'Ошибка загрузки деталей: @error',

      // reader
      'reader.loading': 'Загрузка галереи...',
      'reader.loadingGalleryMeta': 'Загрузка списка страниц...',
      'reader.resolvingFirstPages': 'Разбор страниц изображений...',
      'reader.resolvingImagePage': 'Разбор страницы...',
      'reader.loadingImage': 'Загрузка изображения...',
      'reader.loadFailed': 'Ошибка загрузки: @error',
      'reader.imageFailed': 'Ошибка загрузки изображения',
      'reader.noImages': 'Нет изображений',
      'reader.directionLabel': 'Направление чтения: @dir',
      'reader.ltr': 'Слева→Направо',
      'reader.rtl': 'Справа→Налево',
      'reader.vertical': 'Вертикально',
      'reader.wheelAction': 'Колёсико над изображением',
      'reader.wheelActionPage': 'Листать страницу',
      'reader.wheelActionZoom': 'Масштабировать',
      'reader.wheelActionVerticalHint':
          'В вертикальном режиме и «по ширине» всегда прокручивается список. Опция действует для LTR, RTL и двухстраничного режима.',
      'reader.wheelInvertPageTurn': 'Инвертировать листание колёсиком',
      'reader.wheelInvertPageTurnSubtitle':
          'Меняет, какое направление прокрутки колёсика/тачпада перелистывает вперёд или назад.',
      'reader.wheelScrollSpeed': 'Скорость прокрутки колёсиком',
      'reader.wheelScrollSpeedSubtitle':
          'Управляет скоростью прокрутки мышью в вертикальном режиме и режиме по ширине.',
      'wheelScrollSpeed': 'Скорость прокрутки колёсиком',

      // downloads
      'downloads.title': 'Загрузки',
      'downloads.gallery': 'Галерея',
      'downloads.archive': 'Архив',
      'downloads.noGallery': 'Нет загрузок галерей',
      'downloads.noArchive': 'Нет загрузок архивов',
      'downloads.read': 'Читать',
      'downloads.pause': 'Пауза',
      'downloads.resume': 'Продолжить',
      'downloads.deleteTitle': 'Удалить загрузку',
      'downloads.deleteConfirm': 'Выберите, сохранять ли загруженные файлы.',
      'downloads.loadFailed': 'Ошибка загрузки задач: @error',
      'downloads.gStatus0': 'Нет',
      'downloads.gStatus1': 'Загрузка',
      'downloads.gStatus2': 'Пауза',
      'downloads.gStatus3': 'Завершено',
      'downloads.gStatus4': 'Ошибка',
      'downloads.aStatus0': 'Нет',
      'downloads.aStatus1': 'Разблокировка',
      'downloads.aStatus2': 'Анализ URL',
      'downloads.aStatus3': 'Загрузка',
      'downloads.aStatus4': 'Загружено',
      'downloads.aStatus5': 'Распаковка',
      'downloads.aStatus6': 'Завершено',
      'downloads.aStatus7': 'Пауза',
      'downloads.aStatus8': 'Ошибка',

      // local
      'local.title': 'Локальные галереи',
      'local.noGalleries': 'Локальные галереи не найдены',
      'local.helpText':
          'Смонтируйте каталоги в Docker-контейнер\nили поместите галереи в папку local_gallery',
      'local.scanNow': 'Сканировать',
      'local.empty': 'Пусто',
      'local.noImages': 'Нет изображений в этой галерее',
      'local.loadFailed': 'Ошибка загрузки изображений: @error',
      'local.loadListFailed': 'Ошибка загрузки локальных галерей: @error',
      'local.deleteTitle': 'Удалить локальную галерею',
      'local.deleteConfirm': 'Удалить локальные файлы для "@title"?',
      'local.deleteSuccess': 'Локальная галерея удалена',
      'local.deleteFailed': 'Не удалось удалить локальную галерею: @error',
      'local.parentDirectory': 'Родительская папка',
      'local.copyPath': 'Копировать путь',
      'local.copyAllPaths': 'Копировать все пути',
      'local.scanRoots': 'Корни сканирования',
      'local.scanRootsHint':
          'Это пути внутри контейнера, которые сканирует Docker-сервер. Измените тома Docker или JH_EXTRA_SCAN_PATHS, чтобы настроить их.',
      'local.noScanRoots': 'Корни сканирования не настроены',

      // settings
      'settings.title': 'Настройки',
      'settings.account': 'Аккаунт',
      'settings.loggedIn': 'Вы вошли как: @user',
      'settings.logout': 'Выйти',
      'settings.logoutSuccess': 'Вы вышли',
      'settings.logoutFailed': 'Ошибка выхода: @error',
      'settings.cookieLogin': 'Вход через cookies (рекомендуется)',
      'settings.cookieHint': 'Вход на форум EH заблокирован Cloudflare. '
          'Войдите через браузер и скопируйте cookies сюда.\n'
          'Шаги: Вход на e-hentai.org → F12 → Application → Cookies → скопируйте значения.',
      'settings.cookiePlaceholder':
          'ipb_member_id=xxx; ipb_pass_hash=xxx; igneous=xxx',
      'settings.setCookies': 'Установить Cookies',
      'settings.cookieSuccess': 'Cookies установлены',
      'settings.cookieFailed': 'Ошибка установки cookies: @error',
      'settings.cookieEmpty': 'Вставьте cookies',
      'settings.showCookies': 'Показать cookies',
      'settings.copyCookies': 'Копировать cookies',
      'settings.copyKeyCookies': 'Копировать cookies входа',
      'settings.refreshIgneous': 'Обновить igneous',
      'settings.refreshIgneousSuccess': 'igneous обновлен',
      'settings.refreshIgneousFailed': 'Не удалось обновить igneous',
      'settings.refreshIgneousFailedWithError':
          'Не удалось обновить igneous: @error',
      'settings.credentialLogin':
          'Вход по логину (может не работать из-за Cloudflare)',
      'settings.username': 'Имя пользователя',
      'settings.password': 'Пароль',
      'settings.login': 'Войти',
      'settings.loginSuccess': 'Вход выполнен',
      'settings.loginFailed': 'Ошибка входа',
      'settings.loginError': 'Ошибка входа: @error',
      'settings.emptyCredentials': 'Введите имя пользователя и пароль',
      'settings.site': 'Сайт',
      'redirect2Eh': 'Перенаправлять на EH, если доступно',
      'redirect2EhHint':
          'Сначала пробовать загрузить детали галереи через EH для лучшей производительности сети.',
      'settings.appearance': 'Внешний вид',
      'settings.themeMode': 'Тема',
      'settings.system': 'Системная',
      'settings.light': 'Светлая',
      'settings.dark': 'Тёмная',
      'settings.accentColor': 'Цвет акцента',
      'settings.serverInfo': 'Информация о сервере',
      'settings.dataDir': 'Каталог данных',
      'settings.downloadDir': 'Каталог загрузок',
      'settings.localGalleryDir': 'Каталог локальных галерей',
      'settings.extraScanPaths': 'Доп. пути сканирования',
      'settings.switchSiteFailed': 'Ошибка смены сайта: @error',
      'settings.language': 'Язык',
      'settings.sectionData': 'Данные и инструменты',
      'settings.sectionStyle': 'Оформление',
      'settings.sectionRead': 'Чтение',
      'settings.sectionTags': 'Теги и фильтры',
      'settings.sectionOther': 'Прочее',
      'settings.openDownloads': 'Загрузки',
      'settings.openHistory': 'История',
      'settings.openLocal': 'Локальные галереи',
      'settings.openQuickSearch': 'Быстрый поиск',
      'settings.networkNote': 'Сеть и прокси',
      'settings.networkWebBody':
          'Прокси и сеть настраиваются на сервере или в Docker. Эта страница показывает текущее состояние прокси для запросов EH/EX и изображений H@H.',
      'settings.about': 'О приложении',
      'settings.appVersion': 'Версия @version (@build)',
      'settings.hubMenu': 'Меню настроек',
      'settings.menuWebDocker': 'Веб-интерфейс и сервер',
      'settings.menuWebDockerSubtitle':
          'Загрузки, пути Docker, сеть и прокси, производительность и безопасность (только Web).',
      'settings.menuEH': 'E-Hentai',
      'settings.menuStyle': 'Стиль',
      'settings.menuRead': 'Чтение',
      'settings.menuPreference': 'Поведение',
      'settings.menuNetwork': 'Сеть',
      'settings.menuDownload': 'Загрузки',
      'settings.menuPerformance': 'Производительность',
      'settings.menuMouseWheel': 'Колёсико мыши',
      'settings.menuAdvanced': 'Дополнительно',
      'settings.menuSecurity': 'Безопасность',
      'settings.ehRequiresLogin':
          'Войдите в разделе «Аккаунт», чтобы менять сайт и состояние cookie.',
      'settings.ehMyTags': 'Мои теги',
      'settings.ehMyTagsHint':
          'Управление отслеживаемыми и скрытыми тегами онлайн',
      'settings.ehSiteSetting': 'Настройки сайта',
      'settings.ehSiteSettingHint':
          'Открыть страницу настроек E-Hentai / ExHentai в новой вкладке',
      'settings.ehProfile': 'Настройки профиля',
      'settings.ehSelectedProfile': 'Выбранный профиль',
      'settings.ehProfileHint':
          'Текущий сайт: @site. Переключает активный профиль сайта через cookie sp, как в приложении.',
      'settings.ehProfileEmpty': 'Профили не найдены',
      'settings.ehProfileSaved': 'Профиль переключён',
      'settings.ehProfileSaveFailed': 'Не удалось переключить профиль: @error',
      'settings.ehProfileLoadFailed': 'Не удалось загрузить профили: @error',
      'settings.ehProfileAndQuota': 'Профиль, квота и активы',
      'settings.ehProfileAndQuotaHint':
          'Эти значения всё ещё зависят от разбора страниц сайта. Пока их можно посмотреть в настройках сайта.',
      'settings.ehAssets': 'Активы',
      'settings.ehImageQuota': 'Квота изображений',
      'settings.ehResetCost': 'Стоимость сброса',
      'settings.ehQuotaUnavailable':
          'Квота изображений доступна только донаторам',
      'settings.ehQuotaReset': 'Квота изображений сброшена',
      'settings.ehQuotaResetFailed':
          'Не удалось сбросить квоту изображений: @error',
      'settings.ehStatusFailed': 'Не удалось загрузить статус EH: @error',
      'settings.galleryListStyle': 'Вид списка галерей',
      'pageListStyle': 'Вид списка галерей (страница)',
      'global': 'Глобально',
      'settings.listModeGrid': 'Сетка',
      'settings.listModeList': 'Список',
      'settings.listModeCompact': 'Компактно',
      'settings.gridColumns': 'Колонки сетки',
      'settings.gridColumnsAuto': 'Авто',
      'settings.downloadGridColumns': 'Колонки сетки загрузок',
      'settings.downloadGridColumnsHint':
          'Применяется к сетке задач загрузки в этом браузере.',
      'settings.detailThumbnailColumns': 'Колонки миниатюр в деталях',
      'settings.detailThumbnailColumnsHint':
          'Применяется к миниатюрам на странице галереи и полной странице миниатюр.',
      'moveCover2RightSide': 'Переместить обложку вправо',
      'settings.moveCoverWebHint':
          'Применяется к широким страницам деталей галереи в этом браузере.',
      'settings.galleryListStyleHint':
          'Применяется к списку галерей на веб-главной сразу и сохраняется в этом браузере.',
      'settings.pageListStyleHint':
          'Переопределяет вид списка галерей для отдельных веб-разделов. Глобально использует стиль выше.',
      'settings.networkWebSummary':
          'Состояние прокси показано на странице сети. После изменения переменных окружения Docker перезапустите сервер.',
      'settings.proxyRouting': 'Маршрутизация запросов',
      'settings.ehProxyRoute': 'Запросы страниц EH/EX',
      'settings.hathProxyRoute': 'Запросы изображений H@H',
      'settings.hathProxyDedicatedHint':
          'JH_HATH_PROXY настроен, поэтому *.hath.network сначала использует этот прокси.',
      'settings.hathProxyFallbackHint':
          'JH_HATH_PROXY не настроен, поэтому *.hath.network использует HTTPS_PROXY/HTTP_PROXY. Задайте JH_HATH_PROXY, если H@H всё ещё недоступен напрямую.',
      'settings.proxyEnvironment': 'Окружение прокси',
      'settings.proxyEnvironmentEmpty': 'Значения прокси не обнаружены.',
      'settings.proxyEnvironmentHint':
          'Здесь показаны только протокол, хост и порт. Учётные данные скрыты.',
      'settings.proxyAuthConfigured': 'авторизация настроена',
      'settings.copyNetworkDiagnostics': 'Копировать диагностику сети',
      'settings.networkRuntimeFlags': 'Диагностика сети',
      'settings.networkRestartHint':
          'Эти значения берутся из окружения запуска сервера. После изменения перезапустите контейнер.',
      'settings.directConnection': 'Напрямую',
      'settings.configured': 'Настроено',
      'settings.notConfigured': 'Не настроено',
      'settings.enabled': 'Включено',
      'settings.disabled': 'Выключено',
      'settings.downloadWebSummary':
          'Настройте группы и приоритеты по умолчанию, проверьте пути и параллельность Docker и управляйте задачами загрузки.',
      'settings.downloadWebIntro':
          'Настройте группы и приоритеты по умолчанию для веб-диалогов загрузки и проверьте параметры Docker на сервере.',
      'settings.downloadDefaults': 'Параметры загрузки по умолчанию',
      'settings.downloadDefaultsSaved': 'Параметры загрузки сохранены',
      'settings.defaultGalleryDownload': 'Загрузка галереи',
      'settings.defaultArchiveDownload': 'Загрузка архива',
      'settings.customGroupName': 'Имя пользовательской группы',
      'settings.downloadServerRuntime': 'Параметры сервера',
      'settings.galleryConcurrency': 'Параллельные галереи',
      'settings.archiveConcurrency': 'Параллельные архивы',
      'settings.jhPublicApiBaseUrl': 'Публичный API JH',
      'settings.jhAppId': 'ID приложения JH',
      'settings.jhApiSecretConfigured': 'Секрет API JH',
      'settings.downloadRuntimeHint':
          'Параллельность и пути задаются переменными окружения Docker и применяются после перезапуска сервера.',
      'settings.performanceWebSummary':
          'Настройте порог анимации списка загрузок Web, чтобы снизить нагрузку браузера на больших группах.',
      'settings.webPerformance': 'Производительность Web',
      'settings.performanceWebIntro':
          'Веб-клиент работает в браузере. Эти локальные настройки влияют на плавность больших списков.',
      'settings.webMaxGalleryNum4Animation': 'Порог анимации групп загрузок',
      'settings.webMaxGalleryNum4AnimationHint':
          'Отключает анимацию значка раскрытия/сворачивания, когда в группе загрузок больше задач, чем это значение. 0 отключает всегда.',
      'settings.resetPerformanceDefaults':
          'Сбросить настройки производительности',
      'settings.performanceSaved': 'Настройки производительности сохранены',
      'settings.advancedWebSummary':
          'Включайте режим без изображений, проверяйте пути Docker и управляйте журналами сервера.',
      'settings.advancedWebIntro':
          'Управляйте загрузкой изображений, журналами сервера и путями Docker для этого веб-экземпляра.',
      'settings.exportData': 'Экспорт данных',
      'settings.exportDataHint':
          'Скачать настройки, правила блокировки, историю, историю поиска и быстрые поиски в JSON. Токены и cookies исключены.',
      'settings.exportDataSuccess': 'Экспорт данных загружен',
      'settings.exportDataFailed': 'Не удалось экспортировать данные: @error',
      'settings.importData': 'Импорт данных',
      'settings.importDataHint':
          'Импортировать экспорт Web или JSON JHenTaiConfig из приложения и объединить с этим сервером. Настройки и именованные элементы перезаписываются; правила блокировки дедублируются.',
      'settings.importDataTitle': 'Импортировать данные?',
      'settings.importDataConfirm':
          'Выберите файл экспорта JHenTai Web или JHenTaiConfig из приложения. Импортированные настройки могут перезаписать текущие значения.',
      'settings.importDataSuccess': 'Импортировано элементов: @count',
      'settings.importDataFailed': 'Не удалось импортировать данные: @error',
      'settings.noImageMode': 'Режим без изображений',
      'settings.noImageModeHint':
          'Скрывает обложки галерей, миниатюры и изображения читалки в этом браузере.',
      'checkClipboard': 'Проверять ссылку на галерею в буфере обмена',
      'settings.checkClipboardHint':
          'При открытии главной страницы искать ссылки на галереи в буфере браузера и предлагать открыть их.',
      'settings.pageCache': 'Кэш страниц',
      'settings.clearPageCache': 'Очистить кэш страниц',
      'settings.clearPageCacheTitle': 'Очистить кэш страниц?',
      'settings.clearPageCacheConfirm':
          'Будут удалены кэшированные ответы страниц EH на сервере.',
      'settings.clearPageCacheFailed':
          'Не удалось очистить кэш страниц: @error',
      'settings.loadPageCacheFailed':
          'Не удалось загрузить кэш страниц: @error',
      'settings.pageCacheSummary': '@count страниц в кэше · @size',
      'settings.serverLogs': 'Журналы сервера',
      'settings.clearLogsTitle': 'Очистить журналы сервера?',
      'settings.clearLogsConfirm':
          'Будут удалены все текущие файлы журналов сервера.',
      'settings.clearLogsFailed': 'Не удалось очистить журналы: @error',
      'settings.loadLogsFailed': 'Не удалось загрузить журналы: @error',
      'settings.loadLogFailed': 'Не удалось загрузить журнал: @error',
      'settings.noLogs': 'Журналов пока нет',
      'settings.copyLog': 'Копировать журнал',
      'settings.downloadLog': 'Скачать журнал',
      'settings.emptyLog': 'Этот журнал пуст',
      'settings.securityWebSummary':
          'Проверьте API-токен, сохранённый в этом браузере, подтвердите подключение или отключитесь и подключитесь заново.',
      'settings.webTokenSecurity': 'Безопасность веб-подключения',
      'settings.webTokenSaved': 'Локальный токен',
      'settings.webTokenSavedYes': 'Сохранён в этом браузере',
      'settings.webTokenSavedNo': 'В этом браузере нет сохранённого токена',
      'settings.webTokenFingerprint': 'Отпечаток токена',
      'settings.webTokenVerifyStatus': 'Статус проверки',
      'settings.webTokenValid': 'Текущий токен действителен',
      'settings.webTokenInvalid': 'Текущий токен недействителен или заменён',
      'settings.securityWebBody':
          'Веб-интерфейс подключается с API-токеном, сохранённым в этом браузере. Полный токен здесь не показывается; это только проверка текущего подключения.',
      'settings.verifyCurrentToken': 'Проверить текущий токен',
      'settings.disconnectWebToken': 'Отключиться и подключиться заново',
      'settings.disconnectWebTokenTitle': 'Отключить текущее веб-подключение?',
      'settings.disconnectWebTokenConfirm':
          'API-токен, сохранённый в этом браузере, будет удалён, а вы вернётесь к настройке. Токен сервера не будет удалён.',
      'settings.webTokenRotateHint':
          'Если токен на сервере был заменён, сначала отключитесь здесь, затем введите новый токен в мастере настройки.',
      'settings.webPasswordAuthHint':
          'Защитить эту сессию браузера локальным 4-значным PIN-кодом.',
      'settings.lockNow': 'Заблокировать сейчас',
      'settings.disablePasswordAuthTitle': 'Отключить пароль?',
      'settings.disablePasswordAuthConfirm':
          'Локальный PIN-код, сохранённый в этом браузере, будет удалён.',
      'settings.passwordAuthEnabled': 'Пароль включён',
      'settings.mouseWheelIntro':
          'Поведение колёсика над изображением в читалке (горизонтальные режимы страниц).',
      'settings.webWheelScrollSpeedHint':
          'Управляет скоростью прокрутки колёсиком в списках галерей Web.',
      'settings.mouseWheelReadHint': 'Направление, предзагрузка и другое',
      'settings.aboutVersionLabel': 'Версия',
      'settings.aboutAuthorLabel': 'Автор',
      'settings.aboutTelegramTitle': 'Telegram (в основном китайский)',
      'settings.aboutTelegramHint': 'Ссылка на сообщество',
      'settings.aboutQA': 'Вопросы и ответы',
      'settings.aboutWebForkNote':
          'Этот веб-интерфейс из форка JHenTai Docker; исходный проект указан выше.',

      // history
      'history.title': 'История',
      'history.empty': 'Нет истории просмотров',
      'history.clearAll': 'Очистить всё',
      'history.clearTitle': 'Очистить историю',
      'history.clearConfirm': 'Вы уверены, что хотите очистить всю историю?',
      'history.loadFailed': 'Ошибка загрузки истории: @error',
      'history.loadMore': 'Загрузить ещё',
      'history.search': 'Поиск в истории...',
      'history.jumpToPage': 'Перейти к странице истории',
      'history.pageRange': 'Диапазон: 1 - @total, текущая: @current',

      // search history
      'searchHistory.clearAll': 'Очистить историю поиска',
      'searchHistory.translate': 'Перевести историю поиска',

      // comment
      'comment.placeholder': 'Напишите комментарий...',
      'comment.send': 'Отправить',
      'comment.posted': 'Комментарий опубликован',
      'comment.postedMsg': 'Ваш комментарий опубликован',
      'comment.postFailed': 'Ошибка публикации: @error',
      'comment.voteFailed': 'Ошибка голосования: @error',
      'comment.scoreDetails': 'Детали оценки',
      'lastEditedOn': 'Последнее редактирование',
      'comment.update': 'Обновить комментарий',
      'comment.updated': 'Комментарий обновлён',
      'comment.updatedMsg': 'Ваш комментарий обновлён',
      'comment.updateFailed': 'Не удалось обновить комментарий: @error',
      'comment.tooShort': 'Комментарий слишком короткий',
      'comment.atLeast3Characters': 'Минимум 3 символа',

      // ranklist
      'ranklist.title': 'Рейтинг',
      'ranklist.allTime': 'За всё время',
      'ranklist.year': 'За год',
      'ranklist.month': 'За месяц',
      'ranklist.yesterday': 'Вчера',

      // thumbnails
      'thumbnails.title': 'Миниатюры (@count)',
      'thumbnails.grid': 'Сетка миниатюр',
      'thumbnails.jumpToPage': 'Перейти к странице',
      'thumbnails.pageRange': 'Диапазон: 1 - @total',
      'thumbnails.loadFailed': 'Ошибка загрузки миниатюр: @error',

      // tag translation
      'tagInfo.title': 'Сведения о теге',
      'tagInfo.empty': 'Сведения о теге недоступны',
      'tagInfo.loadFailed': 'Не удалось загрузить сведения о теге: @error',
      'showR18GImageDirectly': 'Показывать R18G изображения сразу',
      'warningImageHint': 'R18G изображение, нажмите для просмотра',
      'tagTranslation.title': 'Перевод тегов',
      'tagTranslation.loaded': '@count тегов загружено',
      'tagTranslation.notLoaded': 'База тегов не загружена',
      'tagTranslation.lastUpdate': 'Последнее обновление: @time',
      'tagTranslation.refresh': 'Обновить базу тегов',
      'tagTranslation.refreshSuccess': '@count тегов обновлено',
      'tagTranslation.refreshFailed': 'Ошибка обновления: @error',

      // list mode
      'listMode.toggle': 'Переключить режим отображения',
      'listMode.grid': 'Сетка',
      'listMode.list': 'Список',
      'listMode.listCompact': 'Компактный список',

      // quick search
      'quickSearch.title': 'Быстрый поиск',
      'quickSearch.empty': 'Нет сохранённых поисков',
      'quickSearch.saveCurrent': 'Сохранить текущий поиск',
      'quickSearch.saveTitle': 'Сохранить быстрый поиск',
      'quickSearch.editTitle': 'Редактировать быстрый поиск',
      'quickSearch.nameLabel': 'Название',
      'quickSearch.addNew': 'Добавить быстрый поиск',
      'quickSearch.keywordLabel': 'Ключевые слова',
      'quickSearch.keywordHint': 'Как в строке поиска на главной',
      'quickSearch.saved': 'Сохранено',
      'quickSearch.deleted': 'Удалено',
      'quickSearch.deleteTitle': 'Удалить быстрый поиск',
      'quickSearch.deleteConfirm': 'Удалить «@name»?',

      // tag suggest
      'tagSuggest.tag': 'Тег',

      // common extras
      'common.save': 'Сохранить',

      // reader enhancements
      'reader.fitWidth': 'По ширине',
      'reader.doubleColumn': 'Двойная страница',
      'reader.autoStart': 'Автопролистывание',
      'reader.autoStop': 'Остановить автопролистывание',

      'enableBottomMenu': 'Включить нижнее меню',

      'enablePageTurnAnime': 'Включить анимацию перелистывания',
      'enableDoubleTapToScaleUp': 'Включить увеличение двойным нажатием',
      'enableTapDragToScaleUp':
          'Включить увеличение касанием с перетаскиванием',
      'reverseTurnPageDirection': 'Инвертировать перелистывание касанием',
      'disablePageTurningOnTap': 'Отключить перелистывание касанием',
      // block rules
      'blockRule.title': 'Правила блокировки',
      'blockRule.empty': 'Нет настроенных правил блокировки',
      'blockRule.add': 'Добавить правило',
      'blockRule.edit': 'Редактировать правило',
      'blockRule.manage': 'Управление правилами блокировки',
      'useBuiltInBlockedUsers':
          'Включить встроенный список заблокированных пользователей',
      'useBuiltInBlockedUsersHint':
          'Фильтровать комментарии пользователей из встроенного списка',
      'blockRule.ruleCount': '@count правил',
      'blockRule.ungrouped': 'Без группы',
      'blockRule.deleteGroup': 'Удалить группу',
      'blockRule.target': 'Цель',
      'blockRule.attribute': 'Атрибут',
      'blockRule.pattern': 'Шаблон',
      'blockRule.expression': 'Выражение',
      'blockRule.expressionHint': 'Значение для сопоставления',
      'blockRule.groupId': 'ID группы',
      'blockRule.groupIdHint': 'Необязательное имя группы',
      'blockRule.blocked': 'Заблокировано',
      'blockRule.tagBlocked': 'Тег "@tag" заблокирован',
      'blockRule.uploaderBlocked': 'Загрузчик "@uploader" заблокирован',
      'blockRule.blockTag': 'Заблокировать тег',
      'blockRule.blockUploader': 'Заблокировать загрузчика',
      'blockRule.blockCommentUser': 'Заблокировать автора комментария',
      'blockRule.blockCommentUserConfirm':
          'Заблокировать автора комментария "@user"?',
      'blockRule.commentUserBlocked': 'Автор комментария "@user" заблокирован',

      // download enhancements
      'simpleSearch': 'Простой',
      'regexSearch': 'Regex',
      'downloads.search': 'Поиск загрузок...',
      'downloads.allGroups': 'Все группы',
      'downloads.group': 'Группа',

      // tag voting
      'tagVote.search': 'Поиск',
      'tagVote.searchUploader': 'Найти загрузчика',
      'tagVote.voteUp': 'За',
      'tagVote.voteDown': 'Против',
      'tagVote.success': 'Голос учтён',
      'tagVote.votedUp': 'Проголосовали за "@tag"',
      'tagVote.votedDown': 'Проголосовали против "@tag"',
      'tagVote.failed': 'Ошибка голосования: @error',
      'tagVote.addTag': 'Добавить тег',
      'tagVote.addTagHint': 'Введите новые теги через запятую',
      'tagVote.addSuccess': 'Тег добавлен',
      'tagVote.addFailed': 'Не удалось добавить тег: @error',

      // responsive layout
      'home.selectGallery': 'Выберите галерею для просмотра деталей',
      'home.selectGalleryHint': 'Детали галереи появятся в этой панели.',

      // gallery detail extras
      'detail.parentGallery': 'Родительская галерея',
      'detail.newerVersion': 'Доступна новая версия',
      'detail.versionHistory': 'История версий',
      'detail.currentVersion': 'Текущая версия',
      'detail.torrents': 'Торренты',
      'detail.torrentCount': 'Торрент (@count)',
      'detail.noTorrents': 'Нет торрентов',
      'detail.outdatedTorrents': 'Устаревшие',
      'detail.downloadTorrent': 'Скачать торрент',
      'detail.copyMagnet': 'Копировать magnet',
      'detail.torrentSeeds': 'Сиды @count',
      'detail.torrentPeers': 'Пиры @count',
      'detail.torrentDownloads': 'Загрузки @count',
      'detail.loadTorrentsFailed': 'Не удалось загрузить торренты: @error',
      'detail.hhDownload': 'H@H загрузка',
      'detail.noHHArchives': 'Нет доступных H@H архивов',
      'detail.loadHHFailed': 'Не удалось загрузить H@H архивы: @error',
      'detail.hhSubmitFailed': 'Не удалось запросить H@H загрузку: @error',
      'detail.hhSubmitted': 'Запрос на H@H загрузку отправлен',

      // settings extras
      'settings.cookieStatusFull': 'Cookies OK (включая igneous — EX доступен)',
      'settings.cookieStatusNoIgneous':
          'Cookies установлены, но нет igneous — EX может не работать',
      'settings.cookieStatusNone': 'Cookies для входа не установлены',
      'settings.siteSwitched': 'Переключено на @site',

      // download progress in detail
      'detail.completed': 'Завершено',
      'detail.retryDownload': 'Повторить',
      'detail.readDownloaded': 'Читать загруженное',
      'detail.deleteDownload': 'Удалить загрузку',
      'detail.deleteDownloadConfirm': 'Удалить эту загрузку и файлы?',
      'detail.archiveCompleted': 'Архив готов',

      // detail enhancements
      'detail.share': 'Поделиться',
      'detail.jumpToPage': 'Перейти к странице',
      'detail.jumpToThumbnail': 'Перейти к миниатюре',
      'detail.similarSearch': 'Похожий поиск',
      'detail.blockGallery': 'Заблокировать галерею',
      'detail.allComments': 'Все комментарии',
      'detail.thumbnails': 'Миниатюры (@count)',
      'detail.viewAllThumbnails': 'Показать все миниатюры',
      'detail.galleryBlocked': 'Галерея заблокирована',
      'detail.jumpPageHint': 'Введите номер страницы (1-@max)',

      // reader enhancements
      'reader.saveImage': 'Сохранить изображение',
      'reader.openInNewTab': 'Открыть в новой вкладке',
      'reader.reloadImage': 'Перезагрузить',
      'reader.interval': 'Интервал',
      'reader.preload': 'Предзагрузка',
      'reader.imageSpacing': 'Отступы изображений',
      'reader.autoInterval': 'Интервал автопролистывания',
      'reader.startAutoMode': 'Начать',
      'reader.saveFailed': 'Не удалось сохранить изображение',
      'reader.redownloadHint':
          'Откройте «Загрузки», чтобы повторить или перезапустить загрузку этой галереи.',
      'reader.deviceOrientation': 'Ориентация устройства',
      'reader.deviceOrientationWebHint':
          'Браузер не может заблокировать ориентацию как приложение. Используйте полноэкранный режим или системную блокировку поворота.',
      'toggleFullScreen': 'Переключить полноэкранный режим',

      // settings reader
      'settings.defaultFavoriteSlot': 'Папка избранного по умолчанию',
      'settings.defaultFavoriteNone': 'Нет (спрашивать каждый раз)',
      'settings.defaultFavoriteHint':
          'Если включено, нажмите на сердечко для папки по умолчанию или удерживайте, чтобы выбрать другую.',
      'settings.readerSettings': 'Настройки чтения',
      'settings.defaultDirection': 'Направление по умолчанию',
      'settings.imageSpacing': 'Отступы изображений',
      'settings.preloadPages': 'Предзагрузка страниц (онлайн)',
      'settings.preloadPagesLocal': 'Предзагрузка страниц (локально)',
      'settings.imageRegionWidthRatioHint':
          'Влияет только на вертикальное чтение. Режим по ширине по-прежнему занимает всю ширину окна.',
      'settings.autoInterval': 'Интервал автопролистывания',
      'settings.fitWidth': 'По ширине',
      'hideScroll2TopButton': 'Кнопка наверх',
      'whenScrollUp': 'При прокрутке вверх',
      'whenScrollDown': 'При прокрутке вниз',
      'never': 'Никогда',
      'always': 'Всегда',
      'preloadGalleryCover': 'Предзагружать обложки галерей',
      'preloadGalleryCoverHint':
          'Предзагружает обложки галерей, которые ещё не показаны',
      'simpleDashboardMode': 'Упрощенная главная страница',
      'simpleDashboardModeHint': 'Скрыть Рейтинги и Популярное',
      'showDawnInfo': 'Показывать событие рассвета',
      'showEncounterMonster': 'Показывать событие встречи HentaiVerse',

      // home enhancements
      'home.scrollToTop': 'Наверх',
      'home.imageSearch': 'Поиск по изображению',
      'home.imageSearchFailed': 'Поиск по изображению не удался: @error',
      'home.imageSearchMode': 'Результаты поиска по изображению',
      'stats.title': 'Статистика посещений',
      'stats.totalVisits': 'Всего посещений: @n',
      'stats.allTime': 'За всё время',
      'stats.year': 'Год',
      'stats.month': 'Месяц',
      'stats.day': 'День',
      'stats.period': 'Период',
      'stats.ranking': 'Рейтинг',
      'stats.score': 'Очки',
      'stats.visits': 'Посещения',
      'stats.hits': 'Просмотры',
      'stats.noSeries': 'Нет данных для графика',
      'usertags.title': 'Отслеживаемые / скрытые теги',
      'usertags.loadFailed': 'Не удалось загрузить: @error',
      'usertags.add': 'Добавить тег',
      'usertags.tagHint': 'Формат namespace:key',
      'usertags.watch': 'Отслеживать',
      'usertags.hidden': 'Скрыт',
      'usertags.watchAdded': 'Тег добавлен в отслеживаемые',
      'usertags.hiddenAdded': 'Тег добавлен в скрытые',
      'usertags.defaultTagSet': 'Набор тегов по умолчанию',
      'usertags.defaultTagSetNone': 'Нет (спрашивать каждый раз)',
      'usertags.none': 'Нет',
      'usertags.weight': 'Вес',
      'usertags.editTitle': 'Редактировать тег',
      'usertags.delete': 'Удалить',
      'usertags.added': 'Добавлено',
      'usertags.updated': 'Обновлено',
      'usertags.deleted': 'Удалено',
      'usertags.currentList': 'Настроенные теги',
      'usertags.tagColor': 'Цвет тега',
      'usertags.tagSetColor': 'Цвет набора тегов',
      'usertags.changeColor': 'Изменить цвет',
      'usertags.colorDefault': 'Использовать цвет по умолчанию',
      'enableDefaultTagSet': 'Включить набор тегов по умолчанию',
      'enableDefaultTagSetHint':
          'Использовать набор тегов по умолчанию напрямую',
      'disableDefaultTagSetHint': 'Выбирать вручную',
      'chooseTagSet': 'Выбрать набор тегов',
      'asYourDefault': 'По умолчанию',
      'downloads.sortBy': 'Сортировка',
      'downloads.sortPriority': 'Приоритет',
      'downloads.sortTime': 'Время',
      'downloads.sortTitle': 'Название',
      'downloads.sortStatus': 'Статус',
      'downloads.allCategories': 'Все категории',
      'downloads.categoryFilter': 'Категория EH',
      'downloads.setPriority': 'Приоритет',
      'downloads.setGroup': 'Группа',
      'downloads.priorityLabel': 'Приоритет @n',
      'downloads.groupLabel': 'Группа',
      'downloads.groupActions': 'Действия группы',
      'downloads.renameGroup': 'Переименовать группу',
      'downloads.renameGroupConfirm': 'Переименовать группу "@group" в:',
      'downloads.groupRenamed': 'Группа изменена для задач: @count',
      'downloads.clearGroup': 'Очистить группу',
      'downloads.clearGroupConfirm':
          'Переместить @count задач из "@group" обратно в default?',
      'downloads.groupCleared': '@count задач перемещено обратно в default',
      'downloads.superseded': 'Обновлено до gid @gid',
      'downloads.editTask': 'Редактировать задачу',
      'downloads.selectTasks': 'Выбрать задачи',
      'downloads.selectVisible': 'Выбрать видимые задачи',
      'downloads.pauseVisible': 'Поставить видимые задачи на паузу',
      'downloads.resumeVisible': 'Возобновить видимые задачи',
      'downloads.reDownloadVisible': 'Скачать видимые галереи заново',
      'downloads.reUnlockVisible': 'Разблокировать видимые архивы заново',
      'downloads.reDownloadConfirm':
          'Удалить скачанные файлы этой галереи и начать заново?',
      'downloads.reDownloadVisibleConfirm':
          'Удалить файлы и перезапустить @count видимых галерей?',
      'downloads.reDownloadBatchConfirm':
          'Удалить файлы и перезапустить @scope?',
      'downloads.reUnlockArchive': 'Разблокировать архив заново',
      'downloads.reUnlockArchiveConfirm':
          'Очистить ссылку загрузки архива и разблокировать заново?',
      'downloads.changeVisibleGroup': 'Изменить группу видимых задач',
      'downloads.changeVisibleGroupConfirm':
          'Переместить @count видимых задач в эту группу.',
      'downloads.changeBatchGroup': 'Изменить группу задач',
      'downloads.changeBatchGroupConfirm': 'Переместить @scope в эту группу.',
      'downloads.deleteVisible': 'Удалить видимые задачи',
      'downloads.deleteVisibleConfirm':
          'Выберите, как удалить @count видимых задач.',
      'downloads.deleteBatchConfirm': 'Выберите, как удалить @scope.',
      'downloads.visibleTaskCount': 'видимых задач: @count',
      'downloads.selectedTaskCount': 'Выбрано задач: @count',
      'downloads.noBatchTargets': 'В текущем списке нет подходящих задач',
      'downloads.batchPaused': 'Поставлено на паузу: @count',
      'downloads.batchResumed': 'Возобновлено: @count',
      'downloads.batchRedownloaded': 'Перезапущено задач: @count',
      'downloads.batchReUnlocked': 'Архивов разблокировано заново: @count',
      'downloads.batchGroupChanged': 'Группа изменена для задач: @count',
      'downloads.batchDeleted': 'Удалено задач: @count',
      'detail.startDownloadTitle': 'Начать загрузку',
      'detail.downloadGroup': 'Группа',
      'existingGroup': 'Существующая группа',
      'groupName': 'Имя группы',
      'detail.downloadPriority': 'Приоритет (больше — раньше)',
      'detail.stats': 'Статистика',
      'detail.similarByTitle': 'Похожее название',
      'detail.upgradeDownload': 'Обновить до новой версии',
      'detail.upgradeOk': 'Загрузка новой версии началась',
      'detail.upgradeFailed': 'Не удалось обновить: @error',
      'detail.archiveNewVersionHint':
          'Есть более новая версия галереи. Скачайте архив со страницы новой галереи.',
      'detail.openNewVersion': 'Открыть новую версию',
      'settings.usertags': 'Отслеживаемые / скрытые теги',
    };
  }
}
