class WebZhCN {
  static Map<String, String> keys() {
    return {
      // common
      'common.cancel': '取消',
      'common.ok': '确定',
      'common.confirm': '确定',
      'common.error': '错误',
      'common.success': '成功',
      'common.failed': '失败',
      'common.retry': '重试',
      'common.delete': '删除',
      'common.reset': '重置',
      'common.refresh': '刷新',
      'common.loading': '加载中...',
      'common.unknown': '未知',
      'common.images': '@count 张图片',
      'common.pages': '@count 页',
      'common.open': '打开',
      'dawnOfaNewDay': '黎明之时',
      'encounterMonster': '你遭遇了一只怪兽！',
      'encounterMonsterHint': '点击跳转至 HentaiVerse 战斗。',

      'share': '分享',
      'save': '保存',
      'reload': '重新加载',
      'cancel': '取消',
      'resampleImage': '压缩图',
      'originalImage': '原图',
      'downloadOriginalImage': '下载原图',
      'downloadOriginalImageByDefault': '默认选中下载原图',
      'downloadAllGallerysOfSamePriority': '同一优先级下同时下载所有画廊',
      'downloadAllGallerysOfSamePriorityHint':
          '默认情况下逐优先级下载画廊，且每个优先级下只会同时下载一个画廊',
      'restoreDownloadTasks': '恢复下载任务',
      'restoreDownloadTasksHint': '通过下载元数据来恢复下载记录',
      'restoreTasksAutomatically': '自动恢复下载任务',
      'restoreTasksAutomaticallyHint': '服务端启动时通过下载元数据自动恢复任务',
      'restoredGalleryCount': '已恢复画廊',
      'restoredArchiveCount': '已恢复归档',
      'reDownload': '重新下载',
      'deleteTask': '仅删除任务',
      'deleteTaskAndImages': '删除任务和图片',
      'hasCopiedToClipboard': '已复制到剪贴板',
      'displayFirstPageAlone': '单独展示首页',
      'showThumbnails': '显示缩略图',
      'showScrollBar': '显示滚动条',
      'showStatusInfo': '底部显示状态信息',
      'spaceBetweenImages': '图片间隔',
      'defaultTab': '启动时默认菜单',

      // setup
      'setup.title': 'JHenTai 服务器设置',
      'setup.description': '请输入服务器日志中显示的 API Token 以连接。',
      'setup.tokenLabel': 'API Token',
      'setup.connect': '连接',
      'setup.emptyToken': '请输入 Token',
      'setup.invalidToken': 'Token 无效，请查看服务器日志获取正确的 Token。',
      'setup.tokenHint': 'Token 为一行共 64 位十六进制字符，请完整复制日志中的整行，不要只复制前半段。',
      'setup.tokenPasteHint': '请粘贴日志中的完整 64 位 Token',
      'setup.tokenCharCount': '已输入 @current / @total 位',
      'setup.tokenWrongLength': 'Token 必须为 64 位十六进制字符（请从 docker logs 完整复制一行）。',
      'setup.tokenHelpTitle': '如何从日志中查找 Token',
      'setup.tokenHelpP1': '在运行 Docker 的主机上打开终端，执行：',
      'setup.tokenHelpP2':
          '找到以 [JHenTai] API token for web UI 开头的行，复制冒号后的 64 位十六进制字符（整段 Token，不要截断）。若容器名不是 jhentai，请将下方命令中的名称改为你的容器名。',
      'setup.tokenHelpAlt': '若没有该行，可从服务端数据库读取（默认容器名 jhentai，数据目录 /data）：',

      // home
      'home.title': 'JHenTai',
      'home.search': '搜索画廊...',
      'home.advancedSearch': '高级搜索',
      'home.searchFilterSheetTitle': '分类与筛选',
      'home.leftPaneWidthPx': '@w px',
      'home.twoPaneDividerTooltip': '左栏 @w px · 双击分隔条恢复默认宽度',
      'home.downloads': '下载',
      'home.localGalleries': '本地画廊',
      'home.settings': '设置',
      'home.subtitle': 'E-Hentai 客户端',
      'home.home': '首页',
      'home.popular': '热门',
      'home.favorites': '收藏',
      'home.watched': '关注',
      'home.noGalleries': '未找到画廊',
      'home.previous': '上一页',
      'home.next': '下一页',
      'home.jumpDate': '跳转到日期',
      'home.page': '第 @page 页',
      'home.loadFailed': '加载失败: @error',
      'home.favSortTitle': '收藏排序',
      'home.favSortFavorited': '按收藏时间',
      'home.favSortPublished': '按发布时间',
      'home.favAllFolders': '全部',
      'home.favSlotShort': '夹 @n',
      // advanced search
      'home.categoryFilter': '分类筛选',
      'home.minimumRating': '最低评分',
      'home.ratingAny': '不限',
      'home.searchIn': '搜索范围',
      'home.galleryName': '画廊名称',
      'home.tags': '标签',
      'home.description': '描述',
      'home.showExpunged': '显示已删除',
      'home.onlyShowGalleriesWithTorrents': '只显示有种子的画廊',
      'home.pageRange': '页数范围',
      'home.pageAtLeast': '页数至少',
      'home.pageAtMost': '页数最多',
      'home.language': '语言',
      'home.languageNone': '无',
      'home.disableFilterForLanguage': '禁用语言过滤',
      'home.disableFilterForUploader': '禁用上传者过滤',
      'home.disableFilterForTags': '禁用标签过滤',
      'home.applySearch': '应用并搜索',
      // category names
      'category.doujinshi': '同人志',
      'category.manga': '漫画',
      'category.artistCg': '插画',
      'category.gameCg': '游戏CG',
      'category.western': '西方',
      'category.nonH': '非H',
      'category.imageSet': '图集',
      'category.cosplay': 'Cosplay',
      'category.asianPorn': '亚洲',
      'category.misc': '杂项',

      // gallery detail
      'detail.copyUrl': '复制画廊链接',
      'detail.copied': '已复制',
      'detail.removeFromFav': '从收藏中移除',
      'detail.addToFav': '添加到收藏',
      'detail.addToFavTitle': '添加到收藏',
      'detail.favRemoved': '已移除',
      'detail.favRemovedMsg': '已从收藏中移除',
      'detail.favAdded': '已添加',
      'detail.favAddedMsg': '已添加到 @name',
      'detail.favError': '收藏操作失败: @error',
      'detail.favSlot': '收藏夹 @n',
      'detail.favNoteHint': '收藏备注（可选）',
      'detail.favQuickAddTooltip': '加入默认收藏夹（长按）',
      'detail.rateTitle': '为画廊评分',
      'detail.rateSubmit': '提交',
      'detail.rated': '已评分',
      'detail.ratedMsg': '你的评分: @rating',
      'detail.rateFailed': '评分失败: @error',
      'detail.rateLoginRequired': '无法评分 — 需要登录',
      'detail.readOnline': '在线阅读',
      'detail.readOnlineResume': '在线阅读（上次第 @page 页）',
      'detail.downloadGallery': '下载画廊',
      'detail.archiveResample': '归档（压缩）',
      'detail.archiveOriginal': '归档（原图）',
      'detail.downloadArchive': '下载归档',
      'detail.downloadStarted': '下载已开始',
      'detail.galleryQueued': '画廊下载已加入队列',
      'detail.archiveQueued': '归档下载已加入队列',
      'detail.downloadFailed': '下载失败: @error',
      'detail.archiveFailed': '归档下载失败: @error',
      'detail.noArchive': '没有可用的归档',
      'detail.tags': '标签',
      'detail.comments': '评论 (@count)',
      'detail.anonymous': '匿名',
      'detail.loadFailed': '加载画廊详情失败: @error',

      // reader
      'reader.loading': '加载画廊中...',
      'reader.loadingGalleryMeta': '正在加载页面列表...',
      'reader.resolvingFirstPages': '正在解析图片页...',
      'reader.resolvingImagePage': '正在解析页面...',
      'reader.loadingImage': '加载图片中...',
      'reader.loadFailed': '加载画廊失败: @error',
      'reader.imageFailed': '图片加载失败',
      'reader.noImages': '没有提供图片',
      'reader.directionLabel': '阅读方向: @dir',
      'reader.ltr': '从左到右',
      'reader.rtl': '从右到左',
      'reader.vertical': '上下滚动',
      'reader.wheelAction': '图片上的鼠标滚轮',
      'reader.wheelActionPage': '翻页',
      'reader.wheelActionZoom': '缩放图片',
      'reader.wheelActionVerticalHint':
          '竖向与适应宽度模式始终滚动列表；本选项仅作用于从左到右、从右到左与双页模式。',
      'reader.wheelInvertPageTurn': '反转滚轮翻页方向',
      'reader.wheelInvertPageTurnSubtitle': '交换滚轮/触控板滚动时「下一页」与「上一页」的对应方向。',

      // downloads
      'downloads.title': '下载',
      'downloads.gallery': '画廊',
      'downloads.archive': '归档',
      'downloads.noGallery': '没有画廊下载',
      'downloads.noArchive': '没有归档下载',
      'downloads.read': '阅读',
      'downloads.pause': '暂停',
      'downloads.resume': '继续',
      'downloads.deleteTitle': '删除下载',
      'downloads.deleteConfirm': '请选择是否保留已下载文件。',
      'downloads.loadFailed': '加载任务失败: @error',
      // gallery statuses
      'downloads.gStatus0': '无',
      'downloads.gStatus1': '下载中',
      'downloads.gStatus2': '已暂停',
      'downloads.gStatus3': '已完成',
      'downloads.gStatus4': '失败',
      // archive statuses
      'downloads.aStatus0': '无',
      'downloads.aStatus1': '解锁中',
      'downloads.aStatus2': '解析链接',
      'downloads.aStatus3': '下载中',
      'downloads.aStatus4': '已下载',
      'downloads.aStatus5': '解压中',
      'downloads.aStatus6': '已完成',
      'downloads.aStatus7': '已暂停',
      'downloads.aStatus8': '失败',

      // local
      'local.title': '本地画廊',
      'local.noGalleries': '未找到本地画廊',
      'local.helpText': '将目录挂载到 Docker 容器中\n或将画廊放入 local_gallery 文件夹',
      'local.scanNow': '立即扫描',
      'local.empty': '空',
      'local.noImages': '此画廊中没有图片',
      'local.loadFailed': '加载画廊图片失败: @error',
      'local.loadListFailed': '加载本地画廊失败: @error',
      'local.deleteTitle': '删除本地画廊',
      'local.deleteConfirm': '删除「@title」的本地文件？',
      'local.deleteSuccess': '本地画廊已删除',
      'local.deleteFailed': '删除本地画廊失败: @error',
      'local.parentDirectory': '上级目录',

      // settings
      'settings.title': '设置',
      'settings.account': '账号',
      'settings.loggedIn': '已登录: @user',
      'settings.logout': '退出登录',
      'settings.logoutSuccess': '已退出登录',
      'settings.logoutFailed': '退出登录失败: @error',
      'settings.cookieLogin': '使用 Cookie 登录（推荐）',
      'settings.cookieHint': 'EH 论坛登录在服务器环境中被 Cloudflare 拦截。'
          '请在浏览器中登录后复制 Cookie 到此处。\n'
          '步骤: 登录 e-hentai.org → F12 → 应用 → Cookie → 复制以下值。',
      'settings.cookiePlaceholder':
          'ipb_member_id=xxx; ipb_pass_hash=xxx; igneous=xxx',
      'settings.setCookies': '设置 Cookie',
      'settings.cookieSuccess': 'Cookie 设置成功',
      'settings.cookieFailed': '设置 Cookie 失败: @error',
      'settings.cookieEmpty': '请粘贴 Cookie',
      'settings.credentialLogin': '使用账号密码登录（可能因 Cloudflare 失败）',
      'settings.username': '用户名',
      'settings.password': '密码',
      'settings.login': '登录',
      'settings.loginSuccess': '登录成功',
      'settings.loginFailed': '登录失败',
      'settings.loginError': '登录失败: @error',
      'settings.emptyCredentials': '请输入用户名和密码',
      'settings.site': '站点',
      'redirect2Eh': '优先重定向至表站',
      'redirect2EhHint': '优先尝试从表站加载画廊详情页，以获得更好的网络体验。',
      'settings.appearance': '外观',
      'settings.themeMode': '主题模式',
      'settings.system': '跟随系统',
      'settings.light': '浅色',
      'settings.dark': '深色',
      'settings.accentColor': '主题色',
      'settings.serverInfo': '服务器信息',
      'settings.dataDir': '数据目录',
      'settings.downloadDir': '下载目录',
      'settings.localGalleryDir': '本地画廊目录',
      'settings.extraScanPaths': '额外扫描路径',
      'settings.switchSiteFailed': '切换站点失败: @error',
      'settings.language': '语言',
      'settings.sectionData': '数据与工具',
      'settings.sectionStyle': '样式',
      'settings.sectionRead': '阅读',
      'settings.sectionTags': '标签与过滤',
      'settings.sectionOther': '其他',
      'settings.openDownloads': '下载任务',
      'settings.openHistory': '浏览记录',
      'settings.openLocal': '本地画廊',
      'settings.openQuickSearch': '快速搜索',
      'settings.networkNote': '网络与代理',
      'settings.networkWebBody':
          '代理等网络选项在服务器或 Docker 环境中配置；此页会显示当前运行时代理状态，便于排查 EH/EX 与 H@H 图片请求。',
      'settings.about': '关于',
      'settings.appVersion': '版本 @version（@build）',
      'settings.hubMenu': '设置菜单',
      'settings.menuWebDocker': '网页与服务器',
      'settings.menuWebDockerSubtitle':
          '下载入口、Docker 路径、网络/代理说明，以及性能与安全提示（仅 Web 版）。',
      'settings.menuEH': 'E-Hentai',
      'settings.menuStyle': '样式',
      'settings.menuRead': '阅读',
      'settings.menuPreference': '偏好',
      'settings.menuNetwork': '网络',
      'settings.menuDownload': '下载',
      'settings.menuPerformance': '性能',
      'settings.menuMouseWheel': '鼠标滚轮',
      'settings.menuAdvanced': '高级',
      'settings.menuSecurity': '安全',
      'settings.ehRequiresLogin': '请先在「账号」中登录后再修改站点与 Cookie 状态。',
      'settings.ehMyTags': '我的标签',
      'settings.ehMyTagsHint': '管理在线关注和隐藏的标签',
      'settings.ehSiteSetting': '站点设置',
      'settings.ehSiteSettingHint': '在新标签页打开 E-Hentai / ExHentai 设置页',
      'settings.ehProfile': 'Profile 设置',
      'settings.ehSelectedProfile': '当前 Profile',
      'settings.ehProfileHint':
          '当前站点: @site。与 App 一样通过 sp Cookie 切换当前站点使用的 Profile。',
      'settings.ehProfileEmpty': '未找到可用 Profile',
      'settings.ehProfileSaved': 'Profile 已切换',
      'settings.ehProfileSaveFailed': '切换 Profile 失败: @error',
      'settings.ehProfileLoadFailed': '加载 Profile 失败: @error',
      'settings.ehProfileAndQuota': '档案、配额与资产',
      'settings.ehProfileAndQuotaHint': '这些数据仍依赖站点页面解析；当前可在站点设置页中查看。',
      'settings.ehAssets': '资产',
      'settings.ehImageQuota': '图片配额',
      'settings.ehResetCost': '重置花费',
      'settings.ehQuotaUnavailable': '图片配额仅捐赠用户可查看',
      'settings.ehQuotaReset': '图片配额已重置',
      'settings.ehQuotaResetFailed': '重置图片配额失败: @error',
      'settings.ehStatusFailed': '加载 EH 状态失败: @error',
      'settings.galleryListStyle': '画廊列表样式',
      'pageListStyle': '画廊列表样式（页面）',
      'global': '全局',
      'settings.listModeGrid': '网格',
      'settings.listModeList': '列表',
      'settings.listModeCompact': '紧凑',
      'settings.gridColumns': '网格列数',
      'settings.gridColumnsAuto': '自动',
      'settings.detailThumbnailColumns': '详情页缩略图列数',
      'settings.detailThumbnailColumnsHint': '应用到画廊详情页缩略图和完整缩略图页。',
      'settings.galleryListStyleHint': '会立即应用到 Web 首页画廊列表，并保存在当前浏览器。',
      'settings.pageListStyleHint': '为各个 Web 页面单独覆盖画廊列表样式；全局表示使用上方样式。',
      'settings.networkWebSummary': '网络代理状态请在「网络」页查看；修改 Docker 环境变量后需重启服务端。',
      'settings.proxyRouting': '请求路由',
      'settings.ehProxyRoute': 'EH/EX 页面请求',
      'settings.hathProxyRoute': 'H@H 图片请求',
      'settings.hathProxyDedicatedHint':
          '已配置 JH_HATH_PROXY，*.hath.network 会优先走这个代理。',
      'settings.hathProxyFallbackHint':
          '未配置 JH_HATH_PROXY，*.hath.network 会沿用 HTTPS_PROXY/HTTP_PROXY；如果 H@H 仍直连失败，请单独设置 JH_HATH_PROXY。',
      'settings.proxyEnvironment': '代理环境变量',
      'settings.proxyEnvironmentEmpty': '未读取到代理环境变量。',
      'settings.proxyEnvironmentHint': '为安全起见，这里只显示协议、主机和端口，不显示账号密码。',
      'settings.networkRuntimeFlags': '网络诊断开关',
      'settings.networkRestartHint': '这些值来自服务端启动环境，修改后需要重启容器生效。',
      'settings.directConnection': '直连',
      'settings.configured': '已配置',
      'settings.notConfigured': '未配置',
      'settings.enabled': '已启用',
      'settings.disabled': '未启用',
      'settings.downloadWebSummary': '设置下载默认分组与优先级，查看 Docker 下载路径和并发，并管理下载任务。',
      'settings.downloadWebIntro': '设置网页下载弹窗使用的默认分组和优先级，并查看服务端 Docker 下载参数。',
      'settings.downloadDefaults': '下载默认值',
      'settings.downloadDefaultsSaved': '下载默认值已保存',
      'settings.defaultGalleryDownload': '画廊下载',
      'settings.defaultArchiveDownload': '归档下载',
      'settings.customGroupName': '自定义分组名',
      'settings.downloadServerRuntime': '服务端运行参数',
      'settings.galleryConcurrency': '画廊并发',
      'settings.archiveConcurrency': '归档并发',
      'settings.downloadRuntimeHint': '并发与路径由 Docker 环境变量控制，修改后需重启服务端生效。',
      'settings.performanceWebSummary': '设置 Web 下载列表动画阈值，减少大列表展开/收起时的浏览器负担。',
      'settings.webPerformance': 'Web 性能',
      'settings.performanceWebIntro': 'Web 端在浏览器中运行，这里提供会影响大列表交互流畅度的本机浏览器设置。',
      'settings.webMaxGalleryNum4Animation': '下载分组动画阈值',
      'settings.webMaxGalleryNum4AnimationHint':
          '单个下载分组内任务数超过此值时，关闭展开/收起图标动画；0 表示始终关闭。',
      'settings.resetPerformanceDefaults': '恢复默认性能设置',
      'settings.performanceSaved': '性能设置已保存',
      'settings.advancedWebSummary': '查看 Docker 路径信息，浏览、复制并清理服务器日志。',
      'settings.advancedWebIntro': '查看当前 Web 实例的服务器日志与 Docker 路径信息。',
      'settings.serverLogs': '服务器日志',
      'settings.clearLogsTitle': '清理服务器日志？',
      'settings.clearLogsConfirm': '这会删除当前所有服务器日志文件。',
      'settings.clearLogsFailed': '清理日志失败：@error',
      'settings.loadLogsFailed': '加载日志列表失败：@error',
      'settings.loadLogFailed': '加载日志失败：@error',
      'settings.noLogs': '暂无日志',
      'settings.copyLog': '复制日志',
      'settings.emptyLog': '此日志为空',
      'settings.securityWebSummary':
          '查看当前浏览器保存的 API Token 状态，校验连接有效性，或断开后重新连接。',
      'settings.webTokenSecurity': 'Web 连接安全',
      'settings.webTokenSaved': '本机 Token',
      'settings.webTokenSavedYes': '已保存在当前浏览器',
      'settings.webTokenSavedNo': '当前浏览器未保存 Token',
      'settings.webTokenFingerprint': 'Token 指纹',
      'settings.webTokenVerifyStatus': '校验状态',
      'settings.webTokenValid': '当前 Token 可用',
      'settings.webTokenInvalid': '当前 Token 无效或已轮换',
      'settings.securityWebBody':
          'Web 端使用浏览器本地保存的 API Token 连接服务端。这里不会显示完整 Token，只用于确认当前浏览器连接状态。',
      'settings.verifyCurrentToken': '校验当前 Token',
      'settings.disconnectWebToken': '断开并重新连接',
      'settings.disconnectWebTokenTitle': '断开当前 Web 连接？',
      'settings.disconnectWebTokenConfirm':
          '这会清除当前浏览器保存的 API Token，并返回设置向导。服务端 Token 不会被删除。',
      'settings.webTokenRotateHint':
          '如果你已经在服务端轮换 Token，请先断开当前连接，然后在设置向导中粘贴新的 Token。',
      'settings.mouseWheelIntro': '选择阅读器中鼠标滚轮在图片上的行为（横向翻页模式）。',
      'settings.mouseWheelReadHint': '阅读方向、预加载等全部选项',
      'settings.aboutVersionLabel': '版本',
      'settings.aboutAuthorLabel': '作者',
      'settings.aboutTelegramTitle': 'Telegram（主要为中文）',
      'settings.aboutTelegramHint': '社群链接',
      'settings.aboutQA': '问答',
      'settings.aboutWebForkNote': '本网页界面由 JHenTai Docker 分支提供；上游项目见上方链接。',

      // history
      'history.title': '浏览记录',
      'history.empty': '暂无浏览记录',
      'history.clearAll': '清空全部',
      'history.clearTitle': '清空浏览记录',
      'history.clearConfirm': '确定要清空所有浏览记录吗？',
      'history.loadFailed': '加载浏览记录失败: @error',
      'history.loadMore': '加载更多',

      // search history
      'searchHistory.clearAll': '清除搜索记录',
      'searchHistory.translate': '翻译搜索记录',

      // comment
      'comment.placeholder': '写下评论...',
      'comment.send': '发送',
      'comment.posted': '评论已发送',
      'comment.postedMsg': '你的评论已发布',
      'comment.postFailed': '发送评论失败: @error',
      'comment.voteFailed': '投票失败: @error',
      'comment.scoreDetails': '评分明细',
      'comment.update': '更新评论',
      'comment.updated': '评论已更新',
      'comment.updatedMsg': '你的评论已更新',
      'comment.updateFailed': '更新评论失败: @error',
      'comment.tooShort': '评论过短',
      'comment.atLeast3Characters': '至少 3 个字符',

      // ranklist
      'ranklist.title': '排行榜',
      'ranklist.allTime': '历史总榜',
      'ranklist.year': '年度',
      'ranklist.month': '月度',
      'ranklist.yesterday': '昨日',

      // thumbnails
      'thumbnails.title': '缩略图 (@count)',
      'thumbnails.grid': '缩略图网格',
      'thumbnails.jumpToPage': '跳转页面',
      'thumbnails.pageRange': '范围: 1 - @total',
      'thumbnails.loadFailed': '加载缩略图失败: @error',

      // home additions
      'home.history': '浏览记录',
      'home.ranklist': '排行榜',

      // tag translation
      'tagTranslation.title': '标签翻译',
      'tagTranslation.loaded': '已加载 @count 个标签',
      'tagTranslation.notLoaded': '标签数据库未加载',
      'tagTranslation.lastUpdate': '最后更新: @time',
      'tagTranslation.refresh': '更新标签数据库',
      'tagTranslation.refreshSuccess': '已更新 @count 个标签',
      'tagTranslation.refreshFailed': '更新失败: @error',

      // list mode
      'listMode.toggle': '切换显示模式',
      'listMode.grid': '网格',
      'listMode.list': '列表',
      'listMode.listCompact': '紧凑列表',

      // quick search
      'quickSearch.title': '快速搜索',
      'quickSearch.empty': '没有已保存的搜索',
      'quickSearch.saveCurrent': '保存当前搜索',
      'quickSearch.saveTitle': '保存快速搜索',
      'quickSearch.editTitle': '编辑快速搜索',
      'quickSearch.nameLabel': '名称',
      'quickSearch.addNew': '添加快速搜索',
      'quickSearch.keywordLabel': '关键词',
      'quickSearch.keywordHint': '与首页搜索栏相同',
      'quickSearch.saved': '已保存',
      'quickSearch.deleted': '已删除',
      'quickSearch.deleteTitle': '删除快速搜索',
      'quickSearch.deleteConfirm': '确定删除「@name」？',

      // tag suggest
      'tagSuggest.tag': '标签',

      // common extras
      'common.save': '保存',

      // reader enhancements
      'reader.fitWidth': '适应宽度',
      'reader.doubleColumn': '双页模式',
      'reader.autoStart': '自动阅读',
      'reader.autoStop': '停止自动阅读',

      // block rules
      'blockRule.title': '屏蔽规则',
      'blockRule.empty': '没有配置屏蔽规则',
      'blockRule.add': '添加规则',
      'blockRule.edit': '编辑规则',
      'blockRule.manage': '管理屏蔽规则',
      'useBuiltInBlockedUsers': '使用内置用户屏蔽名单',
      'useBuiltInBlockedUsersHint': '过滤掉内置名单中的用户评论',
      'blockRule.ruleCount': '@count 条规则',
      'blockRule.ungrouped': '未分组',
      'blockRule.deleteGroup': '删除分组',
      'blockRule.target': '目标',
      'blockRule.attribute': '属性',
      'blockRule.pattern': '匹配模式',
      'blockRule.expression': '表达式',
      'blockRule.expressionHint': '要匹配的值',
      'blockRule.groupId': '分组 ID',
      'blockRule.groupIdHint': '可选的分组名称',
      'blockRule.blocked': '已屏蔽',
      'blockRule.tagBlocked': '标签 "@tag" 已被屏蔽',
      'blockRule.uploaderBlocked': '上传者 "@uploader" 已被屏蔽',
      'blockRule.blockTag': '屏蔽此标签',
      'blockRule.blockUploader': '屏蔽此上传者',
      'blockRule.blockCommentUser': '屏蔽评论用户',
      'blockRule.blockCommentUserConfirm': '屏蔽评论用户 "@user"？',
      'blockRule.commentUserBlocked': '评论用户 "@user" 已被屏蔽',

      // download enhancements
      'downloads.search': '搜索下载...',
      'downloads.allGroups': '所有分组',
      'downloads.group': '分组',

      // tag voting
      'tagVote.search': '搜索',
      'tagVote.searchUploader': '搜索上传者',
      'tagVote.voteUp': '投赞成票',
      'tagVote.voteDown': '投反对票',
      'tagVote.success': '已投票',
      'tagVote.votedUp': '已为 "@tag" 投赞成票',
      'tagVote.votedDown': '已为 "@tag" 投反对票',
      'tagVote.failed': '投票失败: @error',
      'tagVote.addTag': '添加标签',
      'tagVote.addTagHint': '输入新标签，多个用逗号分隔',
      'tagVote.addSuccess': '添加标签成功',
      'tagVote.addFailed': '添加标签失败：@error',

      // responsive layout
      'home.selectGallery': '选择一个画廊查看详情',

      // gallery detail extras
      'detail.parentGallery': '父画廊',
      'detail.newerVersion': '有更新版本',
      'detail.versionHistory': '版本历史',
      'detail.currentVersion': '当前版本',
      'detail.torrents': '种子',
      'detail.torrentCount': '种子（@count）',
      'detail.noTorrents': '暂无种子',
      'detail.outdatedTorrents': '已过期',
      'detail.downloadTorrent': '下载种子',
      'detail.copyMagnet': '复制磁力链接',
      'detail.torrentSeeds': '种子 @count',
      'detail.torrentPeers': '连接 @count',
      'detail.torrentDownloads': '下载 @count',
      'detail.loadTorrentsFailed': '加载种子失败：@error',
      'detail.hhDownload': 'H@H 下载',
      'detail.noHHArchives': '暂无可用 H@H 归档',
      'detail.loadHHFailed': '加载 H@H 归档失败：@error',
      'detail.hhSubmitFailed': '提交 H@H 下载失败：@error',
      'detail.hhSubmitted': '已提交 H@H 下载请求',

      // settings extras
      'settings.cookieStatusFull': 'Cookie 正常（包含 igneous — 可访问 EX）',
      'settings.cookieStatusNoIgneous': 'Cookie 已设置但缺少 igneous — EX 可能无法使用',
      'settings.cookieStatusNone': '未设置登录 Cookie',
      'settings.siteSwitched': '已切换到 @site',

      // download progress in detail
      'detail.completed': '已完成',
      'detail.retryDownload': '重试',
      'detail.readDownloaded': '阅读已下载',
      'detail.deleteDownload': '删除下载',
      'detail.deleteDownloadConfirm': '删除此下载及其文件？',
      'detail.archiveCompleted': '归档就绪',

      // detail enhancements
      'detail.share': '分享',
      'detail.jumpToPage': '跳转到页',
      'detail.jumpToThumbnail': '跳到缩略图',
      'detail.similarSearch': '相似搜索',
      'detail.blockGallery': '屏蔽画廊',
      'detail.allComments': '全部评论',
      'detail.thumbnails': '缩略图 (@count)',
      'detail.viewAllThumbnails': '查看全部缩略图',
      'detail.galleryBlocked': '画廊已被屏蔽',
      'detail.jumpPageHint': '输入页码 (1-@max)',

      // reader enhancements
      'reader.saveImage': '保存图片',
      'reader.openInNewTab': '在新标签页打开',
      'reader.reloadImage': '重新加载',
      'reader.interval': '间隔',
      'reader.preload': '预加载',
      'reader.imageSpacing': '图片间距',
      'reader.autoInterval': '自动阅读间隔',
      'reader.startAutoMode': '开始',
      'reader.saveFailed': '保存图片失败',
      'reader.redownloadHint': '请打开「下载」页面重试或重新开始该画廊下载。',
      'reader.deviceOrientation': '设备方向',
      'reader.deviceOrientationWebHint': '网页版无法像客户端一样锁定屏幕方向。请使用浏览器全屏或系统旋转锁定。',

      // settings reader
      'settings.defaultFavoriteSlot': '默认收藏夹',
      'settings.defaultFavoriteNone': '无（每次询问）',
      'settings.defaultFavoriteHint': '启用后点击心形按钮会使用默认收藏夹，长按可重新选择。',
      'settings.usertags': '关注 / 隐藏标签',
      'settings.readerSettings': '阅读器设置',
      'settings.defaultDirection': '默认方向',
      'settings.imageSpacing': '图片间距',
      'settings.preloadPages': '预加载页数（在线）',
      'settings.preloadPagesLocal': '预加载页数（本地）',
      'settings.autoInterval': '自动阅读间隔',
      'settings.fitWidth': '适应宽度',
      'hideScroll2TopButton': '快速回顶按钮',
      'whenScrollUp': '向上滚动时',
      'whenScrollDown': '向下滚动时',
      'never': '从不',
      'always': '总是',
      'preloadGalleryCover': '预载画廊封面',
      'preloadGalleryCoverHint': '预先加载还未显示在页面上的画廊封面',
      'showDawnInfo': '展示黎明之时事件',
      'showEncounterMonster': '展示 HV 遭遇战事件',

      // home enhancements
      'home.scrollToTop': '回到顶部',
      'home.imageSearch': '以图搜图',
      'home.imageSearchFailed': '以图搜图失败: @error',
      'home.imageSearchMode': '图搜结果',

      // stats page
      'stats.title': '访问统计',
      'stats.totalVisits': '总访问量: @n',
      'stats.allTime': '全部',
      'stats.year': '年',
      'stats.month': '月',
      'stats.day': '日',
      'stats.period': '周期',
      'stats.ranking': '排名',
      'stats.score': '分数',
      'stats.visits': '访问',
      'stats.hits': '点击',
      'stats.noSeries': '暂无图表数据',

      // usertags
      'usertags.title': '关注 / 隐藏标签',
      'usertags.loadFailed': '加载失败: @error',
      'usertags.add': '添加标签',
      'usertags.tagHint': '格式 namespace:key',
      'usertags.watch': '关注',
      'usertags.hidden': '隐藏',
      'usertags.watchAdded': '已添加到关注标签',
      'usertags.hiddenAdded': '已添加到隐藏标签',
      'usertags.defaultTagSet': '默认标签集',
      'usertags.defaultTagSetNone': '无（每次询问）',
      'usertags.none': '未标记',
      'usertags.weight': '权重',
      'usertags.editTitle': '编辑标签',
      'usertags.delete': '删除',
      'usertags.added': '已添加',
      'usertags.updated': '已更新',
      'usertags.deleted': '已删除',
      'usertags.currentList': '已配置标签',
      'enableDefaultTagSet': '关注标签时使用默认标签集',
      'enableDefaultTagSetHint': '默认直接关注，长按重新选择',
      'disableDefaultTagSetHint': '手动选择',
      'chooseTagSet': '选择标签集',
      'asYourDefault': '作为默认选择',

      // downloads queue
      'downloads.sortBy': '排序',
      'downloads.sortPriority': '优先级',
      'downloads.sortTime': '时间',
      'downloads.sortTitle': '标题',
      'downloads.sortStatus': '状态',
      'downloads.allCategories': '全部分类',
      'downloads.categoryFilter': '站点分类',
      'downloads.setPriority': '优先级',
      'downloads.setGroup': '分组',
      'downloads.priorityLabel': '优先级 @n',
      'downloads.groupLabel': '分组',
      'downloads.superseded': '已升级至 gid @gid',
      'downloads.editTask': '编辑任务',
      'downloads.pauseVisible': '暂停当前列表任务',
      'downloads.resumeVisible': '恢复当前列表任务',
      'downloads.changeVisibleGroup': '修改当前列表分组',
      'downloads.changeVisibleGroupConfirm': '将当前可见的 @count 个任务移动到此分组。',
      'downloads.deleteVisible': '删除当前列表任务',
      'downloads.deleteVisibleConfirm': '请选择如何删除当前可见的 @count 个任务。',
      'downloads.noBatchTargets': '当前列表没有可操作任务',
      'downloads.batchPaused': '已暂停 @count 个任务',
      'downloads.batchResumed': '已恢复 @count 个任务',
      'downloads.batchGroupChanged': '已修改 @count 个任务的分组',
      'downloads.batchDeleted': '已删除 @count 个任务',

      // detail download dialog
      'detail.startDownloadTitle': '开始下载',
      'detail.downloadGroup': '分组',
      'existingGroup': '现有分组',
      'groupName': '分组名称',
      'detail.downloadPriority': '优先级（越大越优先）',
      'detail.stats': '统计',
      'detail.similarByTitle': '相似标题',
      'detail.upgradeDownload': '更新到新版本',
      'detail.upgradeOk': '已开始下载新版本',
      'detail.upgradeFailed': '升级失败: @error',
      'detail.archiveNewVersionHint': '存在新版本画廊，请在新版页面重新下载归档。',
      'detail.openNewVersion': '打开新版本',
    };
  }
}
