class WebKoKR {
  static Map<String, String> keys() {
    return {
      // common
      'common.cancel': '취소',
      'common.ok': '확인',
      'common.confirm': '확인',
      'common.error': '오류',
      'common.success': '성공',
      'common.failed': '실패',
      'common.retry': '재시도',
      'common.delete': '삭제',
      'common.reset': '초기화',
      'common.clear': '지우기',
      'preset': '프리셋',
      'custom': '커스텀',
      'common.refresh': '새로고침',
      'common.loading': '로딩 중...',
      'common.unknown': '알 수 없음',
      'common.images': '@count장',
      'common.pages': '@count 페이지',
      'common.open': '열기',
      'common.close': '닫기',
      'localizedReason': '계속하려면 인증하세요',
      'passwordErrorHint': '비밀번호가 틀렸습니다. 다시 시도하세요',
      'dawnOfaNewDay': '새로운 하루가 밝았습니다!',
      'encounterMonster': '몬스터를 만났습니다!',
      'encounterMonsterHint': 'HentaiVerse 전투로 이동하려면 클릭하세요.',

      'share': '공유',
      'save': '저장',
      'reload': '다시 로드',
      'cancel': '취소',
      'resampleImage': '리샘플',
      'originalImage': '원본',
      'downloadOriginalImage': '원본 이미지 다운로드',
      'downloadOriginalImageByDefault': '기본값으로 원본 이미지 선택',
      'downloadAllGallerysOfSamePriority': '같은 우선순위의 모든 갤러리 다운로드',
      'downloadAllGallerysOfSamePriorityHint':
          '기본적으로 각 우선순위마다 갤러리 하나만 동시에 다운로드합니다.',
      'useJH2UpdateGallery': 'JH 서버로 갤러리 업데이트 가속',
      'restoreDownloadTasks': '다운로드 작업 복원',
      'restoreDownloadTasksHint': '메타데이터로 다운로드 작업 복원',
      'restoreTasksAutomatically': '작업 자동 복원',
      'restoreTasksAutomaticallyHint': '서버 시작 시 다운로드 메타데이터에서 작업을 복원합니다',
      'home.pasteAndSearch': '붙여넣고 검색 또는 열기',
      'home.clipboardEmpty': '클립보드가 비어 있습니다',
      'home.clipboardReadFailed': '클립보드를 읽을 수 없습니다. 권한을 허용한 뒤 다시 시도하세요.',
      'galleryUrlDetected': '클립보드에서 갤러리 URL을 찾았습니다',
      'galleryUrlDetectedHint': '감지된 링크 열기',
      'restoredGalleryCount': '복원된 갤러리',
      'restoredArchiveCount': '복원된 아카이브',
      'reDownload': '다시 다운로드',
      'deleteTask': '리스트에서만 삭제',
      'deleteTaskAndImages': '리스트와 파일 모두 삭제',
      'hasCopiedToClipboard': '클립보드에 복사했습니다',
      'autoModeStyle': '자동 모드 스타일',
      'scroll': '스크롤',
      'turnPage': '페이지 넘김',
      'turnPageMode': '페이지 넘기기 모드',
      'turnPageModeHint': '화면 기준 혹은 이미지 기준',
      'image': '이미지 기준',
      'screen': '화면 기준',
      'adaptive': '적응형',
      'displayFirstPageAlone': '첫 페이지만 표시',
      'showThumbnails': '썸네일 표시',
      'showScrollBar': '스크롤바 표시',
      'showStatusInfo': '하단 상태 표시',
      'keepScreenAwakeWhenReading': '읽는 중에 화면 꺼짐 방지하기',
      'gestureRegionWidthRatio': '메뉴 제스처 영역 너비 비율',
      'imageRegionWidthRatio': '이미지 영역 너비 비율',
      'spaceBetweenImages': '이미지 간격',
      'defaultTab': '기본 탭',
      'enablePasswordAuth': '비밀번호 인증 사용',
      'enableAuthOnResume': '다시 돌아올 때 인증',
      'enableAuthOnResumeHints': '백그라운드 3초 후 다시 잠급니다',
      'setPasswordHint': '비밀번호를 입력하세요',
      'confirmPasswordHint': '비밀번호를 다시 입력하세요',
      'passwordNotMatchHint': '비밀번호가 일치하지 않습니다. 다시 시도하세요',

      // setup
      'setup.title': 'JHenTai 서버 설정',
      'setup.description': '서버 로그에 표시된 API 토큰을 입력하여 연결하세요.',
      'setup.tokenLabel': 'API 토큰',
      'setup.connect': '연결',
      'setup.emptyToken': '토큰을 입력하세요',
      'setup.invalidToken': '유효하지 않은 토큰입니다. 서버 로그에서 올바른 토큰을 확인하세요.',
      'setup.tokenHint': '토큰은 한 줄에 64자리 16진수입니다. 로그에서 전체를 복사하세요(절반만 복사하지 마세요).',
      'setup.tokenPasteHint': '로그의 전체 64자 토큰을 붙여넣으세요',
      'setup.tokenCharCount': '@current / @total자',
      'setup.tokenWrongLength': '토큰은 정확히 64자리 16진수여야 합니다(docker logs 한 줄 전체).',
      'setup.tokenHelpTitle': '로그에서 토큰 찾는 방법',
      'setup.tokenHelpP1': 'Docker가 실행 중인 호스트에서 터미널을 열고 다음을 실행하세요.',
      'setup.tokenHelpP2':
          '[JHenTai] API token for web UI 로 시작하는 줄을 찾아 콜론 뒤의 64자리 16진수를 복사하세요(한 줄 전체). 컨테이너 이름이 jhentai가 아니면 아래 명령의 이름을 바꾸세요.',
      'setup.tokenHelpAlt':
          '해당 줄이 없으면 서버 DB에서 읽을 수 있습니다(기본 컨테이너 이름 jhentai, 데이터 디렉터리 /data):',

      // home
      'home.title': 'JHenTai',
      'home.search': '갤러리 검색...',
      'home.advancedSearch': '고급 검색',
      'home.searchFilterSheetTitle': '카테고리 및 필터',
      'home.leftPaneWidthPx': '@w px',
      'home.twoPaneDividerTooltip': '왼쪽 패널 @w px · 구분선을 두 번 탭하면 기본 너비로 복원',
      'home.downloads': '다운로드',
      'home.localGalleries': '로컬 갤러리',
      'home.settings': '설정',
      'home.subtitle': 'E-Hentai 클라이언트',
      'home.home': '홈',
      'home.popular': '인기',
      'home.favorites': '즐겨찾기',
      'home.watched': '구독',
      'home.noGalleries': '갤러리를 찾을 수 없습니다',
      'home.previous': '이전',
      'home.next': '다음',
      'home.jumpDate': '날짜로 이동',
      'home.page': '@page 페이지',
      'home.loadFailed': '로드 실패: @error',
      'home.favSortTitle': '즐겨찾기 정렬',
      'home.favSortFavorited': '즐겨찾기한 시간순',
      'home.favSortPublished': '게시 시간순',
      'home.favAllFolders': '전체',
      'home.favSlotShort': '폴더 @n',
      // advanced search
      'home.categoryFilter': '카테고리 필터',
      'home.minimumRating': '최소 평점',
      'home.ratingAny': '전체',
      'home.searchIn': '검색 범위',
      'home.galleryName': '갤러리 이름',
      'home.tags': '태그',
      'home.description': '설명',
      'home.showExpunged': '삭제된 항목 표시',
      'home.onlyShowGalleriesWithTorrents': '토렌트가 있는 갤러리만 보기',
      'home.pageRange': '페이지 범위',
      'home.pageAtLeast': '최소 페이지',
      'home.pageAtMost': '최대 페이지',
      'home.language': '언어',
      'home.languageNone': '없음',
      'home.disableFilterForLanguage': '언어 필터 사용 안 함',
      'home.disableFilterForUploader': '업로더 필터 사용 안 함',
      'home.disableFilterForTags': '태그 필터 사용 안 함',
      'home.applySearch': '적용 및 검색',
      // category names
      'category.doujinshi': '동인지',
      'category.manga': '만화',
      'category.artistCg': '아티스트 CG',
      'category.gameCg': '게임 CG',
      'category.western': '서양',
      'category.nonH': '비-H',
      'category.imageSet': '이미지 세트',
      'category.cosplay': '코스프레',
      'category.asianPorn': '아시안',
      'category.misc': '기타',

      // gallery detail
      'detail.copyUrl': '갤러리 URL 복사',
      'detail.copied': '복사됨',
      'detail.switchToSite': '@site로 전환',
      'detail.removeFromFav': '즐겨찾기에서 제거',
      'detail.addToFav': '즐겨찾기에 추가',
      'detail.addToFavTitle': '즐겨찾기에 추가',
      'detail.favRemoved': '제거됨',
      'detail.favRemovedMsg': '즐겨찾기에서 제거되었습니다',
      'detail.favAdded': '추가됨',
      'detail.favAddedMsg': '@name에 추가되었습니다',
      'detail.favError': '즐겨찾기 작업 실패: @error',
      'detail.favSlot': '즐겨찾기 @n',
      'detail.favNoteHint': '메모 (선택)',
      'detail.favQuickAddTooltip': '기본 폴더에 추가 (길게 누르기)',
      'detail.rateTitle': '갤러리 평가',
      'detail.rateSubmit': '제출',
      'detail.rated': '평가됨',
      'detail.ratedMsg': '당신의 평점: @rating',
      'detail.rateFailed': '평가 실패: @error',
      'detail.rateLoginRequired': '평가할 수 없음 — 로그인 필요',
      'detail.ratingCount': '@count개 평가',
      'detail.favoriteCount': '@count회 즐겨찾기',
      'detail.readOnline': '온라인 보기',
      'detail.readOnlineResume': '온라인 보기 (이전 @page페이지부터)',
      'detail.downloadGallery': '갤러리 다운로드',
      'detail.archiveResample': '아카이브 (리샘플)',
      'detail.archiveOriginal': '아카이브 (원본)',
      'detail.downloadArchive': '아카이브 다운로드',
      'detail.downloadStarted': '다운로드 시작',
      'detail.galleryQueued': '갤러리 다운로드가 대기열에 추가되었습니다',
      'detail.archiveQueued': '아카이브 다운로드가 대기열에 추가되었습니다',
      'detail.downloadFailed': '다운로드 시작 실패: @error',
      'detail.archiveFailed': '아카이브 다운로드 시작 실패: @error',
      'detail.loadArchiveInfoFailed': '아카이브 정보 로드 실패: @error',
      'detail.noArchive': '사용 가능한 아카이브 없음',
      'detail.tags': '태그',
      'detail.comments': '댓글 (@count)',
      'detail.anonymous': '익명',
      'detail.loadFailed': '갤러리 세부 정보 로드 실패: @error',
      'detail.metadataOnly': '전체 상세 페이지를 사용할 수 없어 EH API 메타데이터를 표시합니다.',

      // reader
      'reader.loading': '갤러리 로드 중...',
      'reader.loadingGalleryMeta': '페이지 목록 로드 중...',
      'reader.resolvingFirstPages': '이미지 페이지 분석 중...',
      'reader.resolvingImagePage': '페이지 분석 중...',
      'reader.loadingImage': '이미지 로드 중...',
      'reader.loadFailed': '갤러리 로드 실패: @error',
      'reader.imageFailed': '이미지 로드 실패',
      'reader.noImages': '이미지가 없습니다',
      'reader.directionLabel': '보기 방향: @dir',
      'reader.ltr': '왼쪽→오른쪽',
      'reader.rtl': '오른쪽→왼쪽',
      'reader.vertical': '세로 스크롤',
      'reader.shortcuts': '단축키',
      'reader.shortcutRightKeys': '→ / ↓ / D',
      'reader.shortcutLeftKeys': '← / ↑ / A',
      'reader.shortcutNext': '다음 페이지',
      'reader.shortcutPrev': '이전 페이지',
      'reader.shortcutToggleMenu': '메뉴 표시/숨기기',
      'reader.shortcutBack': '뒤로',
      'reader.wheelAction': '이미지 위 마우스 휠',
      'reader.wheelActionPage': '페이지 넘기기',
      'reader.wheelActionZoom': '이미지 확대/축소',
      'reader.wheelActionVerticalHint':
          '세로 및 너비 맞춤 모드에서는 항상 목록이 스크롤됩니다. 이 옵션은 좌→우, 우→좌, 두 페이지 모드에만 적용됩니다.',
      'reader.wheelInvertPageTurn': '휠 페이지 넘김 방향 반전',
      'reader.wheelInvertPageTurnSubtitle':
          '휠/트랙패드 스크롤 시 다음 페이지와 이전 페이지에 대응하는 방향을 바꿉니다.',
      'reader.wheelScrollSpeed': '휠 스크롤 속도',
      'reader.wheelScrollSpeedSubtitle':
          '세로 및 너비 맞춤 뷰어 모드에서 마우스 휠 스크롤 속도를 조절합니다.',
      'wheelScrollSpeed': '휠 스크롤 속도',

      // downloads
      'downloads.title': '다운로드',
      'downloads.gallery': '갤러리',
      'downloads.archive': '아카이브',
      'downloads.noGallery': '갤러리 다운로드 없음',
      'downloads.noArchive': '아카이브 다운로드 없음',
      'downloads.read': '보기',
      'downloads.pause': '일시정지',
      'downloads.resume': '재개',
      'downloads.deleteTitle': '다운로드 삭제',
      'downloads.deleteConfirm': '다운로드한 파일을 보존할지 선택하세요.',
      'downloads.loadFailed': '작업 로드 실패: @error',
      // gallery statuses
      'downloads.gStatus0': '없음',
      'downloads.gStatus1': '다운로드 중',
      'downloads.gStatus2': '일시정지',
      'downloads.gStatus3': '완료',
      'downloads.gStatus4': '실패',
      // archive statuses
      'downloads.aStatus0': '없음',
      'downloads.aStatus1': '잠금 해제 중',
      'downloads.aStatus2': 'URL 분석 중',
      'downloads.aStatus3': '다운로드 중',
      'downloads.aStatus4': '다운로드됨',
      'downloads.aStatus5': '압축 해제 중',
      'downloads.aStatus6': '완료',
      'downloads.aStatus7': '일시정지',
      'downloads.aStatus8': '실패',

      // local
      'local.title': '로컬 갤러리',
      'local.noGalleries': '로컬 갤러리를 찾을 수 없습니다',
      'local.helpText':
          'Docker 컨테이너에 디렉토리를 마운트하거나\nlocal_gallery 폴더에 갤러리를 넣으세요',
      'local.scanNow': '지금 스캔',
      'local.empty': '비어 있음',
      'local.noImages': '이 갤러리에 이미지가 없습니다',
      'local.loadFailed': '갤러리 이미지 로드 실패: @error',
      'local.loadListFailed': '로컬 갤러리 로드 실패: @error',
      'local.deleteTitle': '로컬 갤러리 삭제',
      'local.deleteConfirm': '"@title"의 로컬 파일을 삭제할까요?',
      'local.deleteSuccess': '로컬 갤러리가 삭제되었습니다',
      'local.deleteFailed': '로컬 갤러리 삭제 실패: @error',
      'local.parentDirectory': '상위 폴더',
      'local.copyPath': '경로 복사',
      'local.copyAllPaths': '모든 경로 복사',
      'local.scanRoots': '스캔 루트',
      'local.scanRootsHint':
          'Docker 서버가 스캔하는 컨테이너 내부 경로입니다. 변경하려면 Docker 볼륨 마운트 또는 JH_EXTRA_SCAN_PATHS를 수정하세요.',
      'local.noScanRoots': '설정된 스캔 루트가 없습니다',

      // settings
      'settings.title': '설정',
      'settings.account': '계정',
      'settings.loggedIn': '로그인됨: @user',
      'settings.logout': '로그아웃',
      'settings.logoutSuccess': '로그아웃되었습니다',
      'settings.logoutFailed': '로그아웃 실패: @error',
      'settings.cookieLogin': '쿠키로 로그인 (권장)',
      'settings.cookieHint': 'EH 포럼 로그인은 서버 환경에서 Cloudflare에 의해 차단됩니다. '
          '브라우저에서 로그인한 후 쿠키를 여기에 복사하세요.\n'
          '단계: e-hentai.org 로그인 → F12 → 애플리케이션 → 쿠키 → 아래 값 복사.',
      'settings.cookiePlaceholder':
          'ipb_member_id=xxx; ipb_pass_hash=xxx; igneous=xxx',
      'settings.setCookies': '쿠키 설정',
      'settings.cookieSuccess': '쿠키가 설정되었습니다',
      'settings.cookieFailed': '쿠키 설정 실패: @error',
      'settings.cookieEmpty': '쿠키를 붙여넣으세요',
      'settings.showCookies': '쿠키 보기',
      'settings.copyCookies': '쿠키 복사',
      'settings.copyKeyCookies': '로그인 쿠키 복사',
      'settings.refreshIgneous': 'igneous 새로고침',
      'settings.refreshIgneousSuccess': 'igneous가 새로고침되었습니다',
      'settings.refreshIgneousFailed': 'igneous 새로고침 실패',
      'settings.refreshIgneousFailedWithError': 'igneous 새로고침 실패: @error',
      'settings.credentialLogin': '자격 증명으로 로그인 (Cloudflare로 인해 실패할 수 있음)',
      'settings.username': '사용자 이름',
      'settings.password': '비밀번호',
      'settings.login': '로그인',
      'settings.loginSuccess': '로그인 성공',
      'settings.loginFailed': '로그인 실패',
      'settings.loginError': '로그인 실패: @error',
      'settings.emptyCredentials': '사용자 이름과 비밀번호를 입력하세요',
      'settings.site': '사이트',
      'redirect2Eh': '가능하면 EH로 리디렉션',
      'redirect2EhHint': '더 나은 네트워크 성능을 위해 갤러리 상세를 EH에서 먼저 불러옵니다.',
      'settings.appearance': '외관',
      'settings.themeMode': '테마 모드',
      'settings.system': '시스템',
      'settings.light': '라이트',
      'settings.dark': '다크',
      'settings.accentColor': '강조 색상',
      'settings.serverInfo': '서버 정보',
      'settings.dataDir': '데이터 디렉토리',
      'settings.downloadDir': '다운로드 디렉토리',
      'settings.localGalleryDir': '로컬 갤러리 디렉토리',
      'settings.extraScanPaths': '추가 스캔 경로',
      'settings.switchSiteFailed': '사이트 전환 실패: @error',
      'settings.language': '언어',
      'settings.sectionData': '데이터 및 도구',
      'settings.sectionStyle': '스타일',
      'settings.sectionRead': '뷰어',
      'settings.sectionTags': '태그 및 필터',
      'settings.sectionOther': '기타',
      'settings.openDownloads': '다운로드',
      'settings.openHistory': '방문 기록',
      'settings.openLocal': '로컬 갤러리',
      'settings.openQuickSearch': '빠른 검색',
      'settings.networkNote': '네트워크 및 프록시',
      'settings.networkWebBody':
          '프록시와 네트워크 설정은 서버 또는 Docker 환경에서 구성합니다. 이 페이지는 EH/EX 및 H@H 이미지 요청의 현재 프록시 상태를 보여줍니다.',
      'settings.about': '정보',
      'settings.appVersion': '버전 @version (@build)',
      'settings.hubMenu': '설정 메뉴',
      'settings.menuWebDocker': '웹 UI 및 서버',
      'settings.menuWebDockerSubtitle':
          '다운로드 바로가기, Docker 경로, 네트워크·프록시 안내, 성능·보안(Web 전용).',
      'settings.menuEH': 'E-Hentai',
      'settings.menuStyle': '스타일',
      'settings.menuRead': '읽기',
      'settings.menuPreference': '환경설정',
      'settings.menuNetwork': '네트워크',
      'settings.menuDownload': '다운로드',
      'settings.menuPerformance': '성능',
      'settings.menuMouseWheel': '마우스 휠',
      'settings.menuAdvanced': '고급',
      'settings.menuSecurity': '보안',
      'settings.ehRequiresLogin': '계정에서 로그인한 뒤 사이트와 쿠키 상태를 변경하세요.',
      'settings.ehMyTags': '내 태그',
      'settings.ehMyTagsHint': '온라인 관심 및 숨김 태그 관리',
      'settings.ehSiteSetting': '사이트 설정',
      'settings.ehSiteSettingHint': 'E-Hentai / ExHentai 설정 페이지를 새 탭에서 엽니다',
      'settings.ehProfile': '프로필 설정',
      'settings.ehSelectedProfile': '선택한 프로필',
      'settings.ehProfileHint':
          '현재 사이트: @site. 앱과 동일하게 sp 쿠키로 활성 사이트 프로필을 전환합니다.',
      'settings.ehProfileEmpty': '프로필을 찾을 수 없습니다',
      'settings.ehProfileSaved': '프로필을 전환했습니다',
      'settings.ehProfileSaveFailed': '프로필 전환 실패: @error',
      'settings.ehProfileLoadFailed': '프로필 로드 실패: @error',
      'settings.ehProfileAndQuota': '프로필, 할당량 및 자산',
      'settings.ehProfileAndQuotaHint':
          '이 값들은 아직 사이트 페이지 파싱에 의존합니다. 지금은 사이트 설정 페이지에서 확인하세요.',
      'settings.ehAssets': '자산',
      'settings.ehImageQuota': '이미지 할당량',
      'settings.ehResetCost': '초기화 비용',
      'settings.ehQuotaUnavailable': '이미지 할당량은 기부자만 볼 수 있습니다',
      'settings.ehQuotaReset': '이미지 할당량이 초기화되었습니다',
      'settings.ehQuotaResetFailed': '이미지 할당량 초기화 실패: @error',
      'settings.ehStatusFailed': 'EH 상태 로드 실패: @error',
      'settings.galleryListStyle': '갤러리 목록 스타일',
      'pageListStyle': '갤러리 목록 스타일(페이지)',
      'global': '전역',
      'settings.listModeGrid': '그리드',
      'settings.listModeList': '목록',
      'settings.listModeCompact': '간단히',
      'settings.gridColumns': '그리드 열 수',
      'settings.gridColumnsAuto': '자동',
      'settings.downloadGridColumns': '다운로드 그리드 열 수',
      'settings.downloadGridColumnsHint': '이 브라우저의 다운로드 작업 그리드에 적용됩니다.',
      'settings.localGridColumns': '로컬 갤러리 그리드 열 수',
      'settings.localGridColumnsHint': '이 브라우저의 로컬 갤러리 폴더와 갤러리 그리드에 적용됩니다.',
      'settings.detailThumbnailColumns': '상세 썸네일 열 수',
      'settings.detailThumbnailColumnsHint': '갤러리 상세 썸네일과 전체 썸네일 페이지에 적용됩니다.',
      'moveCover2RightSide': '섬네일을 오른쪽으로 배치',
      'settings.moveCoverWebHint': '이 브라우저의 넓은 갤러리 상세 페이지에 적용됩니다.',
      'settings.galleryListStyleHint': '웹 홈 갤러리 목록에 즉시 적용되며 이 브라우저에 저장됩니다.',
      'settings.pageListStyleHint':
          '각 Web 섹션의 갤러리 목록 스타일을 개별로 덮어씁니다. 전역은 위 스타일을 사용합니다.',
      'settings.networkWebSummary':
          '프록시 상태는 네트워크 페이지에서 확인하세요. Docker 환경 변수를 변경한 뒤 서버를 재시작하세요.',
      'settings.proxyRouting': '요청 라우팅',
      'settings.ehProxyRoute': 'EH/EX 페이지 요청',
      'settings.hathProxyRoute': 'H@H 이미지 요청',
      'settings.hathProxyDedicatedHint':
          'JH_HATH_PROXY가 설정되어 *.hath.network가 이 프록시를 우선 사용합니다.',
      'settings.hathProxyFallbackHint':
          'JH_HATH_PROXY가 설정되지 않아 *.hath.network는 HTTPS_PROXY/HTTP_PROXY를 사용합니다. H@H가 계속 실패하면 JH_HATH_PROXY를 별도로 설정하세요.',
      'settings.proxyEnvironment': '프록시 환경',
      'settings.proxyEnvironmentEmpty': '보고된 프록시 환경 값이 없습니다.',
      'settings.proxyEnvironmentHint': '여기에는 프로토콜, 호스트, 포트만 표시되며 인증 정보는 숨깁니다.',
      'settings.proxyAuthConfigured': '인증 설정됨',
      'settings.copyNetworkDiagnostics': '네트워크 진단 복사',
      'settings.networkRuntimeFlags': '네트워크 진단',
      'settings.networkRestartHint':
          '이 값들은 서버 시작 환경에서 가져옵니다. 변경 후 컨테이너를 재시작하세요.',
      'settings.directConnection': '직접 연결',
      'settings.configured': '설정됨',
      'settings.notConfigured': '설정 안 됨',
      'settings.enabled': '활성화됨',
      'settings.disabled': '비활성화됨',
      'settings.downloadWebSummary':
          '다운로드 기본 그룹과 우선순위를 설정하고 Docker 다운로드 경로와 동시 다운로드 수를 확인하며 작업을 관리합니다.',
      'settings.downloadWebIntro':
          '웹 다운로드 대화상자에서 사용할 기본 그룹과 우선순위를 설정하고 서버 Docker 다운로드 값을 확인합니다.',
      'settings.downloadDefaults': '다운로드 기본값',
      'settings.downloadDefaultsSaved': '다운로드 기본값이 저장되었습니다',
      'settings.defaultGalleryDownload': '갤러리 다운로드',
      'settings.defaultArchiveDownload': '아카이브 다운로드',
      'settings.customGroupName': '사용자 지정 그룹 이름',
      'settings.downloadServerRuntime': '서버 런타임',
      'settings.galleryConcurrency': '갤러리 동시 다운로드',
      'settings.archiveConcurrency': '아카이브 동시 다운로드',
      'settings.jhPublicApiBaseUrl': 'JH 공개 API',
      'settings.jhAppId': 'JH 앱 ID',
      'settings.jhApiSecretConfigured': 'JH API 시크릿',
      'settings.downloadRuntimeHint':
          '동시 다운로드 수와 경로는 Docker 환경 변수로 제어되며 서버 재시작 후 적용됩니다.',
      'settings.performanceWebSummary':
          '큰 그룹에서 브라우저 부담을 줄이도록 웹 다운로드 목록 애니메이션 제한을 설정합니다.',
      'settings.webPerformance': '웹 성능',
      'settings.performanceWebIntro':
          '웹 클라이언트는 브라우저에서 실행됩니다. 이 로컬 브라우저 설정은 큰 목록의 상호작용 부드러움에 영향을 줍니다.',
      'settings.webMaxGalleryNum4Animation': '다운로드 그룹 애니메이션 제한',
      'settings.webMaxGalleryNum4AnimationHint':
          '다운로드 그룹의 작업 수가 이 값을 넘으면 펼침/접힘 아이콘 애니메이션을 끕니다. 0은 항상 끕니다.',
      'settings.resetPerformanceDefaults': '성능 기본값 복원',
      'settings.performanceSaved': '성능 설정이 저장되었습니다',
      'settings.advancedWebSummary': '이미지 없음 모드를 켜고 Docker 경로와 서버 로그를 관리합니다.',
      'settings.advancedWebIntro':
          '이 웹 인스턴스의 이미지 로드, 서버 로그, Docker 경로 정보를 관리합니다.',
      'settings.exportData': '데이터 내보내기',
      'settings.exportDataHint':
          '설정, 차단 규칙, 열람 기록, 검색 기록, 빠른 검색을 JSON으로 다운로드합니다. 토큰과 쿠키는 제외됩니다.',
      'settings.exportDataSuccess': '데이터 내보내기를 다운로드했습니다',
      'settings.exportDataFailed': '데이터 내보내기 실패: @error',
      'settings.importData': '데이터 가져오기',
      'settings.importDataHint':
          '웹 내보내기 또는 앱 JHenTaiConfig JSON을 가져와 이 서버에 병합합니다. 설정과 이름 있는 항목은 덮어쓰고 차단 규칙은 중복 제거됩니다.',
      'settings.importDataTitle': '데이터를 가져올까요?',
      'settings.importDataConfirm':
          'JHenTai Web 내보내기 또는 앱 JHenTaiConfig 파일을 선택하세요. 가져온 설정이 현재 값을 덮어쓸 수 있습니다.',
      'settings.importDataSuccess': '@count개 항목을 가져왔습니다',
      'settings.importDataFailed': '데이터 가져오기 실패: @error',
      'settings.noImageMode': '이미지 없음 모드',
      'settings.noImageModeHint': '이 브라우저에서 갤러리 표지, 썸네일, 리더 이미지를 숨깁니다.',
      'checkClipboard': '클립보드의 갤러리 URL 확인',
      'settings.checkClipboardHint':
          '홈 화면을 열 때 브라우저 클립보드의 갤러리 링크를 감지하고 열지 묻습니다.',
      'settings.pageCache': '페이지 캐시',
      'settings.clearPageCache': '페이지 캐시 지우기',
      'settings.clearPageCacheTitle': '페이지 캐시를 지울까요?',
      'settings.clearPageCacheConfirm': '서버에 캐시된 EH 페이지 응답이 삭제됩니다.',
      'settings.clearPageCacheFailed': '페이지 캐시 삭제 실패: @error',
      'settings.loadPageCacheFailed': '페이지 캐시 로드 실패: @error',
      'settings.pageCacheSummary': '캐시된 페이지 @count개 · @size',
      'settings.serverLogs': '서버 로그',
      'settings.clearLogsTitle': '서버 로그를 지울까요?',
      'settings.clearLogsConfirm': '현재 서버 로그 파일이 모두 삭제됩니다.',
      'settings.clearLogsFailed': '로그 삭제 실패: @error',
      'settings.loadLogsFailed': '로그 목록 로드 실패: @error',
      'settings.loadLogFailed': '로그 로드 실패: @error',
      'settings.noLogs': '로그 없음',
      'settings.copyLog': '로그 복사',
      'settings.downloadLog': '로그 다운로드',
      'settings.emptyLog': '이 로그는 비어 있습니다',
      'settings.securityWebSummary':
          '이 브라우저에 저장된 API 토큰 상태를 확인하고 연결을 검증하거나 연결 해제 후 다시 연결합니다.',
      'settings.webTokenSecurity': '웹 연결 보안',
      'settings.webTokenSaved': '로컬 토큰',
      'settings.webTokenSavedYes': '이 브라우저에 저장됨',
      'settings.webTokenSavedNo': '이 브라우저에 저장된 토큰 없음',
      'settings.webTokenFingerprint': '토큰 지문',
      'settings.webTokenVerifyStatus': '검증 상태',
      'settings.webTokenValid': '현재 토큰은 유효합니다',
      'settings.webTokenInvalid': '현재 토큰이 유효하지 않거나 교체되었습니다',
      'settings.securityWebBody':
          '웹 UI는 이 브라우저에 저장된 API 토큰으로 서버에 연결합니다. 전체 토큰은 표시하지 않으며 현재 브라우저 연결만 확인합니다.',
      'settings.verifyCurrentToken': '현재 토큰 검증',
      'settings.disconnectWebToken': '연결 해제 후 다시 연결',
      'settings.disconnectWebTokenTitle': '현재 웹 연결을 해제할까요?',
      'settings.disconnectWebTokenConfirm':
          '이 브라우저에 저장된 API 토큰을 지우고 설정으로 돌아갑니다. 서버 토큰은 삭제되지 않습니다.',
      'settings.webTokenRotateHint':
          '서버에서 토큰을 교체했다면 먼저 여기서 연결을 해제한 뒤 설정에서 새 토큰을 붙여넣으세요.',
      'settings.webPasswordAuthHint':
          '이 브라우저에 저장되는 로컬 4자리 PIN으로 Web 세션을 보호합니다.',
      'settings.lockNow': '지금 잠그기',
      'settings.disablePasswordAuthTitle': '비밀번호 인증을 끌까요?',
      'settings.disablePasswordAuthConfirm': '이 브라우저에 저장된 로컬 PIN을 삭제합니다.',
      'settings.passwordAuthEnabled': '비밀번호 인증이 켜졌습니다',
      'settings.mouseWheelIntro': '뷰어에서 이미지 위 마우스 휠 동작을 선택합니다(가로 페이지 모드).',
      'settings.webWheelScrollSpeedHint': 'Web 갤러리 목록의 마우스 휠 스크롤 속도를 조절합니다.',
      'settings.mouseWheelReadHint': '방향, 프리로드 등 모든 읽기 옵션',
      'settings.aboutVersionLabel': '버전',
      'settings.aboutAuthorLabel': '제작자',
      'settings.aboutTelegramTitle': 'Telegram(주로 중국어)',
      'settings.aboutTelegramHint': '커뮤니티 링크',
      'settings.aboutQA': 'Q&A',
      'settings.aboutWebForkNote':
          '이 웹 UI는 JHenTai Docker 포크에서 제공됩니다. 상위 프로젝트는 위 링크를 참고하세요.',

      // history
      'history.title': '방문 기록',
      'history.empty': '방문 기록 없음',
      'history.clearAll': '전체 삭제',
      'history.clearTitle': '방문 기록 삭제',
      'history.clearConfirm': '모든 방문 기록을 삭제하시겠습니까?',
      'history.loadFailed': '방문 기록 로드 실패: @error',
      'history.loadMore': '더 불러오기',
      'history.search': '방문 기록 검색...',
      'history.jumpToPage': '방문 기록 페이지 이동',
      'history.pageRange': '범위: 1 - @total, 현재: @current',

      // search history
      'searchHistory.clearAll': '검색 기록 삭제',
      'searchHistory.translate': '검색 기록 번역',

      // comment
      'comment.placeholder': '댓글 작성...',
      'comment.send': '전송',
      'comment.posted': '댓글 게시됨',
      'comment.postedMsg': '댓글이 게시되었습니다',
      'comment.postFailed': '댓글 게시 실패: @error',
      'comment.voteFailed': '투표 실패: @error',
      'comment.scoreDetails': '점수 상세',
      'lastEditedOn': '최근 수정일',
      'comment.update': '댓글 수정',
      'comment.updated': '댓글이 수정되었습니다',
      'comment.updatedMsg': '댓글이 업데이트되었습니다',
      'comment.updateFailed': '댓글 수정 실패: @error',
      'comment.tooShort': '댓글이 너무 짧습니다',
      'comment.atLeast3Characters': '최소 3자',

      // ranklist
      'ranklist.title': '랭킹',
      'ranklist.allTime': '역대',
      'ranklist.year': '연간',
      'ranklist.month': '월간',
      'ranklist.yesterday': '어제',

      // thumbnails
      'thumbnails.title': '썸네일 (@count)',
      'thumbnails.grid': '썸네일 그리드',
      'thumbnails.jumpToPage': '페이지로 이동',
      'thumbnails.pageRange': '범위: 1 - @total',
      'thumbnails.loadFailed': '썸네일 로드 실패: @error',

      // home additions
      'home.history': '방문 기록',
      'home.ranklist': '랭킹',

      // tag translation
      'tagInfo.title': '태그 상세',
      'tagInfo.empty': '태그 상세 정보가 없습니다',
      'tagInfo.loadFailed': '태그 상세 정보를 불러오지 못했습니다: @error',
      'showR18GImageDirectly': 'R18G 이미지 표시',
      'warningImageHint': 'R18G 이미지, 클릭하여 보기',
      'tagTranslation.title': '태그 번역',
      'tagTranslation.loaded': '@count개 태그 로드됨',
      'tagTranslation.notLoaded': '태그 데이터베이스가 로드되지 않음',
      'tagTranslation.lastUpdate': '마지막 업데이트: @time',
      'tagTranslation.refresh': '태그 데이터베이스 새로고침',
      'tagTranslation.refreshSuccess': '@count개 태그 업데이트됨',
      'tagTranslation.refreshFailed': '새로고침 실패: @error',

      // list mode
      'listMode.toggle': '보기 모드 전환',
      'listMode.grid': '그리드',
      'listMode.list': '목록',
      'listMode.listCompact': '간략 목록',

      // quick search
      'quickSearch.title': '빠른 검색',
      'quickSearch.empty': '저장된 검색 없음',
      'quickSearch.saveCurrent': '현재 검색 저장',
      'quickSearch.saveTitle': '빠른 검색 저장',
      'quickSearch.editTitle': '빠른 검색 편집',
      'quickSearch.nameLabel': '이름',
      'quickSearch.addNew': '빠른 검색 추가',
      'quickSearch.keywordLabel': '키워드',
      'quickSearch.keywordHint': '홈 검색창과 동일',
      'quickSearch.saved': '저장됨',
      'quickSearch.deleted': '삭제됨',
      'quickSearch.deleteTitle': '빠른 검색 삭제',
      'quickSearch.deleteConfirm': '"@name"을(를) 삭제할까요?',

      // tag suggest
      'tagSuggest.tag': '태그',

      // common extras
      'common.save': '저장',

      // reader enhancements
      'reader.fitWidth': '너비 맞춤',
      'reader.doubleColumn': '두 페이지 보기',
      'reader.autoStart': '자동 넘기기',
      'reader.autoStop': '자동 넘기기 중지',

      'enableBottomMenu': '하단 메뉴 사용',

      'enablePageTurnAnime': '페이지 넘김 애니메이션 사용',
      'enableDoubleTapToScaleUp': '두 번 탭해 확대 사용',
      'enableTapDragToScaleUp': '탭 후 드래그로 확대 사용',
      'reverseTurnPageDirection': '탭 페이지 넘김 방향 반전',
      'disablePageTurningOnTap': '탭으로 페이지 넘김 끄기',
      // block rules
      'blockRule.title': '차단 규칙',
      'blockRule.empty': '차단 규칙이 없습니다',
      'blockRule.add': '규칙 추가',
      'blockRule.edit': '규칙 편집',
      'blockRule.manage': '차단 규칙 관리',
      'useBuiltInBlockedUsers': '내장 사용자 차단 목록 사용',
      'useBuiltInBlockedUsersHint': '내장 차단 목록에 있는 사용자의 갤러리 댓글을 필터링합니다',
      'blockRule.ruleCount': '@count개 규칙',
      'blockRule.ungrouped': '그룹 없음',
      'blockRule.deleteGroup': '그룹 삭제',
      'blockRule.target': '대상',
      'blockRule.attribute': '속성',
      'blockRule.pattern': '패턴',
      'blockRule.expression': '표현식',
      'blockRule.expressionHint': '일치할 값',
      'blockRule.groupId': '그룹 ID',
      'blockRule.groupIdHint': '선택적 그룹 이름',
      'blockRule.blocked': '차단됨',
      'blockRule.tagBlocked': '태그 "@tag"가 차단되었습니다',
      'blockRule.uploaderBlocked': '업로더 "@uploader"가 차단되었습니다',
      'blockRule.blockTag': '이 태그 차단',
      'blockRule.blockUploader': '이 업로더 차단',
      'blockRule.blockCommentUser': '댓글 사용자 차단',
      'blockRule.blockCommentUserConfirm': '댓글 사용자 "@user"를 차단할까요?',
      'blockRule.commentUserBlocked': '댓글 사용자 "@user"가 차단되었습니다',

      // download enhancements
      'simpleSearch': '간단',
      'regexSearch': '정규식',
      'downloads.search': '다운로드 검색...',
      'downloads.allGroups': '모든 그룹',
      'downloads.group': '그룹',

      // tag voting
      'tagVote.search': '검색',
      'tagVote.copyTag': '태그 복사',
      'tagVote.searchUploader': '업로더 검색',
      'tagVote.voteUp': '추천',
      'tagVote.voteDown': '비추천',
      'tagVote.success': '투표 완료',
      'tagVote.votedUp': '"@tag"에 추천했습니다',
      'tagVote.votedDown': '"@tag"에 비추천했습니다',
      'tagVote.failed': '투표 실패: @error',
      'tagVote.addTag': '태그 추가',
      'tagVote.addTagHint': '새 태그를 입력하고 여러 개는 쉼표로 구분하세요',
      'tagVote.addSuccess': '태그가 추가되었습니다',
      'tagVote.addFailed': '태그 추가 실패: @error',

      // responsive layout
      'home.selectGallery': '세부 정보를 보려면 갤러리를 선택하세요',
      'home.selectGalleryHint': '갤러리 상세 정보가 이 패널에 표시됩니다.',

      // gallery detail extras
      'detail.parentGallery': '상위 갤러리',
      'detail.newerVersion': '새 버전 사용 가능',
      'detail.versionHistory': '버전 기록',
      'detail.currentVersion': '현재 버전',
      'detail.torrents': '토렌트',
      'detail.torrentCount': '토렌트 (@count)',
      'detail.noTorrents': '토렌트 없음',
      'detail.outdatedTorrents': '오래됨',
      'detail.downloadTorrent': '토렌트 다운로드',
      'detail.copyMagnet': '마그넷 복사',
      'detail.torrentSeeds': '시드 @count',
      'detail.torrentPeers': '피어 @count',
      'detail.torrentDownloads': '다운로드 @count',
      'detail.loadTorrentsFailed': '토렌트 로드 실패: @error',
      'detail.hhDownload': 'H@H 다운로드',
      'detail.noHHArchives': '사용 가능한 H@H 아카이브 없음',
      'detail.loadHHFailed': 'H@H 아카이브 로드 실패: @error',
      'detail.hhSubmitFailed': 'H@H 다운로드 요청 실패: @error',
      'detail.hhSubmitted': 'H@H 다운로드 요청이 전송되었습니다',

      // settings extras
      'settings.cookieStatusFull': '쿠키 정상 (igneous 포함 — EX 사용 가능)',
      'settings.cookieStatusNoIgneous':
          '쿠키가 설정되었지만 igneous 누락 — EX가 작동하지 않을 수 있음',
      'settings.cookieStatusNone': '로그인 쿠키가 설정되지 않음',
      'settings.siteSwitched': '@site로 전환되었습니다',

      // download progress in detail
      'detail.completed': '완료됨',
      'detail.retryDownload': '재시도',
      'detail.readDownloaded': '다운로드 읽기',
      'detail.deleteDownload': '다운로드 삭제',
      'detail.deleteDownloadConfirm': '이 다운로드와 파일을 삭제하시겠습니까?',
      'detail.archiveCompleted': '아카이브 준비됨',

      // detail enhancements
      'detail.share': '공유',
      'detail.jumpToPage': '페이지 이동',
      'detail.jumpToThumbnail': '썸네일로 이동',
      'detail.similarSearch': '유사 검색',
      'detail.blockGallery': '갤러리 차단',
      'detail.allComments': '모든 댓글',
      'detail.thumbnails': '썸네일 (@count)',
      'detail.viewAllThumbnails': '모든 썸네일 보기',
      'detail.galleryBlocked': '갤러리가 차단되었습니다',
      'detail.jumpPageHint': '페이지 번호 입력 (1-@max)',

      // reader enhancements
      'reader.saveImage': '이미지 저장',
      'reader.openInNewTab': '새 탭에서 열기',
      'reader.reloadImage': '이미지 새로고침',
      'reader.interval': '간격',
      'reader.preload': '미리 로드',
      'reader.imageSpacing': '이미지 간격',
      'reader.autoInterval': '자동 넘기기 간격',
      'reader.startAutoMode': '시작',
      'reader.saveFailed': '이미지를 저장하지 못했습니다',
      'reader.redownloadHint': '다운로드 페이지에서 갤러리 다운로드를 다시 시도하세요.',
      'reader.deviceOrientation': '기기 방향',
      'reader.deviceOrientationWebHint':
          '브라우저에서는 앱처럼 화면 방향을 고정할 수 없습니다. 전체 화면이나 기기 회전 잠금을 사용하세요.',
      'toggleFullScreen': '전체 화면 전환',

      // settings reader
      'settings.defaultFavoriteSlot': '기본 즐겨찾기 폴더',
      'settings.defaultFavoriteNone': '없음 (매번 묻기)',
      'settings.defaultFavoriteHint':
          '활성화하면 하트 클릭 시 기본 폴더를 사용하고, 길게 눌러 다른 폴더를 선택합니다.',
      'settings.readerSettings': '리더 설정',
      'settings.defaultDirection': '기본 방향',
      'settings.imageSpacing': '이미지 간격',
      'settings.preloadPages': '미리 로드 페이지(온라인)',
      'settings.preloadPagesLocal': '미리 로드 페이지(로컬)',
      'settings.imageRegionWidthRatioHint':
          '세로 읽기에만 적용됩니다. 너비 맞춤 모드는 계속 전체 화면 너비를 사용합니다.',
      'settings.autoInterval': '자동 넘기기 간격',
      'settings.fitWidth': '너비 맞춤',
      'hideScroll2TopButton': '맨 위로 버튼',
      'whenScrollUp': '위로 스크롤할 때',
      'whenScrollDown': '아래로 스크롤할 때',
      'never': '사용 안 함',
      'always': '항상',
      'preloadGalleryCover': '갤러리 표지 미리 로드',
      'preloadGalleryCoverHint': '아직 화면에 표시되지 않은 갤러리 표지를 미리 로드합니다',
      'simpleDashboardMode': 'Simple Home Page',
      'simpleDashboardModeHint': 'Hide Ranklist and Popular',
      'showDawnInfo': '새벽 이벤트 표시',
      'showEncounterMonster': 'HentaiVerse 조우 이벤트 표시',

      // home enhancements
      'home.scrollToTop': '맨 위로',
      'home.imageSearch': '이미지로 검색',
      'home.imageSearchFailed': '이미지 검색 실패: @error',
      'home.imageSearchMode': '이미지 검색 결과',
      'stats.title': '방문 통계',
      'stats.totalVisits': '총 방문 수: @n',
      'stats.allTime': '전체 기간',
      'stats.year': '연도',
      'stats.month': '월',
      'stats.day': '일',
      'stats.period': '기간',
      'stats.ranking': '순위',
      'stats.score': '점수',
      'stats.visits': '방문',
      'stats.hits': '조회',
      'stats.noSeries': '차트 데이터 없음',
      'usertags.title': '관심 / 숨김 태그',
      'usertags.loadFailed': '로드 실패: @error',
      'usertags.add': '태그 추가',
      'usertags.tagHint': '형식 namespace:key',
      'usertags.watch': '관심',
      'usertags.hidden': '숨김',
      'usertags.watchAdded': '관심 태그에 추가했습니다',
      'usertags.hiddenAdded': '숨김 태그에 추가했습니다',
      'usertags.defaultTagSet': '기본 태그 세트',
      'usertags.defaultTagSetNone': '없음(매번 묻기)',
      'usertags.none': '없음',
      'usertags.weight': '가중치',
      'usertags.editTitle': '태그 편집',
      'usertags.delete': '삭제',
      'usertags.added': '추가됨',
      'usertags.updated': '업데이트됨',
      'usertags.deleted': '삭제됨',
      'usertags.currentList': '설정된 태그',
      'usertags.tagColor': '태그 색상',
      'usertags.tagSetColor': '태그 세트 색상',
      'usertags.changeColor': '색상 변경',
      'usertags.colorDefault': '기본 색상 사용',
      'enableDefaultTagSet': '기본 태그 세트 사용',
      'enableDefaultTagSetHint': '기본 태그 세트를 바로 사용합니다',
      'disableDefaultTagSetHint': '수동으로 선택',
      'chooseTagSet': '태그 세트 선택',
      'asYourDefault': '기본값으로',
      'downloads.sortBy': '정렬',
      'downloads.sortPriority': '우선순위',
      'downloads.sortTime': '시간',
      'downloads.sortTitle': '제목',
      'downloads.sortStatus': '상태',
      'downloads.allCategories': '전체 분류',
      'downloads.categoryFilter': 'EH 분류',
      'downloads.setPriority': '우선순위',
      'downloads.setGroup': '그룹',
      'downloads.priorityLabel': '우선순위 @n',
      'downloads.groupLabel': '그룹',
      'downloads.groupActions': '그룹 작업',
      'downloads.renameGroup': '그룹 이름 바꾸기',
      'downloads.renameGroupConfirm': '"@group" 그룹의 새 이름:',
      'downloads.groupRenamed': '@count개 작업의 그룹 이름을 바꿨습니다',
      'downloads.clearGroup': '그룹 비우기',
      'downloads.clearGroupConfirm': '"@group" 그룹의 @count개 작업을 default로 이동할까요?',
      'downloads.groupCleared': '@count개 작업을 default로 이동했습니다',
      'downloads.superseded': 'gid @gid 로 업그레이드됨',
      'downloads.editTask': '작업 편집',
      'downloads.selectTasks': '작업 선택',
      'downloads.selectVisible': '현재 목록 작업 선택',
      'downloads.pauseVisible': '현재 목록 작업 일시정지',
      'downloads.resumeVisible': '현재 목록 작업 재개',
      'downloads.reDownloadVisible': '현재 목록 갤러리 다시 다운로드',
      'downloads.reUnlockVisible': '현재 목록 아카이브 다시 잠금 해제',
      'downloads.reDownloadConfirm': '이 갤러리의 다운로드된 파일을 삭제하고 다시 시작할까요?',
      'downloads.reDownloadVisibleConfirm':
          '현재 보이는 @count개 갤러리 파일을 삭제하고 다시 다운로드할까요?',
      'downloads.reDownloadBatchConfirm': '파일을 삭제하고 @scope을(를) 다시 시작할까요?',
      'downloads.reUnlockArchive': '아카이브 다시 잠금 해제',
      'downloads.reUnlockArchiveConfirm': '아카이브 다운로드 링크를 지우고 다시 잠금 해제할까요?',
      'downloads.changeVisibleGroup': '현재 목록 그룹 변경',
      'downloads.changeVisibleGroupConfirm': '현재 보이는 @count개 작업을 이 그룹으로 이동합니다.',
      'downloads.changeBatchGroup': '작업 그룹 변경',
      'downloads.changeBatchGroupConfirm': '@scope을(를) 이 그룹으로 이동합니다.',
      'downloads.changeVisiblePriority': '현재 목록 우선순위 변경',
      'downloads.changeBatchPriority': '작업 우선순위 변경',
      'downloads.changeBatchPriorityConfirm': '@scope의 우선순위를 다음으로 변경합니다:',
      'downloads.deleteVisible': '현재 목록 작업 삭제',
      'downloads.deleteVisibleConfirm': '현재 보이는 @count개 작업을 삭제할 방법을 선택하세요.',
      'downloads.deleteBatchConfirm': '@scope을(를) 삭제할 방법을 선택하세요.',
      'downloads.visibleTaskCount': '현재 보이는 @count개 작업',
      'downloads.selectedTaskCount': '@count개 작업 선택됨',
      'downloads.noBatchTargets': '현재 목록에 처리할 작업이 없습니다',
      'downloads.batchPaused': '@count개 작업을 일시정지했습니다',
      'downloads.batchResumed': '@count개 작업을 재개했습니다',
      'downloads.batchRedownloaded': '@count개 작업을 다시 시작했습니다',
      'downloads.batchReUnlocked': '@count개 아카이브 작업을 다시 잠금 해제했습니다',
      'downloads.batchGroupChanged': '@count개 작업의 그룹을 변경했습니다',
      'downloads.batchPriorityChanged': '@count개 작업의 우선순위를 변경했습니다',
      'downloads.batchDeleted': '@count개 작업을 삭제했습니다',
      'detail.startDownloadTitle': '다운로드 시작',
      'detail.downloadGroup': '그룹',
      'existingGroup': '기존 그룹',
      'groupName': '그룹 이름',
      'detail.downloadPriority': '우선순위(높을수록 먼저 실행)',
      'detail.stats': '통계',
      'detail.similarByTitle': '비슷한 제목',
      'detail.upgradeDownload': '새 버전으로 업데이트',
      'detail.upgradeOk': '새 버전 다운로드가 시작되었습니다',
      'detail.upgradeFailed': '업그레이드 실패: @error',
      'detail.archiveNewVersionHint':
          '새 갤러리 버전이 있습니다. 새 갤러리 페이지에서 아카이브를 다운로드하세요.',
      'detail.openNewVersion': '새 버전 열기',
      'settings.usertags': '관심 / 숨김 태그',
    };
  }
}
