class WebEnUS {
  static Map<String, String> keys() {
    return {
      // common
      'common.cancel': 'Cancel',
      'common.ok': 'OK',
      'common.confirm': 'Confirm',
      'common.error': 'Error',
      'common.success': 'Success',
      'common.failed': 'Failed',
      'common.retry': 'Retry',
      'common.add': 'Add',
      'common.delete': 'Delete',
      'common.reset': 'Reset',
      'common.clear': 'Clear',
      'preset': 'Preset',
      'custom': 'Custom',
      'common.refresh': 'Refresh',
      'common.loading': 'Loading...',
      'common.unknown': 'Unknown',
      'common.images': '@count images',
      'common.pages': '@count pages',
      'common.save': 'Save',
      'common.open': 'Open',
      'common.close': 'Close',
      'localizedReason': 'Please authenticate to continue',
      'passwordErrorHint': 'Password error, please try again',
      'dawnOfaNewDay': 'It is the dawn of a new day!',
      'encounterMonster': 'You have encountered a monster!',
      'encounterMonsterHint': 'Click to fight in the HentaiVerse.',

      // reader / gallery actions (align with native .tr keys)
      'share': 'Share',
      'save': 'Save',
      'reload': 'Reload',
      'cancel': 'Cancel',
      'resampleImage': 'Resample',
      'originalImage': 'Original',
      'downloadOriginalImage': 'Download original image',
      'downloadOriginalImageByDefault': 'Choose original image by default',
      'downloadAllGallerysOfSamePriority':
          'Download all galleries of the same priority',
      'downloadAllGallerysOfSamePriorityHint':
          'By default, only one gallery per priority is downloaded at a time.',
      'useJH2UpdateGallery': 'Use JH server to accelerate gallery updates',
      'restoreDownloadTasks': 'Restore download tasks',
      'restoreDownloadTasksHint': 'Restore download tasks from metadata',
      'restoreTasksAutomatically': 'Restore tasks automatically',
      'restoreTasksAutomaticallyHint':
          'Restore tasks from download metadata when the server starts',
      'home.pasteAndSearch': 'Paste and search or open',
      'home.clipboardEmpty': 'Clipboard is empty',
      'home.clipboardReadFailed':
          'Could not read clipboard. Allow clipboard permission and try again.',
      'galleryUrlDetected': 'Found Gallery URL in Clipboard',
      'galleryUrlDetectedHint': 'Open detected link',
      'restoredGalleryCount': 'Restored galleries',
      'restoredArchiveCount': 'Restored archives',
      'reDownload': 'Re-Download',
      'deleteTask': 'Delete Task Only',
      'deleteTaskAndImages': 'Delete Task And Images',
      'hasCopiedToClipboard': 'Copied to clipboard',
      'search': 'Search',
      'all': 'All',
      'download': 'Download',
      'import': 'Import',
      'delete': 'Delete',
      'deleteSuccess': 'Deleted',
      'serverCondition': 'Server Condition',
      'copyShareCode': 'Copy Share Code',
      'readIndexRecord': 'Read Progress',
      'quickSearch': 'Quick Search',
      'blockingRules': 'Block Rules',
      'searchHistory': 'Search History',
      'galleryHistory': 'Gallery History',
      'autoModeStyle': 'Auto mode style',
      'scroll': 'Scroll',
      'turnPage': 'Turn page',
      'turnPageMode': 'Turn Page Mode',
      'turnPageModeHint': 'To next screen or next image',
      'image': 'Image',
      'screen': 'Screen',
      'adaptive': 'Adaptive',
      'displayFirstPageAlone': 'Display First Page Alone',
      'showThumbnails': 'Show Thumbnails',
      'showScrollBar': 'Show Scroll Bar',
      'showStatusInfo': 'Show Status at Bottom',
      'keepScreenAwakeWhenReading': 'Keep Screen Awake When Reading',
      'gestureRegionWidthRatio': 'Gesture region width ratio',
      'imageRegionWidthRatio': 'Image region width ratio',
      'spaceBetweenImages': 'Space Between Images',
      'defaultTab': 'Default Tab',
      'enablePasswordAuth': 'Enable Password Auth',
      'enableAuthOnResume': 'Enable Auth on Resume',
      'enableAuthOnResumeHints': 'Lock again after 3 seconds in background',
      'setPasswordHint': 'Please input your password',
      'confirmPasswordHint': 'Please input your password again',
      'passwordNotMatchHint': 'Password not match, try again',

      // setup
      'setup.title': 'JHenTai Server Setup',
      'setup.description':
          'Enter the API token shown in the server logs to connect.',
      'setup.tokenLabel': 'API Token',
      'setup.connect': 'Connect',
      'setup.emptyToken': 'Please enter a token',
      'setup.invalidToken':
          'Invalid token. Check your server logs for the correct token.',
      'setup.tokenHint':
          'The token is 64 hex characters on one line — copy the full string, not half.',
      'setup.tokenPasteHint': 'Paste the complete 64-character token from logs',
      'setup.tokenCharCount': '@current / @total characters',
      'setup.tokenWrongLength':
          'Token must be exactly 64 hexadecimal characters (full line from docker logs).',
      'setup.tokenHelpTitle': 'How to find the token in logs',
      'setup.tokenHelpP1':
          'On the host running Docker, open a terminal and run:',
      'setup.tokenHelpP2':
          'Find the line starting with [JHenTai] API token for web UI. Copy the 64 hexadecimal characters after the colon (the full token on one line). If your container name is not jhentai, replace it in the commands below.',
      'setup.tokenHelpAlt':
          'If that line is missing, read the token from the server database (default container name jhentai, data directory /data):',

      // home
      'home.title': 'JHenTai',
      'home.search': 'Search galleries...',
      'home.advancedSearch': 'Advanced search',
      'home.searchFilterSheetTitle': 'Categories & filters',
      'home.leftPaneWidthPx': '@w px',
      'home.twoPaneDividerTooltip':
          'Left pane @w px · double-click divider to restore default width',
      'home.downloads': 'Downloads',
      'home.localGalleries': 'Local Galleries',
      'home.settings': 'Settings',
      'home.subtitle': 'E-Hentai Client',
      'home.home': 'Home',
      'home.popular': 'Popular',
      'home.favorites': 'Favorites',
      'home.watched': 'Watched',
      'home.noGalleries': 'No galleries found',
      'home.previous': 'Previous',
      'home.next': 'Next',
      'home.jumpDate': 'Jump to date',
      'home.page': 'Page @page',
      'home.loadFailed': 'Failed to load: @error',
      'home.favSortTitle': 'Favorites sort',
      'home.favSortFavorited': 'By favorited time',
      'home.favSortPublished': 'By published time',
      'home.favAllFolders': 'All',
      'home.favSlotShort': 'Folder @n',
      // advanced search
      'home.categoryFilter': 'Category Filter',
      'home.minimumRating': 'Minimum Rating',
      'home.ratingAny': 'Any',
      'home.searchIn': 'Search In',
      'home.galleryName': 'Gallery Name',
      'home.tags': 'Tags',
      'home.description': 'Description',
      'home.showExpunged': 'Show Expunged',
      'home.onlyShowGalleriesWithTorrents': 'Only show galleries with torrents',
      'home.pageRange': 'Page range',
      'home.pageAtLeast': 'At least',
      'home.pageAtMost': 'At most',
      'home.language': 'Language',
      'home.languageNone': 'None',
      'home.disableFilterForLanguage': 'Disable language filter',
      'home.disableFilterForUploader': 'Disable uploader filter',
      'home.disableFilterForTags': 'Disable tag filter',
      'home.applySearch': 'Apply & Search',
      // category names
      'category.doujinshi': 'Doujinshi',
      'category.manga': 'Manga',
      'category.artistCg': 'Artist CG',
      'category.gameCg': 'Game CG',
      'category.western': 'Western',
      'category.nonH': 'Non-H',
      'category.imageSet': 'Image Set',
      'category.cosplay': 'Cosplay',
      'category.asianPorn': 'Asian Porn',
      'category.misc': 'Misc',

      // gallery detail
      'detail.copyUrl': 'Copy gallery URL',
      'detail.copied': 'Copied',
      'detail.switchToSite': 'Switch to @site',
      'detail.removeFromFav': 'Remove from favorites',
      'detail.addToFav': 'Add to favorites',
      'detail.addToFavTitle': 'Add to favorites',
      'detail.favRemoved': 'Removed',
      'detail.favRemovedMsg': 'Removed from favorites',
      'detail.favAdded': 'Added',
      'detail.favAddedMsg': 'Added to @name',
      'detail.favError': 'Favorite operation failed: @error',
      'detail.favSlot': 'Favorites @n',
      'detail.favNoteHint': 'Favorite note (optional)',
      'detail.favQuickAddTooltip': 'Add to default folder (long-press)',
      'detail.rateTitle': 'Rate this gallery',
      'detail.rateSubmit': 'Submit',
      'detail.rated': 'Rated',
      'detail.ratedMsg': 'Your rating: @rating',
      'detail.rateFailed': 'Rating failed: @error',
      'detail.rateLoginRequired': 'Cannot rate — login required',
      'detail.ratingCount': '@count ratings',
      'detail.favoriteCount': 'Favorited @count',
      'detail.readOnline': 'Read Online',
      'detail.readOnlineResume': 'Read online (resume page @page)',
      'detail.downloadGallery': 'Download Gallery',
      'detail.archiveResample': 'Archive (Resample)',
      'detail.archiveOriginal': 'Archive (Original)',
      'detail.downloadArchive': 'Download archive',
      'detail.downloadStarted': 'Download Started',
      'detail.galleryQueued': 'Gallery download has been queued',
      'detail.archiveQueued': 'Archive download has been queued',
      'detail.downloadFailed': 'Failed to start download: @error',
      'detail.archiveFailed': 'Failed to start archive download: @error',
      'detail.loadArchiveInfoFailed': 'Failed to load archive info: @error',
      'detail.noArchive': 'No archive available',
      'detail.tags': 'Tags',
      'detail.comments': 'Comments (@count)',
      'detail.anonymous': 'Anonymous',
      'detail.loadFailed': 'Failed to load gallery detail: @error',
      'detail.metadataOnly':
          'Full detail page is unavailable. Showing EH API metadata.',

      // reader
      'reader.loading': 'Loading gallery...',
      'reader.loadingGalleryMeta': 'Loading page list...',
      'reader.resolvingFirstPages': 'Resolving image pages...',
      'reader.resolvingImagePage': 'Resolving page...',
      'reader.loadingImage': 'Loading image...',
      'reader.loadFailed': 'Failed to load gallery: @error',
      'reader.imageFailed': 'Failed to load image',
      'reader.noImages': 'No images provided',
      'reader.directionLabel': 'Reading direction: @dir',
      'reader.ltr': 'LTR',
      'reader.rtl': 'RTL',
      'reader.vertical': 'Vertical',
      'reader.shortcuts': 'Shortcuts',
      'reader.shortcutRightKeys': '→ / ↓ / D',
      'reader.shortcutLeftKeys': '← / ↑ / A',
      'reader.shortcutNext': 'Next page',
      'reader.shortcutPrev': 'Previous page',
      'reader.shortcutToggleMenu': 'Show/hide menu',
      'reader.shortcutBack': 'Back',
      'reader.wheelAction': 'Mouse wheel on image',
      'reader.wheelActionPage': 'Turn page',
      'reader.wheelActionZoom': 'Zoom image',
      'reader.wheelActionVerticalHint':
          'Vertical and fit-width modes always scroll the list. This option applies to LTR, RTL, and double-page modes.',
      'reader.wheelInvertPageTurn': 'Invert wheel page turn',
      'reader.wheelInvertPageTurnSubtitle':
          'Swaps which scroll direction goes to the next vs previous page (wheel / trackpad).',
      'reader.wheelScrollSpeed': 'Wheel scroll speed',
      'reader.wheelScrollSpeedSubtitle':
          'Controls mouse wheel speed in vertical and fit-width reader modes.',
      'wheelScrollSpeed': 'Wheel scroll speed',

      // downloads
      'downloads.title': 'Downloads',
      'downloads.gallery': 'Gallery',
      'downloads.archive': 'Archive',
      'downloads.noGallery': 'No gallery downloads',
      'downloads.noArchive': 'No archive downloads',
      'downloads.read': 'Read',
      'downloads.pause': 'Pause',
      'downloads.resume': 'Resume',
      'downloads.deleteTitle': 'Delete Download',
      'downloads.deleteConfirm': 'Choose whether to keep downloaded files.',
      'downloads.loadFailed': 'Failed to load tasks: @error',
      // gallery statuses
      'downloads.gStatus0': 'None',
      'downloads.gStatus1': 'Downloading',
      'downloads.gStatus2': 'Paused',
      'downloads.gStatus3': 'Completed',
      'downloads.gStatus4': 'Failed',
      // archive statuses
      'downloads.aStatus0': 'None',
      'downloads.aStatus1': 'Unlocking',
      'downloads.aStatus2': 'Parsing URL',
      'downloads.aStatus3': 'Downloading',
      'downloads.aStatus4': 'Downloaded',
      'downloads.aStatus5': 'Unpacking',
      'downloads.aStatus6': 'Completed',
      'downloads.aStatus7': 'Paused',
      'downloads.aStatus8': 'Failed',

      // local
      'local.title': 'Local Galleries',
      'local.noGalleries': 'No local galleries found',
      'local.helpText':
          'Mount directories into the Docker container\nor place galleries in the local_gallery folder',
      'local.scanNow': 'Scan Now',
      'local.empty': 'Empty',
      'local.noImages': 'No images found in this gallery',
      'local.loadFailed': 'Failed to load gallery images: @error',
      'local.loadListFailed': 'Failed to load local galleries: @error',
      'local.deleteTitle': 'Delete Local Gallery',
      'local.deleteConfirm': 'Delete local files for "@title"?',
      'local.deleteSuccess': 'Local gallery deleted',
      'local.deleteFailed': 'Failed to delete local gallery: @error',
      'local.parentDirectory': 'Parent Directory',
      'local.copyPath': 'Copy Path',
      'local.copyAllPaths': 'Copy All Paths',
      'local.scanRoots': 'Scan Roots',
      'local.scanRootsHint':
          'These are the container paths that the Docker server scans. Add a mounted path here, or use Docker volume mounts and JH_EXTRA_SCAN_PATHS.',
      'local.addScanRoot': 'Add scan root',
      'local.addScanRootFailed': 'Failed to add scan root: @error',
      'local.deleteScanRootFailed': 'Failed to remove scan root: @error',
      'local.noScanRoots': 'No scan roots configured',

      // settings
      'settings.title': 'Settings',
      'settings.account': 'Account',
      'settings.loggedIn': 'Logged in as: @user',
      'settings.logout': 'Logout',
      'settings.logoutSuccess': 'Logged out',
      'settings.logoutFailed': 'Logout failed: @error',
      'settings.cookieLogin': 'Login with cookies (recommended)',
      'settings.cookieHint':
          'EH forum login is blocked by Cloudflare in server environments. '
              'Please login via browser, then copy cookies here.\n'
              'Steps: Login at e-hentai.org → F12 → Application → Cookies → copy values below.',
      'settings.cookiePlaceholder':
          'ipb_member_id=xxx; ipb_pass_hash=xxx; igneous=xxx',
      'settings.setCookies': 'Set Cookies',
      'settings.pasteCookies': 'Paste Cookies',
      'settings.cookieSuccess': 'Cookies set successfully',
      'settings.cookieFailed': 'Failed to set cookies: @error',
      'settings.cookieEmpty': 'Please paste cookies',
      'settings.showCookies': 'Show Cookies',
      'settings.copyCookies': 'Copy Cookies',
      'settings.copyKeyCookies': 'Copy Login Cookies',
      'settings.refreshIgneous': 'Refresh igneous',
      'settings.refreshIgneousSuccess': 'igneous refreshed',
      'settings.refreshIgneousFailed': 'Failed to refresh igneous',
      'settings.refreshIgneousFailedWithError':
          'Failed to refresh igneous: @error',
      'settings.credentialLogin':
          'Login with credentials (may fail due to Cloudflare)',
      'settings.username': 'Username',
      'settings.password': 'Password',
      'settings.login': 'Login',
      'settings.loginSuccess': 'Login successful',
      'settings.loginFailed': 'Login failed',
      'settings.loginError': 'Login failed: @error',
      'settings.emptyCredentials': 'Please enter username and password',
      'settings.site': 'Site',
      'redirect2Eh': 'Redirect to EH if available',
      'redirect2EhHint':
          'Try loading gallery details from EH first for better network performance.',
      'settings.appearance': 'Appearance',
      'settings.themeMode': 'Theme Mode',
      'settings.system': 'System',
      'settings.light': 'Light',
      'settings.dark': 'Dark',
      'settings.accentColor': 'Accent Color',
      'settings.serverInfo': 'Server Info',
      'settings.dataDir': 'Data Directory',
      'settings.downloadDir': 'Download Directory',
      'settings.localGalleryDir': 'Local Gallery Dir',
      'settings.extraScanPaths': 'Extra Scan Paths',
      'settings.switchSiteFailed': 'Failed to switch site: @error',
      'settings.language': 'Language',
      'settings.sectionData': 'Data & tools',
      'settings.sectionStyle': 'Style',
      'settings.sectionRead': 'Reader',
      'settings.sectionTags': 'Tags & filtering',
      'settings.sectionOther': 'Other',
      'settings.openDownloads': 'Downloads',
      'settings.openHistory': 'Browsing history',
      'settings.openLocal': 'Local galleries',
      'settings.openQuickSearch': 'Quick search',
      'settings.networkNote': 'Network & proxy',
      'settings.networkWebBody':
          'Proxy and advanced networking are configured on the server host or Docker environment. '
              'This page shows the current runtime proxy state for EH/EX and H@H image requests.',
      'settings.about': 'About',
      'settings.appVersion': 'Version @version (@build)',
      'settings.hubMenu': 'Settings menu',
      'settings.menuWebDocker': 'Web UI & server',
      'settings.menuWebDockerSubtitle':
          'Downloads shortcut, Docker paths, network/proxy notes, performance and security (Web only).',
      'settings.menuEH': 'E-Hentai',
      'settings.menuStyle': 'Style',
      'settings.menuRead': 'Read',
      'settings.menuPreference': 'Preference',
      'settings.menuNetwork': 'Network',
      'settings.menuDownload': 'Download',
      'settings.menuPerformance': 'Performance',
      'settings.menuMouseWheel': 'Mouse wheel',
      'settings.menuAdvanced': 'Advanced',
      'settings.menuSecurity': 'Security',
      'settings.ehRequiresLogin':
          'Log in from Account to change site and cookie status.',
      'settings.ehMyTags': 'My Tags',
      'settings.ehMyTagsHint': 'Manage watched and hidden tags online',
      'settings.ehSiteSetting': 'Site settings',
      'settings.ehSiteSettingHint':
          'Open the E-Hentai / ExHentai settings page in a new tab',
      'settings.ehProfile': 'Profile settings',
      'settings.ehSelectedProfile': 'Selected profile',
      'settings.ehProfileHint':
          'Current site: @site. Switches the active site profile through the sp cookie, matching the app.',
      'settings.ehProfileEmpty': 'No profiles found',
      'settings.ehProfileSaved': 'Profile switched',
      'settings.ehProfileSaveFailed': 'Failed to switch profile: @error',
      'settings.ehProfileLoadFailed': 'Failed to load profiles: @error',
      'settings.ehProfileAndQuota': 'Profile, quota, and assets',
      'settings.ehProfileAndQuotaHint':
          'These values still depend on site-page parsing. You can view them from the site settings page for now.',
      'settings.ehAssets': 'Assets',
      'settings.ehImageQuota': 'Image quota',
      'settings.ehResetCost': 'Reset cost',
      'settings.ehQuotaUnavailable':
          'Image quota is available to donators only',
      'settings.ehQuotaReset': 'Image quota has been reset',
      'settings.ehQuotaResetFailed': 'Failed to reset image quota: @error',
      'settings.ehStatusFailed': 'Failed to load EH status: @error',
      'settings.galleryListStyle': 'Gallery list style',
      'pageListStyle': 'Gallery list style (page)',
      'global': 'Global',
      'settings.listModeGrid': 'Grid',
      'settings.listModeList': 'List',
      'settings.listModeCompact': 'Compact',
      'settings.gridColumns': 'Grid columns',
      'settings.gridColumnsAuto': 'Auto',
      'settings.downloadGridColumns': 'Download grid columns',
      'settings.downloadGridColumnsHint':
          'Applies to the download task grid in this browser.',
      'settings.localGridColumns': 'Local gallery grid columns',
      'settings.localGridColumnsHint':
          'Applies to local gallery folders and gallery grids in this browser.',
      'settings.detailThumbnailColumns': 'Detail thumbnail columns',
      'settings.detailThumbnailColumnsHint':
          'Applies to gallery detail thumbnails and the full thumbnail page.',
      'moveCover2RightSide': 'Move Cover to Right Side',
      'settings.moveCoverWebHint':
          'Applies to wide gallery detail pages in this browser.',
      'settings.galleryListStyleHint':
          'Applies to the web home gallery list immediately and is saved in this browser.',
      'settings.showGalleryListTags': 'Show tags in gallery lists',
      'settings.showGalleryListTagsHint':
          'Matches the app list styles that can hide gallery tags for a cleaner list.',
      'settings.pageListStyleHint':
          'Override the gallery list style for individual web sections. Global uses the style above.',
      'settings.networkWebSummary':
          'Proxy state is shown on the Network page. Restart the server after changing Docker environment variables.',
      'settings.proxyRouting': 'Request routing',
      'settings.ehProxyRoute': 'EH/EX page requests',
      'settings.hathProxyRoute': 'H@H image requests',
      'settings.hathProxyDedicatedHint':
          'JH_HATH_PROXY is configured, so *.hath.network uses that proxy first.',
      'settings.hathProxyFallbackHint':
          'JH_HATH_PROXY is not configured, so *.hath.network falls back to HTTPS_PROXY/HTTP_PROXY. Set JH_HATH_PROXY if H@H still fails direct access.',
      'settings.proxyEnvironment': 'Proxy environment',
      'settings.proxyEnvironmentEmpty':
          'No proxy environment values were reported.',
      'settings.proxyEnvironmentHint':
          'Only protocol, host, and port are shown here. Credentials are hidden.',
      'settings.proxyAuthConfigured': 'auth configured',
      'settings.copyNetworkDiagnostics': 'Copy network diagnostics',
      'settings.networkRuntimeFlags': 'Network diagnostics',
      'settings.networkRestartHint':
          'These values come from the server startup environment. Restart the container after changing them.',
      'settings.directConnection': 'Direct',
      'settings.configured': 'Configured',
      'settings.notConfigured': 'Not configured',
      'settings.enabled': 'Enabled',
      'settings.disabled': 'Disabled',
      'settings.downloadWebSummary':
          'Set download defaults, review Docker download paths and concurrency, and manage download tasks.',
      'settings.downloadWebIntro':
          'Set default groups and priorities used by the web download dialogs, and review server-side Docker download settings.',
      'settings.downloadDefaults': 'Download defaults',
      'settings.downloadDefaultsSaved': 'Download defaults saved',
      'settings.defaultGalleryDownload': 'Gallery download',
      'settings.defaultArchiveDownload': 'Archive download',
      'settings.customGroupName': 'Custom group name',
      'speedLimit': 'Speed limit',
      'settings.speedLimitWebHint':
          'Limits gallery image downloads on the Docker server. Use 99 for unlimited.',
      'settings.speedLimitMaximum': 'Images',
      'settings.speedLimitPeriod': 'Per',
      'settings.unlimited': 'Unlimited',
      'settings.downloadServerRuntime': 'Server runtime',
      'settings.galleryConcurrency': 'Gallery concurrency',
      'settings.archiveConcurrency': 'Archive concurrency',
      'settings.jhPublicApiBaseUrl': 'JH public API',
      'settings.jhAppId': 'JH app ID',
      'settings.jhApiSecretConfigured': 'JH API secret',
      'settings.downloadRuntimeHint':
          'Concurrency and paths are controlled by Docker environment variables and take effect after restarting the server.',
      'settings.performanceWebSummary':
          'Tune the web download-list animation threshold to reduce browser work on large groups.',
      'settings.webPerformance': 'Web performance',
      'settings.performanceWebIntro':
          'The web client runs in your browser. These local browser settings affect large-list interaction smoothness.',
      'settings.webMaxGalleryNum4Animation': 'Download group animation limit',
      'settings.webMaxGalleryNum4AnimationHint':
          'Disable expand/collapse icon animation when a download group has more tasks than this value. Use 0 to always disable it.',
      'settings.resetPerformanceDefaults': 'Reset performance defaults',
      'settings.performanceSaved': 'Performance settings saved',
      'settings.advancedWebSummary':
          'Enable no-image mode, review Docker paths, and manage server logs.',
      'settings.advancedWebIntro':
          'Control image loading, server logs, and Docker path information for this web instance.',
      'settings.exportData': 'Export data',
      'settings.exportDataHint':
          'Download settings, block rules, history, search history, and quick searches as JSON. Tokens and cookies are excluded.',
      'settings.exportDataSuccess': 'Data export downloaded',
      'settings.exportDataFailed': 'Failed to export data: @error',
      'settings.exportAppData': 'Export for App',
      'settings.exportAppDataHint':
          'Download an App-compatible JHenTaiConfig file with read progress, quick searches, block rules, search history, and gallery history.',
      'settings.exportAppDataSuccess': 'App-compatible export downloaded',
      'settings.importData': 'Import data',
      'settings.importDataHint':
          'Import a Web export or App JHenTaiConfig JSON and merge it into this server. Settings and named items are overwritten; block rules are de-duplicated.',
      'settings.importDataTitle': 'Import data?',
      'settings.importDataConfirm':
          'Choose a JHenTai Web export or App JHenTaiConfig file. Imported settings may overwrite current values.',
      'settings.importDataSuccess': 'Imported @count items',
      'settings.importDataFailed': 'Failed to import data: @error',
      'settings.cloudSync': 'Cloud Config Sync',
      'settings.cloudSyncHint':
          'Browse JHenTai cloud configs, import by share code, and merge them into this Docker server.',
      'settings.cloudServiceAvailable':
          'JHenTai cloud config service is available',
      'settings.cloudServiceUnavailable':
          'JHenTai cloud config service is unavailable',
      'settings.cloudShareCode': 'Share code',
      'settings.cloudConfigType': 'Config type',
      'settings.cloudConfigEmpty': 'No cloud configs',
      'settings.cloudConfigNotFound': 'No config found for this share code',
      'settings.cloudConfigUnknownType': 'Unknown config',
      'settings.uploadCloudConfig': 'Upload to cloud',
      'settings.uploadCloudConfigTitle': 'Upload current data to cloud?',
      'settings.uploadCloudConfigConfirm':
          'Select the local data types to upload to JHenTai cloud config service.',
      'settings.uploadCloudConfigSuccess': 'Cloud config uploaded',
      'settings.uploadCloudConfigFailed':
          'Failed to upload cloud config: @error',
      'settings.deleteCloudConfigTitle': 'Delete cloud config?',
      'settings.deleteCloudConfigConfirm':
          'This removes the config from the JHenTai cloud service.',
      'settings.deleteCloudConfigFailed':
          'Failed to delete cloud config: @error',
      'settings.noImageMode': 'No image mode',
      'settings.noImageModeHint':
          'Hide gallery covers, thumbnails, and reader images in this browser.',
      'checkClipboard': 'Check Gallery URL in Clipboard',
      'settings.checkClipboardHint':
          'When the home page opens, detect gallery links from the browser clipboard and offer to open them.',
      'settings.pageCache': 'Page cache',
      'settings.clearPageCache': 'Clear page cache',
      'settings.clearPageCacheTitle': 'Clear page cache?',
      'settings.clearPageCacheConfirm':
          'This will delete cached EH page responses on the server.',
      'settings.clearPageCacheFailed': 'Failed to clear page cache: @error',
      'settings.loadPageCacheFailed': 'Failed to load page cache: @error',
      'settings.pageCacheSummary': '@count cached pages · @size',
      'settings.serverLogs': 'Server logs',
      'settings.clearLogsTitle': 'Clear server logs?',
      'settings.clearLogsConfirm':
          'This will delete all current server log files.',
      'settings.clearLogsFailed': 'Failed to clear logs: @error',
      'settings.loadLogsFailed': 'Failed to load logs: @error',
      'settings.loadLogFailed': 'Failed to load log: @error',
      'settings.noLogs': 'No logs yet',
      'settings.copyLog': 'Copy log',
      'settings.downloadLog': 'Download log',
      'settings.emptyLog': 'This log is empty',
      'settings.securityWebSummary':
          'Check the API token saved in this browser, verify the connection, or disconnect and reconnect.',
      'settings.webTokenSecurity': 'Web connection security',
      'settings.webTokenSaved': 'Local token',
      'settings.webTokenSavedYes': 'Saved in this browser',
      'settings.webTokenSavedNo': 'No token saved in this browser',
      'settings.webTokenFingerprint': 'Token fingerprint',
      'settings.webTokenVerifyStatus': 'Verify status',
      'settings.webTokenValid': 'Current token is valid',
      'settings.webTokenInvalid': 'Current token is invalid or rotated',
      'settings.securityWebBody':
          'The web UI connects with an API token stored in this browser. The full token is never shown here; this only checks the current browser connection.',
      'settings.verifyCurrentToken': 'Verify current token',
      'settings.disconnectWebToken': 'Disconnect and reconnect',
      'settings.disconnectWebTokenTitle':
          'Disconnect the current web connection?',
      'settings.disconnectWebTokenConfirm':
          'This clears the API token saved in this browser and returns to setup. The server token will not be deleted.',
      'settings.webTokenRotateHint':
          'If you rotated the token on the server, disconnect here first, then paste the new token in setup.',
      'settings.webPasswordAuthHint':
          'Protect this browser session with a local 4-digit PIN.',
      'settings.lockNow': 'Lock now',
      'settings.disablePasswordAuthTitle': 'Disable password auth?',
      'settings.disablePasswordAuthConfirm':
          'This removes the local PIN saved in this browser.',
      'settings.passwordAuthEnabled': 'Password auth enabled',
      'settings.changeWebPin': 'Change PIN',
      'settings.currentWebPinHint': 'Enter your current PIN',
      'settings.newWebPinHint': 'Enter a new PIN',
      'settings.webPinChanged': 'PIN changed',
      'settings.mouseWheelIntro':
          'Choose how the mouse wheel behaves over images in the reader (horizontal page modes).',
      'settings.webWheelScrollSpeedHint':
          'Controls mouse wheel speed for Web gallery lists.',
      'settings.mouseWheelReadHint': 'Direction, preload, and more',
      'settings.aboutVersionLabel': 'Version',
      'settings.aboutAuthorLabel': 'Author',
      'settings.aboutTelegramTitle': 'Telegram (Chinese mainly)',
      'settings.aboutTelegramHint': 'Community link',
      'settings.aboutQA': 'Q & A',
      'settings.aboutWebForkNote':
          'This web UI is served from the JHenTai Docker fork; upstream is linked above.',

      // history
      'history.title': 'History',
      'history.empty': 'No browsing history',
      'history.clearAll': 'Clear All',
      'history.clearTitle': 'Clear History',
      'history.clearConfirm':
          'Are you sure you want to clear all browsing history?',
      'history.deleteTitle': 'Delete History Item',
      'history.deleteConfirm': 'Remove "@title" from browsing history?',
      'history.loadFailed': 'Failed to load history: @error',
      'history.loadMore': 'Load more',
      'history.search': 'Search browsing history...',
      'history.jumpToPage': 'Jump history page',
      'history.pageRange': 'Range: 1 - @total, current: @current',

      // search history
      'searchHistory.clearAll': 'Clear search history',
      'searchHistory.clearTitle': 'Clear Search History',
      'searchHistory.clearConfirm':
          'Are you sure you want to clear all search history?',
      'searchHistory.translate': 'Translate search history',

      // comment
      'comment.placeholder': 'Write a comment...',
      'comment.send': 'Send',
      'comment.posted': 'Comment Posted',
      'comment.postedMsg': 'Your comment has been posted',
      'comment.postFailed': 'Failed to post comment: @error',
      'comment.voteFailed': 'Failed to vote: @error',
      'comment.scoreDetails': 'Score Details',
      'lastEditedOn': 'Last edited on',
      'comment.update': 'Update Comment',
      'comment.updated': 'Comment Updated',
      'comment.updatedMsg': 'Your comment has been updated',
      'comment.updateFailed': 'Failed to update comment: @error',
      'comment.tooShort': 'Comment is too short',
      'comment.atLeast3Characters': 'At least 3 characters',

      // ranklist
      'ranklist.title': 'Ranklist',
      'ranklist.allTime': 'All Time',
      'ranklist.year': 'Past Year',
      'ranklist.month': 'Past Month',
      'ranklist.yesterday': 'Yesterday',

      // thumbnails
      'thumbnails.title': 'Thumbnails (@count)',
      'thumbnails.grid': 'Thumbnail Grid',
      'thumbnails.jumpToPage': 'Jump to Page',
      'thumbnails.pageRange': 'Range: 1 - @total',
      'thumbnails.loadFailed': 'Failed to load thumbnails: @error',

      // home additions
      'home.history': 'History',
      'home.ranklist': 'Ranklist',

      // tag translation
      'tagInfo.title': 'Tag details',
      'tagInfo.empty': 'No tag details available',
      'tagInfo.loadFailed': 'Failed to load tag details: @error',
      'showR18GImageDirectly': 'Show R18G Image Directly',
      'warningImageHint': 'R18G image, click to view',
      'tagTranslation.title': 'Tag Translation',
      'tagTranslation.loaded': '@count tags loaded',
      'tagTranslation.notLoaded': 'Tag database not loaded',
      'tagTranslation.lastUpdate': 'Last update: @time',
      'tagTranslation.refresh': 'Refresh Tag Database',
      'tagTranslation.refreshSuccess': '@count tags updated',
      'tagTranslation.refreshFailed': 'Failed to refresh: @error',
      'zhTagSearchOrderOptimization':
          'Chinese Tag Auto-Completion Ordering Rule',
      'zhTagSearchOrderOptimizationHint':
          'Intelligent sorting by default and sort by frequency if enabled',
      'tagSearchOrder.loaded': '@count tag frequency rows loaded',
      'tagSearchOrder.notLoaded': 'Tag frequency data not loaded',
      'tagSearchOrder.version': 'Version: @version',
      'tagSearchOrder.refresh': 'Refresh Tag Frequency Data',
      'tagSearchOrder.refreshSuccess': '@count tag frequency rows updated',
      'tagSearchOrder.refreshFailed': 'Failed to refresh: @error',

      // list mode
      'listMode.toggle': 'Toggle view mode',
      'listMode.grid': 'Grid',
      'listMode.list': 'List',
      'listMode.listCompact': 'Compact List',

      // quick search
      'quickSearch.title': 'Quick Search',
      'quickSearch.empty': 'No saved searches',
      'quickSearch.saveCurrent': 'Save current search',
      'quickSearch.saveTitle': 'Save Quick Search',
      'quickSearch.editTitle': 'Edit Quick Search',
      'quickSearch.nameLabel': 'Name',
      'quickSearch.addNew': 'Add quick search',
      'quickSearch.keywordLabel': 'Keyword',
      'quickSearch.keywordHint': 'Same as the home search bar',
      'quickSearch.saved': 'Saved',
      'quickSearch.deleted': 'Deleted',
      'quickSearch.deleteTitle': 'Delete quick search',
      'quickSearch.deleteConfirm': 'Remove "@name"?',

      // tag suggest
      'tagSuggest.tag': 'Tag',

      // reader enhancements
      'reader.fitWidth': 'Fit Width',
      'reader.doubleColumn': 'Double Column',
      'reader.autoStart': 'Auto Read',
      'reader.autoStop': 'Stop Auto Read',

      'enableBottomMenu': 'Enable bottom menu',

      'enablePageTurnAnime': 'Enable page turn animation',
      'enableDoubleTapToScaleUp': 'Enable double-tap zoom',
      'enableTapDragToScaleUp': 'Enable tap-drag zoom',
      'reverseTurnPageDirection': 'Reverse tap page turning direction',
      'disablePageTurningOnTap': 'Disable tap-to-turn-page',
      // block rules
      'blockRule.title': 'Block Rules',
      'blockRule.empty': 'No block rules configured',
      'blockRule.add': 'Add Rule',
      'blockRule.edit': 'Edit Rule',
      'blockRule.manage': 'Manage Block Rules',
      'useBuiltInBlockedUsers': 'Enable Built-in User Blocklist',
      'useBuiltInBlockedUsersHint':
          'Filter out gallery comments from users on the built-in blocklist',
      'blockRule.ruleCount': '@count rules',
      'blockRule.ungrouped': 'Ungrouped',
      'blockRule.deleteGroup': 'Delete Group',
      'blockRule.deleteGroupTitle': 'Delete Block Rule Group',
      'blockRule.deleteGroupConfirm':
          'Delete group "@group" and its @count rules?',
      'blockRule.deleteRuleTitle': 'Delete Block Rule',
      'blockRule.deleteRuleConfirm': 'Delete rule "@rule"?',
      'blockRule.target': 'Target',
      'blockRule.attribute': 'Attribute',
      'blockRule.pattern': 'Pattern',
      'blockRule.expression': 'Expression',
      'blockRule.expressionHint': 'Value to match against',
      'blockRule.groupId': 'Group ID',
      'blockRule.groupIdHint': 'Optional group name',
      'blockRule.blocked': 'Blocked',
      'blockRule.tagBlocked': 'Tag "@tag" has been blocked',
      'blockRule.uploaderBlocked': 'Uploader "@uploader" has been blocked',
      'blockRule.blockTag': 'Block this tag',
      'blockRule.blockUploader': 'Block this uploader',
      'blockRule.blockCommentUser': 'Block comment user',
      'blockRule.blockCommentUserConfirm': 'Block comment user "@user"?',
      'blockRule.commentUserBlocked': 'Comment user "@user" has been blocked',

      // download enhancements
      'simpleSearch': 'Simple',
      'regexSearch': 'Regex',
      'downloads.search': 'Search downloads...',
      'downloads.allGroups': 'All Groups',
      'downloads.group': 'Group',

      // tag voting
      'tagVote.search': 'Search',
      'tagVote.copyTag': 'Copy tag',
      'tagVote.searchUploader': 'Search uploader',
      'tagVote.voteUp': 'Vote Up',
      'tagVote.voteDown': 'Vote Down',
      'tagVote.success': 'Voted',
      'tagVote.votedUp': 'Voted up for "@tag"',
      'tagVote.votedDown': 'Voted down for "@tag"',
      'tagVote.failed': 'Vote failed: @error',
      'tagVote.addTag': 'Add Tag',
      'tagVote.addTagHint': 'Enter new tags, separated with commas',
      'tagVote.addSuccess': 'Tag added',
      'tagVote.addFailed': 'Failed to add tag: @error',

      // responsive layout
      'home.selectGallery': 'Select a gallery to view details',
      'home.selectGalleryHint': 'Gallery details will appear in this pane.',

      // gallery detail extras
      'detail.parentGallery': 'Parent Gallery',
      'detail.newerVersion': 'Newer Version Available',
      'detail.versionHistory': 'Version History',
      'detail.currentVersion': 'Current Version',
      'detail.torrents': 'Torrents',
      'detail.torrentCount': 'Torrent (@count)',
      'detail.noTorrents': 'No torrents',
      'detail.outdatedTorrents': 'Outdated',
      'detail.downloadTorrent': 'Download torrent',
      'detail.copyMagnet': 'Copy magnet',
      'detail.torrentSeeds': 'Seeds @count',
      'detail.torrentPeers': 'Peers @count',
      'detail.torrentDownloads': 'Downloads @count',
      'detail.loadTorrentsFailed': 'Failed to load torrents: @error',
      'detail.hhDownload': 'H@H Download',
      'detail.noHHArchives': 'No H@H archives available',
      'detail.loadHHFailed': 'Failed to load H@H archives: @error',
      'detail.hhSubmitFailed': 'Failed to request H@H download: @error',
      'detail.hhSubmitted': 'H@H download request submitted',

      // settings extras
      'settings.cookieStatusFull': 'Cookies OK (includes igneous — EX ready)',
      'settings.cookieStatusNoIgneous':
          'Cookies set but missing igneous — EX may not work',
      'settings.cookieStatusNone': 'No login cookies set',
      'settings.siteSwitched': 'Switched to @site',

      // download progress in detail
      'detail.completed': 'Completed',
      'detail.retryDownload': 'Retry',
      'detail.readDownloaded': 'Read Downloaded',
      'detail.deleteDownload': 'Delete Download',
      'detail.deleteDownloadConfirm': 'Delete this download and its files?',
      'detail.archiveCompleted': 'Archive Ready',

      // detail enhancements
      'detail.share': 'Share',
      'detail.jumpToPage': 'Jump to Page',
      'detail.jumpToThumbnail': 'Jump to Thumbnail',
      'detail.similarSearch': 'Similar Search',
      'detail.blockGallery': 'Block Gallery',
      'detail.allComments': 'All Comments',
      'detail.thumbnails': 'Thumbnails (@count)',
      'detail.viewAllThumbnails': 'View All Thumbnails',
      'detail.galleryBlocked': 'Gallery has been blocked',
      'detail.jumpPageHint': 'Enter page number (1-@max)',

      // reader enhancements
      'reader.saveImage': 'Save Image',
      'reader.openInNewTab': 'Open in New Tab',
      'reader.reloadImage': 'Reload Image',
      'reader.interval': 'Interval',
      'reader.preload': 'Preload',
      'reader.imageSpacing': 'Image Spacing',
      'reader.autoInterval': 'Auto-mode Interval',
      'reader.startAutoMode': 'Start',
      'reader.saveFailed': 'Could not save image',
      'reader.redownloadHint':
          'Open Downloads to retry or restart this gallery’s download.',
      'reader.deviceOrientation': 'Device orientation',
      'reader.deviceOrientationWebHint':
          'Browsers cannot lock orientation like the app. Use the browser full-screen or your device rotation lock if needed.',
      'toggleFullScreen': 'Toggle Full Screen',

      // settings reader
      'settings.defaultFavoriteSlot': 'Default favorite folder',
      'settings.defaultFavoriteNone': 'None (always ask)',
      'settings.defaultFavoriteHint':
          'When enabled, click the heart to use the default folder and long-press to choose another.',
      'settings.usertags': 'Watched / hidden tags',
      'settings.readerSettings': 'Reader Settings',
      'settings.defaultDirection': 'Default Direction',
      'settings.imageSpacing': 'Image Spacing',
      'settings.preloadPages': 'Preload Pages (Online)',
      'settings.preloadPagesLocal': 'Preload Pages (Local)',
      'preloadPageCount': 'Preload Page Count (Online)',
      'preloadPageCountInLocalMode': 'Preload Page Count (Local)',
      'preloadDistanceInOnlineMode': 'Preload Distance (Online)',
      'preloadDistanceInLocalMode': 'Preload Distance (Local)',
      'ScreenHeight': 'Screen',
      'settings.imageRegionWidthRatioHint':
          'Only affects vertical reading. Fit Width still uses the full viewport width.',
      'settings.autoInterval': 'Auto-mode Interval',
      'settings.fitWidth': 'Fit Width',
      'hideScroll2TopButton': 'Scroll to top button',
      'whenScrollUp': 'When scrolling up',
      'whenScrollDown': 'When scrolling down',
      'never': 'Never',
      'always': 'Always',
      'preloadGalleryCover': 'Preload gallery cover',
      'preloadGalleryCoverHint':
          'Preload covers for galleries that are not displayed yet',
      'simpleDashboardMode': 'Simple Home Page',
      'simpleDashboardModeHint': 'Hide Ranklist and Popular',
      'showDawnInfo': 'Show new dawn event',
      'showEncounterMonster': 'Show HentaiVerse encounter event',

      // home enhancements
      'home.scrollToTop': 'Scroll to Top',
      'home.imageSearch': 'Search by image',
      'home.imageSearchFailed': 'Image search failed: @error',
      'home.imageSearchMode': 'Image search results',

      'stats.title': 'Visitor statistics',
      'stats.totalVisits': 'Total visits: @n',
      'stats.allTime': 'All time',
      'stats.year': 'Year',
      'stats.month': 'Month',
      'stats.day': 'Day',
      'stats.period': 'Period',
      'stats.ranking': 'Ranking',
      'stats.score': 'Score',
      'stats.visits': 'Visits',
      'stats.hits': 'Hits',
      'stats.noSeries': 'No chart data',

      'usertags.title': 'Watched / hidden tags',
      'usertags.loadFailed': 'Load failed: @error',
      'usertags.add': 'Add tag',
      'usertags.tagHint': 'Format namespace:key',
      'usertags.watch': 'Watch',
      'usertags.hidden': 'Hidden',
      'usertags.watchAdded': 'Tag added to watched tags',
      'usertags.hiddenAdded': 'Tag added to hidden tags',
      'usertags.defaultTagSet': 'Default tag set',
      'usertags.defaultTagSetNone': 'None (ask each time)',
      'usertags.none': 'None',
      'usertags.weight': 'Weight',
      'usertags.editTitle': 'Edit tag',
      'usertags.delete': 'Delete',
      'usertags.added': 'Added',
      'usertags.updated': 'Updated',
      'usertags.deleted': 'Deleted',
      'usertags.currentList': 'Configured tags',
      'usertags.tagColor': 'Tag color',
      'usertags.tagSetColor': 'Tag set color',
      'usertags.changeColor': 'Change color',
      'usertags.colorDefault': 'Use default color',
      'enableDefaultTagSet': 'Enable Default Tag Set',
      'enableDefaultTagSetHint': 'Use the default tag set directly',
      'disableDefaultTagSetHint': 'Select manually',
      'chooseTagSet': 'Choose Tag Set',
      'asYourDefault': 'As Default',

      'downloads.sortBy': 'Sort',
      'downloads.sortPriority': 'Priority',
      'downloads.sortTime': 'Time',
      'downloads.sortTitle': 'Title',
      'downloads.sortStatus': 'Status',
      'downloads.allCategories': 'All categories',
      'downloads.categoryFilter': 'EH category',
      'downloads.setPriority': 'Priority',
      'downloads.setGroup': 'Group',
      'downloads.priorityLabel': 'Priority @n',
      'downloads.groupLabel': 'Group',
      'downloads.groupActions': 'Group actions',
      'downloads.renameGroup': 'Rename group',
      'downloads.renameGroupConfirm': 'Rename group "@group" to:',
      'downloads.groupRenamed': 'Renamed group for @count tasks',
      'downloads.clearGroup': 'Clear group',
      'downloads.clearGroupConfirm':
          'Move @count tasks in "@group" back to default?',
      'downloads.groupCleared': 'Moved @count tasks back to default',
      'downloads.superseded': 'Upgraded to gid @gid',
      'downloads.editTask': 'Edit task',
      'downloads.selectTasks': 'Select tasks',
      'downloads.selectVisible': 'Select visible tasks',
      'downloads.pauseVisible': 'Pause visible tasks',
      'downloads.resumeVisible': 'Resume visible tasks',
      'downloads.reDownloadVisible': 'Re-download visible gallery tasks',
      'downloads.reUnlockVisible': 'Re-unlock visible archive tasks',
      'downloads.reDownloadConfirm':
          'Delete downloaded files for this gallery and start it again?',
      'downloads.reDownloadVisibleConfirm':
          'Delete files and restart @count visible gallery tasks?',
      'downloads.reDownloadBatchConfirm': 'Delete files and restart @scope?',
      'downloads.reUnlockArchive': 'Re-unlock archive',
      'downloads.reUnlockArchiveConfirm':
          'Clear the archive download link and unlock it again?',
      'downloads.changeVisibleGroup': 'Change visible tasks group',
      'downloads.changeVisibleGroupConfirm':
          'Move @count visible tasks to this group.',
      'downloads.changeBatchGroup': 'Change tasks group',
      'downloads.changeBatchGroupConfirm': 'Move @scope to this group.',
      'downloads.changeVisiblePriority': 'Change visible tasks priority',
      'downloads.changeBatchPriority': 'Change tasks priority',
      'downloads.changeBatchPriorityConfirm': 'Set the priority for @scope to:',
      'downloads.deleteVisible': 'Delete visible tasks',
      'downloads.deleteVisibleConfirm':
          'Choose how to delete @count visible tasks.',
      'downloads.deleteBatchConfirm': 'Choose how to delete @scope.',
      'downloads.visibleTaskCount': '@count visible tasks',
      'downloads.selectedTaskCount': '@count selected tasks',
      'downloads.noBatchTargets': 'No matching tasks in the current list',
      'downloads.batchPaused': 'Paused @count tasks',
      'downloads.batchResumed': 'Resumed @count tasks',
      'downloads.batchRedownloaded': 'Restarted @count tasks',
      'downloads.batchReUnlocked': 'Re-unlocked @count archive tasks',
      'downloads.batchGroupChanged': 'Changed group for @count tasks',
      'downloads.batchPriorityChanged': 'Changed priority for @count tasks',
      'downloads.batchDeleted': 'Deleted @count tasks',

      'detail.startDownloadTitle': 'Start download',
      'detail.downloadGroup': 'Group',
      'existingGroup': 'Existing Group',
      'groupName': 'Group name',
      'detail.downloadPriority': 'Priority (higher runs first)',
      'detail.stats': 'Statistics',
      'detail.similarByTitle': 'Similar title',
      'detail.upgradeDownload': 'Update to new version',
      'detail.upgradeOk': 'New version download started',
      'detail.upgradeFailed': 'Upgrade failed: @error',
      'detail.archiveNewVersionHint':
          'A newer gallery version exists. Download archive from the new gallery page.',
      'detail.openNewVersion': 'Open new version',
    };
  }
}
