class WebPtBR {
  static Map<String, String> keys() {
    return {
      // common
      'common.cancel': 'Cancelar',
      'common.ok': 'Confirmar',
      'common.confirm': 'Confirmar',
      'common.error': 'Erro',
      'common.success': 'Sucesso',
      'common.failed': 'Falhou',
      'common.retry': 'Tentar novamente',
      'common.delete': 'Excluir',
      'common.reset': 'Redefinir',
      'common.refresh': 'Atualizar',
      'common.loading': 'Carregando...',
      'common.unknown': 'Desconhecido',
      'common.images': '@count imagens',
      'common.pages': '@count páginas',
      'common.open': 'Abrir',
      'dawnOfaNewDay': 'É o amanhecer de um novo dia!',
      'encounterMonster': 'Você encontrou um monstro!',
      'encounterMonsterHint': 'Clique para lutar no HentaiVerse.',

      'share': 'Compartilhar',
      'save': 'Salvar',
      'reload': 'Recarregar',
      'cancel': 'Cancelar',
      'resampleImage': 'Reamostrada',
      'originalImage': 'Imagem original',
      'downloadOriginalImage': 'Baixar imagem original',
      'downloadOriginalImageByDefault': 'Escolher imagem original por padrão',
      'downloadAllGallerysOfSamePriority':
          'Baixar todas as galerias da mesma prioridade',
      'downloadAllGallerysOfSamePriorityHint':
          'Por padrão, apenas uma galeria por prioridade é baixada por vez.',
      'restoreDownloadTasks': 'Restaurar tarefas de download',
      'restoreDownloadTasksHint': 'Restaurar tarefas de download por metadados',
      'restoreTasksAutomatically': 'Restaurar tarefas automaticamente',
      'restoreTasksAutomaticallyHint':
          'Restaura tarefas pelos metadados de download ao iniciar o servidor',
      'restoredGalleryCount': 'Galerias restauradas',
      'restoredArchiveCount': 'Arquivos restaurados',
      'reDownload': 'Baixar novamente',
      'deleteTask': 'Apagar apenas tarefa',
      'deleteTaskAndImages': 'Apagar tarefa e imagens',
      'hasCopiedToClipboard': 'Copiado para a área de transferência',
      'autoModeStyle': 'Estilo do modo automático',
      'scroll': 'Rolagem',
      'turnPage': 'Virar página',
      'turnPageMode': 'Modo de virar página',
      'turnPageModeHint': 'Para a próxima tela ou próxima imagem',
      'image': 'Imagem',
      'screen': 'Tela',
      'adaptive': 'Adaptativo',
      'displayFirstPageAlone': 'Mostrar primeira página sozinha',
      'showThumbnails': 'Mostrar miniaturas',
      'showScrollBar': 'Mostrar barra de rolagem',
      'showStatusInfo': 'Mostrar status na parte inferior',
      'keepScreenAwakeWhenReading': 'Manter tela ativa ao ler',
      'gestureRegionWidthRatio':
          'Proporção da largura da área de gesto do menu',
      'spaceBetweenImages': 'Espaçamento entre imagens',
      'defaultTab': 'Aba padrão',

      // setup
      'setup.title': 'Configuração do Servidor JHenTai',
      'setup.description':
          'Insira o token API mostrado nos logs do servidor para conectar.',
      'setup.tokenLabel': 'Token API',
      'setup.connect': 'Conectar',
      'setup.emptyToken': 'Por favor, insira um token',
      'setup.invalidToken':
          'Token inválido. Verifique os logs do servidor para o token correto.',
      'setup.tokenHint':
          'O token tem 64 caracteres hex em uma linha — copie a linha inteira.',
      'setup.tokenPasteHint': 'Cole o token completo de 64 caracteres dos logs',
      'setup.tokenCharCount': '@current / @total caracteres',
      'setup.tokenWrongLength':
          'O token deve ter exatamente 64 caracteres hexadecimais (linha completa do docker logs).',
      'setup.tokenHelpTitle': 'Como encontrar o token nos logs',
      'setup.tokenHelpP1':
          'No host onde o Docker está em execução, abra um terminal e execute:',
      'setup.tokenHelpP2':
          'Procure a linha que começa com [JHenTai] API token for web UI. Copie os 64 caracteres hexadecimais após os dois pontos (o token inteiro em uma linha). Se o nome do contêiner não for jhentai, substitua nos comandos abaixo.',
      'setup.tokenHelpAlt':
          'Se essa linha não existir, leia o token no banco de dados do servidor (nome padrão do contêiner jhentai, diretório de dados /data):',

      // home
      'home.title': 'JHenTai',
      'home.search': 'Pesquisar galerias...',
      'home.advancedSearch': 'Pesquisa avançada',
      'home.searchFilterSheetTitle': 'Categorias e filtros',
      'home.leftPaneWidthPx': '@w px',
      'home.twoPaneDividerTooltip':
          'Painel esquerdo @w px · clique duas vezes no divisor para largura padrão',
      'home.downloads': 'Baixados',
      'home.localGalleries': 'Galerias Locais',
      'home.settings': 'Configurações',
      'home.subtitle': 'Cliente E-Hentai',
      'home.home': 'Início',
      'home.popular': 'Populares',
      'home.favorites': 'Favoritos',
      'home.watched': 'Acompanhados',
      'home.noGalleries': 'Nenhuma galeria encontrada',
      'home.previous': 'Anterior',
      'home.next': 'Próximo',
      'home.jumpDate': 'Ir para a data',
      'home.page': 'Página @page',
      'home.loadFailed': 'Falha ao carregar: @error',
      'home.favSortTitle': 'Ordenação dos favoritos',
      'home.favSortFavorited': 'Por data de favorito',
      'home.favSortPublished': 'Por data de publicação',
      'home.favAllFolders': 'Todas',
      'home.favSlotShort': 'Pasta @n',
      'home.categoryFilter': 'Filtro de Categoria',
      'home.minimumRating': 'Avaliação Mínima',
      'home.ratingAny': 'Qualquer',
      'home.searchIn': 'Pesquisar em',
      'home.galleryName': 'Nome da Galeria',
      'home.tags': 'Etiquetas',
      'home.description': 'Descrição',
      'home.showExpunged': 'Mostrar Excluídos',
      'home.onlyShowGalleriesWithTorrents':
          'Mostrar apenas galerias com torrents',
      'home.pageRange': 'Intervalo de páginas',
      'home.pageAtLeast': 'No mínimo',
      'home.pageAtMost': 'No máximo',
      'home.language': 'Idioma',
      'home.languageNone': 'Nenhum',
      'home.disableFilterForLanguage': 'Desativar filtro de idioma',
      'home.disableFilterForUploader': 'Desativar filtro de uploader',
      'home.disableFilterForTags': 'Desativar filtro de tags',
      'home.applySearch': 'Aplicar e Pesquisar',
      'home.history': 'Histórico',
      'home.ranklist': 'Ranking',

      // category names
      'category.doujinshi': 'Doujinshi',
      'category.manga': 'Mangá',
      'category.artistCg': 'CG de Artista',
      'category.gameCg': 'CG de Jogo',
      'category.western': 'Ocidental',
      'category.nonH': 'Non-H',
      'category.imageSet': 'Conjunto de Imagens',
      'category.cosplay': 'Cosplay',
      'category.asianPorn': 'Asiático',
      'category.misc': 'Diversos',

      // gallery detail
      'detail.copyUrl': 'Copiar URL da galeria',
      'detail.copied': 'Copiado',
      'detail.removeFromFav': 'Remover dos favoritos',
      'detail.addToFav': 'Adicionar aos favoritos',
      'detail.addToFavTitle': 'Adicionar aos favoritos',
      'detail.favRemoved': 'Removido',
      'detail.favRemovedMsg': 'Removido dos favoritos',
      'detail.favAdded': 'Adicionado',
      'detail.favAddedMsg': 'Adicionado a @name',
      'detail.favError': 'Operação de favoritos falhou: @error',
      'detail.favSlot': 'Favoritos @n',
      'detail.favNoteHint': 'Nota (opcional)',
      'detail.favQuickAddTooltip': 'Adicionar à pasta padrão (pressione longo)',
      'detail.rateTitle': 'Avaliar esta galeria',
      'detail.rateSubmit': 'Enviar',
      'detail.rated': 'Avaliado',
      'detail.ratedMsg': 'Sua avaliação: @rating',
      'detail.rateFailed': 'Falha na avaliação: @error',
      'detail.rateLoginRequired': 'Não é possível avaliar — login necessário',
      'detail.readOnline': 'Ler Online',
      'detail.readOnlineResume': 'Ler online (retomar na página @page)',
      'detail.downloadGallery': 'Baixar Galeria',
      'detail.archiveResample': 'Arquivo (Comprimido)',
      'detail.archiveOriginal': 'Arquivo (Original)',
      'detail.downloadArchive': 'Baixar arquivo',
      'detail.downloadStarted': 'Download Iniciado',
      'detail.galleryQueued': 'Download da galeria foi enfileirado',
      'detail.archiveQueued': 'Download do arquivo foi enfileirado',
      'detail.downloadFailed': 'Falha ao iniciar download: @error',
      'detail.archiveFailed': 'Falha ao iniciar download do arquivo: @error',
      'detail.loadArchiveInfoFailed':
          'Falha ao carregar informações do arquivo: @error',
      'detail.noArchive': 'Nenhum arquivo disponível',
      'detail.tags': 'Etiquetas',
      'detail.comments': 'Comentários (@count)',
      'detail.anonymous': 'Anônimo',
      'detail.loadFailed': 'Falha ao carregar detalhes da galeria: @error',

      // reader
      'reader.loading': 'Carregando galeria...',
      'reader.loadingGalleryMeta': 'Carregando lista de páginas...',
      'reader.resolvingFirstPages': 'Resolvendo páginas de imagem...',
      'reader.resolvingImagePage': 'Resolvendo página...',
      'reader.loadingImage': 'Carregando imagem...',
      'reader.loadFailed': 'Falha ao carregar galeria: @error',
      'reader.imageFailed': 'Falha ao carregar imagem',
      'reader.noImages': 'Nenhuma imagem fornecida',
      'reader.directionLabel': 'Direção de leitura: @dir',
      'reader.ltr': 'Esquerda→Direita',
      'reader.rtl': 'Direita→Esquerda',
      'reader.vertical': 'Rolagem vertical',
      'reader.wheelAction': 'Roda do mouse na imagem',
      'reader.wheelActionPage': 'Virar página',
      'reader.wheelActionZoom': 'Ampliar imagem',
      'reader.wheelActionVerticalHint':
          'Modos vertical e largura ajustada sempre rolam a lista. Esta opção vale para LTR, RTL e página dupla.',
      'reader.wheelInvertPageTurn': 'Inverter direção da roda (página)',
      'reader.wheelInvertPageTurnSubtitle':
          'Troca qual direção de rolagem da roda/trackpad vai para a próxima vs página anterior.',
      'reader.wheelScrollSpeed': 'Velocidade da roda',
      'reader.wheelScrollSpeedSubtitle':
          'Controla a velocidade da roda do mouse nos modos vertical e ajustar à largura.',

      // downloads
      'downloads.title': 'Baixados',
      'downloads.gallery': 'Galeria',
      'downloads.archive': 'Arquivo',
      'downloads.noGallery': 'Sem downloads de galeria',
      'downloads.noArchive': 'Sem downloads de arquivo',
      'downloads.read': 'Ler',
      'downloads.pause': 'Pausar',
      'downloads.resume': 'Retomar',
      'downloads.deleteTitle': 'Excluir Download',
      'downloads.deleteConfirm':
          'Escolha se deseja manter os arquivos baixados.',
      'downloads.loadFailed': 'Falha ao carregar tarefas: @error',
      'downloads.gStatus0': 'Nenhum',
      'downloads.gStatus1': 'Baixando',
      'downloads.gStatus2': 'Pausado',
      'downloads.gStatus3': 'Concluído',
      'downloads.gStatus4': 'Falhou',
      'downloads.aStatus0': 'Nenhum',
      'downloads.aStatus1': 'Desbloqueando',
      'downloads.aStatus2': 'Analisando URL',
      'downloads.aStatus3': 'Baixando',
      'downloads.aStatus4': 'Baixado',
      'downloads.aStatus5': 'Descompactando',
      'downloads.aStatus6': 'Concluído',
      'downloads.aStatus7': 'Pausado',
      'downloads.aStatus8': 'Falhou',

      // local
      'local.title': 'Galerias Locais',
      'local.noGalleries': 'Nenhuma galeria local encontrada',
      'local.helpText':
          'Monte diretórios no contêiner Docker\nou coloque galerias na pasta local_gallery',
      'local.scanNow': 'Escanear Agora',
      'local.empty': 'Vazio',
      'local.noImages': 'Nenhuma imagem encontrada nesta galeria',
      'local.loadFailed': 'Falha ao carregar imagens: @error',
      'local.loadListFailed': 'Falha ao carregar galerias locais: @error',
      'local.deleteTitle': 'Excluir Galeria Local',
      'local.deleteConfirm': 'Excluir arquivos locais de "@title"?',
      'local.deleteSuccess': 'Galeria local excluída',
      'local.deleteFailed': 'Falha ao excluir galeria local: @error',
      'local.parentDirectory': 'Pasta Pai',
      'local.copyPath': 'Copiar Caminho',

      // settings
      'settings.title': 'Configurações',
      'settings.account': 'Conta',
      'settings.loggedIn': 'Conectado como: @user',
      'settings.logout': 'Sair',
      'settings.logoutSuccess': 'Desconectado',
      'settings.logoutFailed': 'Falha ao sair: @error',
      'settings.cookieLogin': 'Login com cookies (recomendado)',
      'settings.cookieHint':
          'O login no fórum EH é bloqueado pelo Cloudflare em ambientes de servidor. '
              'Faça login pelo navegador e copie os cookies aqui.\n'
              'Passos: Login em e-hentai.org → F12 → Aplicação → Cookies → copie os valores abaixo.',
      'settings.cookiePlaceholder':
          'ipb_member_id=xxx; ipb_pass_hash=xxx; igneous=xxx',
      'settings.setCookies': 'Definir Cookies',
      'settings.cookieSuccess': 'Cookies definidos com sucesso',
      'settings.cookieFailed': 'Falha ao definir cookies: @error',
      'settings.cookieEmpty': 'Por favor, cole os cookies',
      'settings.showCookies': 'Mostrar Cookies',
      'settings.copyCookies': 'Copiar Cookies',
      'settings.copyKeyCookies': 'Copiar Cookies de Login',
      'settings.refreshIgneous': 'Atualizar igneous',
      'settings.refreshIgneousSuccess': 'igneous atualizado',
      'settings.refreshIgneousFailed': 'Falha ao atualizar igneous',
      'settings.refreshIgneousFailedWithError':
          'Falha ao atualizar igneous: @error',
      'settings.credentialLogin':
          'Login com credenciais (pode falhar devido ao Cloudflare)',
      'settings.username': 'Usuário',
      'settings.password': 'Senha',
      'settings.login': 'Entrar',
      'settings.loginSuccess': 'Login bem-sucedido',
      'settings.loginFailed': 'Falha no login',
      'settings.loginError': 'Falha no login: @error',
      'settings.emptyCredentials': 'Por favor, insira usuário e senha',
      'settings.site': 'Site',
      'redirect2Eh': 'Redirecionar para EH, se disponível',
      'redirect2EhHint':
          'Tenta carregar os detalhes da galeria pelo EH primeiro para melhor desempenho de rede.',
      'settings.appearance': 'Aparência',
      'settings.themeMode': 'Modo de Tema',
      'settings.system': 'Sistema',
      'settings.light': 'Claro',
      'settings.dark': 'Escuro',
      'settings.accentColor': 'Cor de Destaque',
      'settings.serverInfo': 'Informações do Servidor',
      'settings.dataDir': 'Diretório de Dados',
      'settings.downloadDir': 'Diretório de Downloads',
      'settings.localGalleryDir': 'Dir. Galerias Locais',
      'settings.extraScanPaths': 'Caminhos Extras de Scan',
      'settings.switchSiteFailed': 'Falha ao trocar site: @error',
      'settings.language': 'Idioma',
      'settings.sectionData': 'Dados e ferramentas',
      'settings.sectionStyle': 'Estilo',
      'settings.sectionRead': 'Leitura',
      'settings.sectionTags': 'Tags e filtros',
      'settings.sectionOther': 'Outros',
      'settings.openDownloads': 'Baixados',
      'settings.openHistory': 'Histórico',
      'settings.openLocal': 'Galerias locais',
      'settings.openQuickSearch': 'Busca rápida',
      'settings.networkNote': 'Rede e proxy',
      'settings.networkWebBody':
          'Proxy e rede avançada são configurados no servidor ou Docker. Esta página mostra o estado atual do proxy para EH/EX e imagens H@H.',
      'settings.about': 'Sobre',
      'settings.appVersion': 'Versão @version (@build)',
      'settings.hubMenu': 'Menu de configurações',
      'settings.menuWebDocker': 'Interface web e servidor',
      'settings.menuWebDockerSubtitle':
          'Atalho de downloads, caminhos Docker, rede/proxy, desempenho e segurança (somente Web).',
      'settings.menuEH': 'E-Hentai',
      'settings.menuStyle': 'Estilo',
      'settings.menuRead': 'Leitura',
      'settings.menuPreference': 'Preferências',
      'settings.menuNetwork': 'Rede',
      'settings.menuDownload': 'Baixados',
      'settings.menuPerformance': 'Desempenho',
      'settings.menuMouseWheel': 'Roda do mouse',
      'settings.menuAdvanced': 'Avançado',
      'settings.menuSecurity': 'Segurança',
      'settings.ehRequiresLogin':
          'Entre em Conta para alterar o site e o estado dos cookies.',
      'settings.ehMyTags': 'Minhas tags',
      'settings.ehMyTagsHint': 'Gerencie tags observadas e ocultas online',
      'settings.ehSiteSetting': 'Configurações do site',
      'settings.ehSiteSettingHint':
          'Abrir a página de configurações E-Hentai / ExHentai em uma nova aba',
      'settings.ehProfile': 'Configurações de perfil',
      'settings.ehSelectedProfile': 'Perfil selecionado',
      'settings.ehProfileHint':
          'Site atual: @site. Alterna o perfil ativo do site pelo cookie sp, igual ao app.',
      'settings.ehProfileEmpty': 'Nenhum perfil encontrado',
      'settings.ehProfileSaved': 'Perfil alterado',
      'settings.ehProfileSaveFailed': 'Falha ao alterar perfil: @error',
      'settings.ehProfileLoadFailed': 'Falha ao carregar perfis: @error',
      'settings.ehProfileAndQuota': 'Perfil, cota e recursos',
      'settings.ehProfileAndQuotaHint':
          'Esses valores ainda dependem da leitura das páginas do site. Por enquanto, veja-os nas configurações do site.',
      'settings.ehAssets': 'Recursos',
      'settings.ehImageQuota': 'Cota de imagens',
      'settings.ehResetCost': 'Custo para redefinir',
      'settings.ehQuotaUnavailable':
          'A cota de imagens está disponível apenas para doadores',
      'settings.ehQuotaReset': 'A cota de imagens foi redefinida',
      'settings.ehQuotaResetFailed':
          'Falha ao redefinir a cota de imagens: @error',
      'settings.ehStatusFailed': 'Falha ao carregar o status EH: @error',
      'settings.galleryListStyle': 'Estilo da lista de galerias',
      'pageListStyle': 'Estilo da lista de galerias (página)',
      'global': 'Global',
      'settings.listModeGrid': 'Grade',
      'settings.listModeList': 'Lista',
      'settings.listModeCompact': 'Compacta',
      'settings.gridColumns': 'Colunas da grade',
      'settings.gridColumnsAuto': 'Automático',
      'settings.detailThumbnailColumns': 'Colunas de miniaturas dos detalhes',
      'settings.detailThumbnailColumnsHint':
          'Aplica às miniaturas dos detalhes da galeria e à página completa de miniaturas.',
      'moveCover2RightSide': 'Mover capa para o lado direito',
      'settings.moveCoverWebHint':
          'Aplica às páginas largas de detalhes da galeria neste navegador.',
      'settings.galleryListStyleHint':
          'Aplica imediatamente à lista de galerias da página inicial web e fica salvo neste navegador.',
      'settings.pageListStyleHint':
          'Substitui o estilo da lista de galerias por seção web. Global usa o estilo acima.',
      'settings.networkWebSummary':
          'O estado do proxy aparece na página Rede. Reinicie o servidor após alterar variáveis de ambiente Docker.',
      'settings.proxyRouting': 'Roteamento de requisições',
      'settings.ehProxyRoute': 'Requisições de páginas EH/EX',
      'settings.hathProxyRoute': 'Requisições de imagens H@H',
      'settings.hathProxyDedicatedHint':
          'JH_HATH_PROXY está configurado, então *.hath.network usa esse proxy primeiro.',
      'settings.hathProxyFallbackHint':
          'JH_HATH_PROXY não está configurado, então *.hath.network usa HTTPS_PROXY/HTTP_PROXY. Defina JH_HATH_PROXY se H@H ainda falhar.',
      'settings.proxyEnvironment': 'Ambiente de proxy',
      'settings.proxyEnvironmentEmpty': 'Nenhum valor de proxy foi informado.',
      'settings.proxyEnvironmentHint':
          'Apenas protocolo, host e porta aparecem aqui. Credenciais ficam ocultas.',
      'settings.proxyAuthConfigured': 'autenticação configurada',
      'settings.networkRuntimeFlags': 'Diagnóstico de rede',
      'settings.networkRestartHint':
          'Esses valores vêm do ambiente de inicialização do servidor. Reinicie o contêiner após alterá-los.',
      'settings.directConnection': 'Direto',
      'settings.configured': 'Configurado',
      'settings.notConfigured': 'Não configurado',
      'settings.enabled': 'Ativado',
      'settings.disabled': 'Desativado',
      'settings.downloadWebSummary':
          'Defina grupos e prioridades padrão, revise caminhos e concorrência Docker, e gerencie tarefas de download.',
      'settings.downloadWebIntro':
          'Defina grupos e prioridades padrão usados pelos diálogos de download da web e revise as opções Docker do servidor.',
      'settings.downloadDefaults': 'Padrões de download',
      'settings.downloadDefaultsSaved': 'Padrões de download salvos',
      'settings.defaultGalleryDownload': 'Download de galeria',
      'settings.defaultArchiveDownload': 'Download de arquivo',
      'settings.customGroupName': 'Nome de grupo personalizado',
      'settings.downloadServerRuntime': 'Execução do servidor',
      'settings.galleryConcurrency': 'Concorrência de galerias',
      'settings.archiveConcurrency': 'Concorrência de arquivos',
      'settings.downloadRuntimeHint':
          'Concorrência e caminhos são controlados por variáveis de ambiente Docker e valem após reiniciar o servidor.',
      'settings.performanceWebSummary':
          'Ajuste o limite de animação da lista de downloads web para reduzir trabalho do navegador em grupos grandes.',
      'settings.webPerformance': 'Desempenho web',
      'settings.performanceWebIntro':
          'O cliente web roda no navegador. Estas opções locais afetam a fluidez de listas grandes.',
      'settings.webMaxGalleryNum4Animation':
          'Limite de animação de grupos de download',
      'settings.webMaxGalleryNum4AnimationHint':
          'Desativa a animação do ícone de expandir/recolher quando um grupo tem mais tarefas que este valor. Use 0 para desativar sempre.',
      'settings.resetPerformanceDefaults': 'Restaurar padrões de desempenho',
      'settings.performanceSaved': 'Configurações de desempenho salvas',
      'settings.advancedWebSummary':
          'Ative o modo sem imagens, revise caminhos Docker e gerencie logs do servidor.',
      'settings.advancedWebIntro':
          'Controle o carregamento de imagens, logs do servidor e caminhos Docker desta instância web.',
      'settings.exportData': 'Exportar dados',
      'settings.exportDataHint':
          'Baixe configurações, regras de bloqueio, histórico, histórico de busca e buscas rápidas como JSON. Tokens e cookies são excluídos.',
      'settings.exportDataSuccess': 'Exportação de dados baixada',
      'settings.exportDataFailed': 'Falha ao exportar dados: @error',
      'settings.importData': 'Importar dados',
      'settings.importDataHint':
          'Importe um JSON exportado pelo Web ou um JHenTaiConfig do app e mescle neste servidor. Configurações e itens nomeados são sobrescritos; regras de bloqueio são deduplicadas.',
      'settings.importDataTitle': 'Importar dados?',
      'settings.importDataConfirm':
          'Escolha uma exportação do JHenTai Web ou um arquivo JHenTaiConfig do app. Configurações importadas podem sobrescrever valores atuais.',
      'settings.importDataSuccess': '@count itens importados',
      'settings.importDataFailed': 'Falha ao importar dados: @error',
      'settings.noImageMode': 'Modo sem imagens',
      'settings.noImageModeHint':
          'Oculta capas, miniaturas e imagens do leitor neste navegador.',
      'settings.pageCache': 'Cache de páginas',
      'settings.clearPageCache': 'Limpar cache de páginas',
      'settings.clearPageCacheTitle': 'Limpar cache de páginas?',
      'settings.clearPageCacheConfirm':
          'Isso apagará respostas de páginas EH em cache no servidor.',
      'settings.clearPageCacheFailed':
          'Falha ao limpar cache de páginas: @error',
      'settings.loadPageCacheFailed':
          'Falha ao carregar cache de páginas: @error',
      'settings.pageCacheSummary': '@count páginas em cache · @size',
      'settings.serverLogs': 'Logs do servidor',
      'settings.clearLogsTitle': 'Limpar logs do servidor?',
      'settings.clearLogsConfirm':
          'Isso apagará todos os arquivos atuais de log do servidor.',
      'settings.clearLogsFailed': 'Falha ao limpar logs: @error',
      'settings.loadLogsFailed': 'Falha ao carregar logs: @error',
      'settings.loadLogFailed': 'Falha ao carregar log: @error',
      'settings.noLogs': 'Sem logs ainda',
      'settings.copyLog': 'Copiar log',
      'settings.downloadLog': 'Baixar log',
      'settings.emptyLog': 'Este log está vazio',
      'settings.securityWebSummary':
          'Verifique o token de API salvo neste navegador, valide a conexão ou desconecte e conecte novamente.',
      'settings.webTokenSecurity': 'Segurança da conexão web',
      'settings.webTokenSaved': 'Token local',
      'settings.webTokenSavedYes': 'Salvo neste navegador',
      'settings.webTokenSavedNo': 'Nenhum token salvo neste navegador',
      'settings.webTokenFingerprint': 'Identificador do token',
      'settings.webTokenVerifyStatus': 'Estado da verificação',
      'settings.webTokenValid': 'O token atual é válido',
      'settings.webTokenInvalid': 'O token atual é inválido ou foi trocado',
      'settings.securityWebBody':
          'A interface web conecta usando um token de API salvo neste navegador. O token completo nunca é exibido aqui; isto apenas verifica a conexão atual.',
      'settings.verifyCurrentToken': 'Verificar token atual',
      'settings.disconnectWebToken': 'Desconectar e reconectar',
      'settings.disconnectWebTokenTitle': 'Desconectar a conexão web atual?',
      'settings.disconnectWebTokenConfirm':
          'Isto remove o token de API salvo neste navegador e volta à configuração. O token do servidor não será excluído.',
      'settings.webTokenRotateHint':
          'Se você trocou o token no servidor, desconecte aqui primeiro e cole o novo token na configuração.',
      'settings.mouseWheelIntro':
          'Escolha o comportamento da roda do mouse sobre as imagens no leitor (modos de página horizontais).',
      'settings.mouseWheelReadHint': 'Direção, pré-carregamento e mais',
      'settings.aboutVersionLabel': 'Versão',
      'settings.aboutAuthorLabel': 'Autor',
      'settings.aboutTelegramTitle': 'Telegram (principalmente chinês)',
      'settings.aboutTelegramHint': 'Link da comunidade',
      'settings.aboutQA': 'Perguntas e respostas',
      'settings.aboutWebForkNote':
          'Esta UI web vem do fork JHenTai Docker; o projeto original está linkado acima.',

      // history
      'history.title': 'Histórico',
      'history.empty': 'Sem histórico de navegação',
      'history.clearAll': 'Limpar Tudo',
      'history.clearTitle': 'Limpar Histórico',
      'history.clearConfirm': 'Tem certeza que deseja limpar todo o histórico?',
      'history.loadFailed': 'Falha ao carregar histórico: @error',
      'history.loadMore': 'Carregar mais',

      // search history
      'searchHistory.clearAll': 'Limpar histórico de pesquisa',
      'searchHistory.translate': 'Traduzir histórico de pesquisa',

      // comment
      'comment.placeholder': 'Escreva um comentário...',
      'comment.send': 'Enviar',
      'comment.posted': 'Comentário Publicado',
      'comment.postedMsg': 'Seu comentário foi publicado',
      'comment.postFailed': 'Falha ao publicar comentário: @error',
      'comment.voteFailed': 'Falha ao votar: @error',
      'comment.scoreDetails': 'Detalhes da Pontuação',
      'comment.update': 'Atualizar Comentário',
      'comment.updated': 'Comentário Atualizado',
      'comment.updatedMsg': 'Seu comentário foi atualizado',
      'comment.updateFailed': 'Falha ao atualizar comentário: @error',
      'comment.tooShort': 'Comentário muito curto',
      'comment.atLeast3Characters': 'Pelo menos 3 caracteres',

      // ranklist
      'ranklist.title': 'Ranking',
      'ranklist.allTime': 'Todos os Tempos',
      'ranklist.year': 'Último Ano',
      'ranklist.month': 'Último Mês',
      'ranklist.yesterday': 'Ontem',

      // thumbnails
      'thumbnails.title': 'Miniaturas (@count)',
      'thumbnails.grid': 'Grade de Miniaturas',
      'thumbnails.jumpToPage': 'Ir para Página',
      'thumbnails.pageRange': 'Intervalo: 1 - @total',
      'thumbnails.loadFailed': 'Falha ao carregar miniaturas: @error',

      // tag translation
      'tagTranslation.title': 'Tradução de Tags',
      'tagTranslation.loaded': '@count tags carregadas',
      'tagTranslation.notLoaded': 'Banco de tags não carregado',
      'tagTranslation.lastUpdate': 'Última atualização: @time',
      'tagTranslation.refresh': 'Atualizar Banco de Tags',
      'tagTranslation.refreshSuccess': '@count tags atualizadas',
      'tagTranslation.refreshFailed': 'Falha ao atualizar: @error',

      // list mode
      'listMode.toggle': 'Alternar modo de visualização',
      'listMode.grid': 'Grade',
      'listMode.list': 'Lista',
      'listMode.listCompact': 'Lista Compacta',

      // quick search
      'quickSearch.title': 'Pesquisa Rápida',
      'quickSearch.empty': 'Nenhuma pesquisa salva',
      'quickSearch.saveCurrent': 'Salvar pesquisa atual',
      'quickSearch.saveTitle': 'Salvar Pesquisa Rápida',
      'quickSearch.editTitle': 'Editar Pesquisa Rápida',
      'quickSearch.nameLabel': 'Nome',
      'quickSearch.addNew': 'Adicionar busca rápida',
      'quickSearch.keywordLabel': 'Palavra-chave',
      'quickSearch.keywordHint': 'Igual à barra de busca da página inicial',
      'quickSearch.saved': 'Salvo',
      'quickSearch.deleted': 'Excluído',
      'quickSearch.deleteTitle': 'Excluir busca rápida',
      'quickSearch.deleteConfirm': 'Remover "@name"?',

      // tag suggest
      'tagSuggest.tag': 'Etiqueta',

      // common extras
      'common.save': 'Salvar',

      // reader enhancements
      'reader.fitWidth': 'Ajustar Largura',
      'reader.doubleColumn': 'Duas Colunas',
      'reader.autoStart': 'Leitura Automática',
      'reader.autoStop': 'Parar Leitura Automática',

      'enableBottomMenu': 'Ativar menu inferior',

      'enablePageTurnAnime': 'Ativar animação de virar página',
      'enableDoubleTapToScaleUp': 'Ativar zoom com toque duplo',
      'enableTapDragToScaleUp': 'Ativar zoom ao tocar e arrastar',
      'reverseTurnPageDirection': 'Inverter direção ao tocar para virar página',
      'disablePageTurningOnTap': 'Desativar toque para virar página',
      // block rules
      'blockRule.title': 'Regras de Bloqueio',
      'blockRule.empty': 'Nenhuma regra de bloqueio configurada',
      'blockRule.add': 'Adicionar Regra',
      'blockRule.edit': 'Editar Regra',
      'blockRule.manage': 'Gerenciar Regras de Bloqueio',
      'useBuiltInBlockedUsers': 'Ativar lista interna de usuários bloqueados',
      'useBuiltInBlockedUsersHint':
          'Filtra comentários de usuários presentes na lista interna',
      'blockRule.ruleCount': '@count regras',
      'blockRule.ungrouped': 'Sem grupo',
      'blockRule.deleteGroup': 'Excluir Grupo',
      'blockRule.target': 'Alvo',
      'blockRule.attribute': 'Atributo',
      'blockRule.pattern': 'Padrão',
      'blockRule.expression': 'Expressão',
      'blockRule.expressionHint': 'Valor para comparar',
      'blockRule.groupId': 'ID do Grupo',
      'blockRule.groupIdHint': 'Nome do grupo opcional',
      'blockRule.blocked': 'Bloqueado',
      'blockRule.tagBlocked': 'Tag "@tag" foi bloqueada',
      'blockRule.uploaderBlocked': 'Uploader "@uploader" foi bloqueado',
      'blockRule.blockTag': 'Bloquear esta tag',
      'blockRule.blockUploader': 'Bloquear este uploader',
      'blockRule.blockCommentUser': 'Bloquear usuário do comentário',
      'blockRule.blockCommentUserConfirm':
          'Bloquear usuário do comentário "@user"?',
      'blockRule.commentUserBlocked':
          'Usuário do comentário "@user" foi bloqueado',

      // download enhancements
      'simpleSearch': 'Simples',
      'regexSearch': 'Regex',
      'downloads.search': 'Pesquisar downloads...',
      'downloads.allGroups': 'Todos os Grupos',
      'downloads.group': 'Grupo',

      // tag voting
      'tagVote.search': 'Pesquisar',
      'tagVote.searchUploader': 'Pesquisar uploader',
      'tagVote.voteUp': 'Votar Positivo',
      'tagVote.voteDown': 'Votar Negativo',
      'tagVote.success': 'Votado',
      'tagVote.votedUp': 'Votou positivo para "@tag"',
      'tagVote.votedDown': 'Votou negativo para "@tag"',
      'tagVote.failed': 'Falha ao votar: @error',
      'tagVote.addTag': 'Adicionar Tag',
      'tagVote.addTagHint': 'Insira novas tags, separadas por vírgulas',
      'tagVote.addSuccess': 'Tag adicionada',
      'tagVote.addFailed': 'Falha ao adicionar tag: @error',

      // responsive layout
      'home.selectGallery': 'Selecione uma galeria para ver detalhes',

      // gallery detail extras
      'detail.parentGallery': 'Galeria Pai',
      'detail.newerVersion': 'Versão Mais Nova Disponível',
      'detail.versionHistory': 'Histórico de Versões',
      'detail.currentVersion': 'Versão Atual',
      'detail.torrents': 'Torrents',
      'detail.torrentCount': 'Torrent (@count)',
      'detail.noTorrents': 'Sem torrents',
      'detail.outdatedTorrents': 'Desatualizados',
      'detail.downloadTorrent': 'Baixar torrent',
      'detail.copyMagnet': 'Copiar magnet',
      'detail.torrentSeeds': 'Seeds @count',
      'detail.torrentPeers': 'Peers @count',
      'detail.torrentDownloads': 'Baixados @count',
      'detail.loadTorrentsFailed': 'Falha ao carregar torrents: @error',
      'detail.hhDownload': 'Download H@H',
      'detail.noHHArchives': 'Nenhum arquivo H@H disponível',
      'detail.loadHHFailed': 'Falha ao carregar arquivos H@H: @error',
      'detail.hhSubmitFailed': 'Falha ao solicitar download H@H: @error',
      'detail.hhSubmitted': 'Solicitação de download H@H enviada',

      // settings extras
      'settings.cookieStatusFull': 'Cookies OK (inclui igneous — EX pronto)',
      'settings.cookieStatusNoIgneous':
          'Cookies definidos mas falta igneous — EX pode não funcionar',
      'settings.cookieStatusNone': 'Nenhum cookie de login definido',
      'settings.siteSwitched': 'Alterado para @site',

      // download progress in detail
      'detail.completed': 'Concluído',
      'detail.retryDownload': 'Tentar novamente',
      'detail.readDownloaded': 'Ler baixado',
      'detail.deleteDownload': 'Excluir download',
      'detail.deleteDownloadConfirm': 'Excluir este download e seus arquivos?',
      'detail.archiveCompleted': 'Arquivo pronto',

      // detail enhancements
      'detail.share': 'Compartilhar',
      'detail.jumpToPage': 'Ir para Página',
      'detail.jumpToThumbnail': 'Ir para miniatura',
      'detail.similarSearch': 'Pesquisa Similar',
      'detail.blockGallery': 'Bloquear Galeria',
      'detail.allComments': 'Todos os Comentários',
      'detail.thumbnails': 'Miniaturas (@count)',
      'detail.viewAllThumbnails': 'Ver Todas as Miniaturas',
      'detail.galleryBlocked': 'Galeria foi bloqueada',
      'detail.jumpPageHint': 'Insira o número da página (1-@max)',

      // reader enhancements
      'reader.saveImage': 'Salvar Imagem',
      'reader.openInNewTab': 'Abrir em Nova Aba',
      'reader.reloadImage': 'Recarregar Imagem',
      'reader.interval': 'Intervalo',
      'reader.preload': 'Pré-carregar',
      'reader.imageSpacing': 'Espaçamento de Imagem',
      'reader.autoInterval': 'Intervalo Auto-leitura',
      'reader.startAutoMode': 'Iniciar',
      'reader.saveFailed': 'Não foi possível salvar a imagem',
      'reader.redownloadHint':
          'Abra Downloads para tentar novamente ou reiniciar o download desta galeria.',
      'reader.deviceOrientation': 'Orientação do dispositivo',
      'reader.deviceOrientationWebHint':
          'O navegador não pode fixar a orientação como o app. Use tela cheia ou o bloqueio de rotação do sistema.',

      // settings reader
      'settings.defaultFavoriteSlot': 'Pasta de favoritos padrão',
      'settings.defaultFavoriteNone': 'Nenhuma (perguntar sempre)',
      'settings.defaultFavoriteHint':
          'Quando ativado, clique no coração para usar a pasta padrão e pressione e segure para escolher outra.',
      'settings.readerSettings': 'Configurações do Leitor',
      'settings.defaultDirection': 'Direção Padrão',
      'settings.imageSpacing': 'Espaçamento de Imagem',
      'settings.preloadPages': 'Páginas Pré-carregadas (Online)',
      'settings.preloadPagesLocal': 'Páginas Pré-carregadas (Local)',
      'settings.autoInterval': 'Intervalo Auto-leitura',
      'settings.fitWidth': 'Ajustar Largura',
      'hideScroll2TopButton': 'Botão voltar ao topo',
      'whenScrollUp': 'Ao rolar para cima',
      'whenScrollDown': 'Ao rolar para baixo',
      'never': 'Nunca',
      'always': 'Sempre',
      'preloadGalleryCover': 'Pré-carregar capas das galerias',
      'preloadGalleryCoverHint':
          'Pré-carrega capas de galerias que ainda não estão na tela',
      'simpleDashboardMode': 'Simple Home Page',
      'simpleDashboardModeHint': 'Hide Ranklist and Popular',
      'showDawnInfo': 'Mostrar evento de amanhecer',
      'showEncounterMonster': 'Mostrar encontro do HentaiVerse',

      // home enhancements
      'home.scrollToTop': 'Voltar ao Topo',
      'home.imageSearch': 'Pesquisar por imagem',
      'home.imageSearchFailed': 'Falha na pesquisa por imagem: @error',
      'home.imageSearchMode': 'Resultados da pesquisa por imagem',
      'stats.title': 'Estatísticas de visitas',
      'stats.totalVisits': 'Total de visitas: @n',
      'stats.allTime': 'Todo o período',
      'stats.year': 'Ano',
      'stats.month': 'Mês',
      'stats.day': 'Dia',
      'stats.period': 'Período',
      'stats.ranking': 'Classificação',
      'stats.score': 'Pontuação',
      'stats.visits': 'Visitas',
      'stats.hits': 'Acessos',
      'stats.noSeries': 'Sem dados para o gráfico',
      'usertags.title': 'Tags observadas / ocultas',
      'usertags.loadFailed': 'Falha ao carregar: @error',
      'usertags.add': 'Adicionar tag',
      'usertags.tagHint': 'Formato namespace:key',
      'usertags.watch': 'Observar',
      'usertags.hidden': 'Oculta',
      'usertags.watchAdded': 'Tag adicionada às observadas',
      'usertags.hiddenAdded': 'Tag adicionada às ocultas',
      'usertags.defaultTagSet': 'Conjunto de tags padrão',
      'usertags.defaultTagSetNone': 'Nenhum (perguntar sempre)',
      'usertags.none': 'Nenhum',
      'usertags.weight': 'Peso',
      'usertags.editTitle': 'Editar tag',
      'usertags.delete': 'Excluir',
      'usertags.added': 'Adicionada',
      'usertags.updated': 'Atualizada',
      'usertags.deleted': 'Excluída',
      'usertags.currentList': 'Tags configuradas',
      'enableDefaultTagSet': 'Ativar conjunto de tags padrão',
      'enableDefaultTagSetHint': 'Usar diretamente o conjunto de tags padrão',
      'disableDefaultTagSetHint': 'Selecionar manualmente',
      'chooseTagSet': 'Escolher conjunto de tags',
      'asYourDefault': 'Como padrão',
      'downloads.sortBy': 'Ordenar',
      'downloads.sortPriority': 'Prioridade',
      'downloads.sortTime': 'Tempo',
      'downloads.sortTitle': 'Título',
      'downloads.sortStatus': 'Estado',
      'downloads.allCategories': 'Todas as categorias',
      'downloads.categoryFilter': 'Categoria EH',
      'downloads.setPriority': 'Prioridade',
      'downloads.setGroup': 'Grupo',
      'downloads.priorityLabel': 'Prioridade @n',
      'downloads.groupLabel': 'Grupo',
      'downloads.groupActions': 'Acoes do grupo',
      'downloads.renameGroup': 'Renomear grupo',
      'downloads.renameGroupConfirm': 'Renomear o grupo "@group" para:',
      'downloads.groupRenamed': 'Grupo renomeado para @count tarefas',
      'downloads.clearGroup': 'Limpar grupo',
      'downloads.clearGroupConfirm':
          'Mover @count tarefas em "@group" de volta para default?',
      'downloads.groupCleared': '@count tarefas movidas de volta para default',
      'downloads.superseded': 'Atualizada para gid @gid',
      'downloads.editTask': 'Editar tarefa',
      'downloads.pauseVisible': 'Pausar tarefas visíveis',
      'downloads.resumeVisible': 'Retomar tarefas visíveis',
      'downloads.reDownloadVisible': 'Baixar novamente galerias visíveis',
      'downloads.reDownloadConfirm':
          'Excluir os arquivos baixados desta galeria e iniciar novamente?',
      'downloads.reDownloadVisibleConfirm':
          'Excluir arquivos e reiniciar @count galerias visíveis?',
      'downloads.reUnlockArchive': 'Desbloquear arquivo novamente',
      'downloads.reUnlockArchiveConfirm':
          'Limpar o link de download do arquivo e desbloquear novamente?',
      'downloads.changeVisibleGroup': 'Alterar grupo das tarefas visíveis',
      'downloads.changeVisibleGroupConfirm':
          'Mover @count tarefas visíveis para este grupo.',
      'downloads.deleteVisible': 'Excluir tarefas visíveis',
      'downloads.deleteVisibleConfirm':
          'Escolha como excluir @count tarefas visíveis.',
      'downloads.noBatchTargets': 'Nenhuma tarefa compatível na lista atual',
      'downloads.batchPaused': '@count tarefas pausadas',
      'downloads.batchResumed': '@count tarefas retomadas',
      'downloads.batchRedownloaded': '@count tarefas reiniciadas',
      'downloads.batchGroupChanged': 'Grupo alterado para @count tarefas',
      'downloads.batchDeleted': '@count tarefas excluídas',
      'detail.startDownloadTitle': 'Iniciar download',
      'detail.downloadGroup': 'Grupo',
      'existingGroup': 'Grupo existente',
      'groupName': 'Nome do grupo',
      'detail.downloadPriority': 'Prioridade (maior executa primeiro)',
      'detail.stats': 'Estatísticas',
      'detail.similarByTitle': 'Título similar',
      'detail.upgradeDownload': 'Atualizar para nova versão',
      'detail.upgradeOk': 'Download da nova versão iniciado',
      'detail.upgradeFailed': 'Falha ao atualizar: @error',
      'detail.archiveNewVersionHint':
          'Existe uma versão mais nova da galeria. Baixe o arquivo pela página da nova galeria.',
      'detail.openNewVersion': 'Abrir nova versão',
      'settings.usertags': 'Tags observadas / ocultas',
    };
  }
}
