class WebPtBR {
  static Map<String, String> keys() {
    return {
      // common
      'common.cancel': 'Cancelar',
      'common.ok': 'OK',
      'common.error': 'Erro',
      'common.success': 'Sucesso',
      'common.failed': 'Falhou',
      'common.retry': 'Tentar novamente',
      'common.delete': 'Excluir',
      'common.reset': 'Redefinir',
      'common.unknown': 'Desconhecido',
      'common.images': '@count imagens',
      'common.pages': '@count páginas',

      // setup
      'setup.title': 'Configuração do Servidor JHenTai',
      'setup.description': 'Insira o token API mostrado nos logs do servidor para conectar.',
      'setup.tokenLabel': 'Token API',
      'setup.connect': 'Conectar',
      'setup.emptyToken': 'Por favor, insira um token',
      'setup.invalidToken': 'Token inválido. Verifique os logs do servidor para o token correto.',

      // home
      'home.title': 'JHenTai',
      'home.search': 'Pesquisar galerias...',
      'home.advancedSearch': 'Pesquisa avançada',
      'home.downloads': 'Downloads',
      'home.localGalleries': 'Galerias Locais',
      'home.settings': 'Configurações',
      'home.subtitle': 'Cliente E-Hentai',
      'home.home': 'Início',
      'home.popular': 'Popular',
      'home.favorites': 'Favoritos',
      'home.watched': 'Acompanhados',
      'home.noGalleries': 'Nenhuma galeria encontrada',
      'home.previous': 'Anterior',
      'home.next': 'Próximo',
      'home.page': 'Página @page',
      'home.loadFailed': 'Falha ao carregar: @error',
      'home.categoryFilter': 'Filtro de Categoria',
      'home.minimumRating': 'Avaliação Mínima',
      'home.ratingAny': 'Qualquer',
      'home.searchIn': 'Pesquisar em',
      'home.galleryName': 'Nome da Galeria',
      'home.tags': 'Tags',
      'home.description': 'Descrição',
      'home.showExpunged': 'Mostrar Excluídos',
      'home.applySearch': 'Aplicar e Pesquisar',
      'home.history': 'Histórico',
      'home.ranklist': 'Ranking',

      // category names
      'category.doujinshi': 'Doujinshi',
      'category.manga': 'Manga',
      'category.artistCg': 'CG de Artista',
      'category.gameCg': 'CG de Jogo',
      'category.western': 'Ocidental',
      'category.nonH': 'Non-H',
      'category.imageSet': 'Conjunto de Imagens',
      'category.cosplay': 'Cosplay',
      'category.asianPorn': 'Asiático',
      'category.misc': 'Diversos',

      // gallery detail
      'detail.copyUrl': 'Copiar URL da galeria',
      'detail.copied': 'Copiado',
      'detail.removeFromFav': 'Remover dos favoritos',
      'detail.addToFav': 'Adicionar aos favoritos',
      'detail.addToFavTitle': 'Adicionar aos favoritos',
      'detail.favRemoved': 'Removido',
      'detail.favRemovedMsg': 'Removido dos favoritos',
      'detail.favAdded': 'Adicionado',
      'detail.favAddedMsg': 'Adicionado a @name',
      'detail.favError': 'Operação de favoritos falhou: @error',
      'detail.favSlot': 'Favoritos @n',
      'detail.rateTitle': 'Avaliar esta galeria',
      'detail.rateSubmit': 'Enviar',
      'detail.rated': 'Avaliado',
      'detail.ratedMsg': 'Sua avaliação: @rating',
      'detail.rateFailed': 'Falha na avaliação: @error',
      'detail.rateLoginRequired': 'Não é possível avaliar — login necessário',
      'detail.readOnline': 'Ler Online',
      'detail.downloadGallery': 'Baixar Galeria',
      'detail.archiveResample': 'Arquivo (Comprimido)',
      'detail.archiveOriginal': 'Arquivo (Original)',
      'detail.downloadStarted': 'Download Iniciado',
      'detail.galleryQueued': 'Download da galeria foi enfileirado',
      'detail.archiveQueued': 'Download do arquivo foi enfileirado',
      'detail.downloadFailed': 'Falha ao iniciar download: @error',
      'detail.archiveFailed': 'Falha ao iniciar download do arquivo: @error',
      'detail.noArchive': 'Nenhum arquivo disponível',
      'detail.tags': 'Tags',
      'detail.comments': 'Comentários (@count)',
      'detail.anonymous': 'Anônimo',
      'detail.loadFailed': 'Falha ao carregar detalhes da galeria: @error',

      // reader
      'reader.loading': 'Carregando galeria...',
      'reader.loadingImage': 'Carregando imagem...',
      'reader.loadFailed': 'Falha ao carregar galeria: @error',
      'reader.imageFailed': 'Falha ao carregar imagem',
      'reader.noImages': 'Nenhuma imagem fornecida',
      'reader.directionLabel': 'Direção de leitura: @dir',
      'reader.ltr': 'Esquerda→Direita',
      'reader.rtl': 'Direita→Esquerda',
      'reader.vertical': 'Vertical',

      // downloads
      'downloads.title': 'Downloads',
      'downloads.gallery': 'Galeria',
      'downloads.archive': 'Arquivo',
      'downloads.noGallery': 'Sem downloads de galeria',
      'downloads.noArchive': 'Sem downloads de arquivo',
      'downloads.read': 'Ler',
      'downloads.pause': 'Pausar',
      'downloads.resume': 'Retomar',
      'downloads.deleteTitle': 'Excluir Download',
      'downloads.deleteConfirm': 'Excluir este download e seus arquivos?',
      'downloads.loadFailed': 'Falha ao carregar tarefas: @error',
      'downloads.gStatus0': 'Nenhum',
      'downloads.gStatus1': 'Baixando',
      'downloads.gStatus2': 'Pausado',
      'downloads.gStatus3': 'Concluído',
      'downloads.gStatus4': 'Falhou',
      'downloads.aStatus0': 'Nenhum',
      'downloads.aStatus1': 'Desbloqueando',
      'downloads.aStatus2': 'Analisando URL',
      'downloads.aStatus3': 'Baixando',
      'downloads.aStatus4': 'Baixado',
      'downloads.aStatus5': 'Descompactando',
      'downloads.aStatus6': 'Concluído',
      'downloads.aStatus7': 'Pausado',
      'downloads.aStatus8': 'Falhou',

      // local
      'local.title': 'Galerias Locais',
      'local.noGalleries': 'Nenhuma galeria local encontrada',
      'local.helpText': 'Monte diretórios no contêiner Docker\nou coloque galerias na pasta local_gallery',
      'local.scanNow': 'Escanear Agora',
      'local.empty': 'Vazio',
      'local.noImages': 'Nenhuma imagem encontrada nesta galeria',
      'local.loadFailed': 'Falha ao carregar imagens: @error',
      'local.loadListFailed': 'Falha ao carregar galerias locais: @error',

      // settings
      'settings.title': 'Configurações',
      'settings.account': 'Conta',
      'settings.loggedIn': 'Conectado como: @user',
      'settings.logout': 'Sair',
      'settings.logoutSuccess': 'Desconectado',
      'settings.logoutFailed': 'Falha ao sair: @error',
      'settings.cookieLogin': 'Login com cookies (recomendado)',
      'settings.cookieHint': 'O login no fórum EH é bloqueado pelo Cloudflare em ambientes de servidor. '
          'Faça login pelo navegador e copie os cookies aqui.\n'
          'Passos: Login em e-hentai.org → F12 → Aplicação → Cookies → copie os valores abaixo.',
      'settings.cookiePlaceholder': 'ipb_member_id=xxx; ipb_pass_hash=xxx; igneous=xxx',
      'settings.setCookies': 'Definir Cookies',
      'settings.cookieSuccess': 'Cookies definidos com sucesso',
      'settings.cookieFailed': 'Falha ao definir cookies: @error',
      'settings.cookieEmpty': 'Por favor, cole os cookies',
      'settings.credentialLogin': 'Login com credenciais (pode falhar devido ao Cloudflare)',
      'settings.username': 'Usuário',
      'settings.password': 'Senha',
      'settings.login': 'Entrar',
      'settings.loginSuccess': 'Login bem-sucedido',
      'settings.loginFailed': 'Falha no login',
      'settings.loginError': 'Falha no login: @error',
      'settings.emptyCredentials': 'Por favor, insira usuário e senha',
      'settings.site': 'Site',
      'settings.appearance': 'Aparência',
      'settings.themeMode': 'Modo de Tema',
      'settings.system': 'Sistema',
      'settings.light': 'Claro',
      'settings.dark': 'Escuro',
      'settings.accentColor': 'Cor de Destaque',
      'settings.serverInfo': 'Informações do Servidor',
      'settings.dataDir': 'Diretório de Dados',
      'settings.downloadDir': 'Diretório de Downloads',
      'settings.localGalleryDir': 'Dir. Galerias Locais',
      'settings.extraScanPaths': 'Caminhos Extras de Scan',
      'settings.switchSiteFailed': 'Falha ao trocar site: @error',
      'settings.language': 'Idioma',

      // history
      'history.title': 'Histórico',
      'history.empty': 'Sem histórico de navegação',
      'history.clearAll': 'Limpar Tudo',
      'history.clearTitle': 'Limpar Histórico',
      'history.clearConfirm': 'Tem certeza que deseja limpar todo o histórico?',
      'history.loadFailed': 'Falha ao carregar histórico: @error',

      // search history
      'searchHistory.clearAll': 'Limpar histórico de pesquisa',

      // comment
      'comment.placeholder': 'Escreva um comentário...',
      'comment.send': 'Enviar',
      'comment.posted': 'Comentário Publicado',
      'comment.postedMsg': 'Seu comentário foi publicado',
      'comment.postFailed': 'Falha ao publicar comentário: @error',
      'comment.voteFailed': 'Falha ao votar: @error',

      // ranklist
      'ranklist.title': 'Ranking',
      'ranklist.allTime': 'Todos os Tempos',
      'ranklist.year': 'Último Ano',
      'ranklist.month': 'Último Mês',
      'ranklist.yesterday': 'Ontem',

      // thumbnails
      'thumbnails.title': 'Miniaturas (@count)',
      'thumbnails.grid': 'Grade de Miniaturas',
      'thumbnails.loadFailed': 'Falha ao carregar miniaturas: @error',

      // tag translation
      'tagTranslation.title': 'Tradução de Tags',
      'tagTranslation.loaded': '@count tags carregadas',
      'tagTranslation.notLoaded': 'Banco de tags não carregado',
      'tagTranslation.lastUpdate': 'Última atualização: @time',
      'tagTranslation.refresh': 'Atualizar Banco de Tags',
      'tagTranslation.refreshSuccess': '@count tags atualizadas',
      'tagTranslation.refreshFailed': 'Falha ao atualizar: @error',

      // list mode
      'listMode.toggle': 'Alternar modo de visualização',
      'listMode.grid': 'Grade',
      'listMode.list': 'Lista',
      'listMode.listCompact': 'Lista Compacta',

      // quick search
      'quickSearch.title': 'Pesquisa Rápida',
      'quickSearch.empty': 'Nenhuma pesquisa salva',
      'quickSearch.saveCurrent': 'Salvar pesquisa atual',
      'quickSearch.saveTitle': 'Salvar Pesquisa Rápida',
      'quickSearch.nameLabel': 'Nome',

      // tag suggest
      'tagSuggest.tag': 'Tag',
    };
  }
}
