class WebZhCN {
  static Map<String, String> keys() {
    return {
      // common
      'common.cancel': '取消',
      'common.ok': '确定',
      'common.confirm': '确定',
      'common.error': '错误',
      'common.success': '成功',
      'common.failed': '失败',
      'common.retry': '重试',
      'common.add': '添加',
      'common.delete': '删除',
      'common.reset': '重置',
      'common.clear': '清除',
      'preset': '预设',
      'custom': '自定义',
      'common.refresh': '刷新',
      'common.loading': '加载中...',
      'common.unknown': '未知',
      'common.images': '@count 张图片',
      'common.pages': '@count 页',
      'common.open': '打开',
      'common.close': '关闭',
      'common.yes': '是',
      'common.no': '否',
      'common.visible': '可见',
      'common.notVisible': '不可见',
      'common.warning': '警告',
      'common.update': '更新',
      'common.download': '下载',
      'superResolution.title': '图片超分辨率',
      'superResolution.summary': '检测 GPU/Vulkan、下载模型，并管理 Docker 超分任务。',
      'superResolution.capability': '运行环境自检',
      'superResolution.arch': '架构',
      'superResolution.gpu': 'GPU/Vulkan',
      'superResolution.safetyHint':
          '超分会长时间占用 GPU/CPU 并显著增加磁盘占用；Docker 默认按 GPU 优先策略运行，CPU-only 仅适合少量实验。',
      'superResolution.models': '模型',
      'superResolution.modelGroupBasic': '基础推荐',
      'superResolution.modelGroupAdvanced': '高级/实验',
      'superResolution.installed': '已安装',
      'superResolution.notInstalled': '未安装',
      'superResolution.modelReady': '模型已准备好',
      'superResolution.modelDownloadStarted': '已开始下载模型',
      'superResolution.modelDownloading': '正在下载 @progress%',
      'superResolution.modelImporting': '正在导入模型包',
      'superResolution.modelDownloadFailed': '模型下载失败',
      'superResolution.installedNotExecutable': '已安装，但二进制文件不可执行',
      'superResolution.modelSource': '下载源：@source',
      'superResolution.repairPermission': '修复权限',
      'superResolution.modelPermissionRepaired': '模型执行权限已修复',
      'superResolution.importModel': '导入 ZIP',
      'superResolution.jobs': '任务',
      'superResolution.noJobs': '暂无超分任务',
      'superResolution.deleteHint': '删除任务并清理已生成的超分图片？',
      'superResolution.start': '图片超分',
      'superResolution.model': '模型',
      'superResolution.tileSize': 'Tile 大小',
      'superResolution.gpuAutoHint': '留空自动选择',
      'superResolution.cpuOnly': 'CPU-only 实验模式',
      'superResolution.cpuOnlyHint': '仅在没有 GPU 且确认 NAS 负载风险时开启。',
      'superResolution.noGpuWarning': '未检测到 GPU/Vulkan，默认不建议创建超分任务。',
      'superResolution.warningUbuntuAmd64Only':
          '当前官方 Ubuntu 包在此处仅按 amd64 处理；该架构需要提供自定义二进制文件。',
      'superResolution.warningNoGpuCpuDisabled':
          '未检测到 Vulkan/GPU 设备；CPU-only 模式仍属实验功能，默认已禁用。',
      'superResolution.modelMissingHint': '当前模型尚未安装，请先到图片超分辨率页面下载模型。',
      'superResolution.jobCreated': '超分任务已创建',
      'superResolution.useOutput': '使用超分图片',
      'superResolution.noOutputHint': '当前画廊还没有完整可用的超分输出。',
      'superResolution.autoAfterDownload': '下载完成后自动超分',
      'superResolution.autoAfterDownloadHint':
          '开启后，gallery 下载完成或 archive 解压完成时会自动创建超分任务；任务进入现有单并发队列，不影响下载完成状态。',
      'superResolution.autoEnabled': '自动创建超分任务',
      'superResolution.autoEnabledHint':
          '默认关闭，避免 NAS 在下载完成后无意触发长时间 GPU/CPU 负载。',
      'superResolution.allowCpuOnlyAuto': '自动任务允许 CPU-only',
      'superResolution.allowCpuOnlyAutoHint':
          '没有 GPU/Vulkan 时仍允许创建自动任务，仅适合少量实验。',
      'superResolution.autoSettingsSaved': '自动超分设置已保存',
      'localizedReason': '请验证以继续',
      'passwordErrorHint': '密码错误，请重试',
      'dawnOfaNewDay': '黎明之时',
      'encounterMonster': '你遭遇了一只怪兽！',
      'encounterMonsterHint': '点击跳转至 HentaiVerse 战斗。',

      'share': '分享',
      'save': '保存',
      'reload': '重新加载',
      'cancel': '取消',
      'resampleImage': '压缩图',
      'originalImage': '原图',
      'downloadOriginalImage': '下载原图',
      'downloadOriginalImageByDefault': '默认选中下载原图',
      'downloadAllGallerysOfSamePriority': '同一优先级下同时下载所有画廊',
      'downloadAllGallerysOfSamePriorityHint':
          '默认情况下逐优先级下载画廊，且每个优先级下只会同时下载一个画廊',
      'useJH2UpdateGallery': '使用 JH 服务器加速画廊更新',
      'deleteArchiveFileAfterDownload': '归档下载完成后删除原压缩包',
      'settings.deleteArchiveZipAfterDownloadHint':
          '开启后 Docker 服务端会在解压完成后删除下载的 ZIP；关闭则保留原压缩包。',
      'restoreDownloadTasks': '恢复下载任务',
      'restoreDownloadTasksHint': '通过下载元数据来恢复下载记录',
      'restoreTasksAutomatically': '自动恢复下载任务',
      'restoreTasksAutomaticallyHint': '服务端启动时通过下载元数据自动恢复任务',
      'home.pasteAndSearch': '粘贴并搜索或打开',
      'home.clipboardEmpty': '剪贴板为空',
      'home.clipboardReadFailed': '无法读取剪贴板，请允许剪贴板权限后重试。',
      'galleryUrlDetected': '剪贴板里发现画廊链接',
      'galleryUrlDetectedHint': '打开检测到的链接',
      'restoredGalleryCount': '已恢复画廊',
      'restoredArchiveCount': '已恢复归档',
      'reDownload': '重新下载',
      'deleteTask': '仅删除任务',
      'deleteTaskAndImages': '删除任务和图片',
      'hasCopiedToClipboard': '已复制到剪贴板',
      'search': '搜索',
      'all': '全部',
      'download': '下载',
      'import': '导入',
      'delete': '删除',
      'deleteSuccess': '已删除',
      'serverCondition': '服务器状态',
      'copyShareCode': '复制分享码',
      'readIndexRecord': '阅读进度',
      'quickSearch': '快速搜索',
      'blockingRules': '屏蔽规则',
      'searchHistory': '搜索历史',
      'galleryHistory': '画廊浏览历史',
      'autoModeStyle': '自动模式风格',
      'scroll': '连续滚动',
      'turnPage': '依次翻页',
      'turnPageMode': '翻页模式',
      'turnPageModeHint': '移动至下一屏幕还是下一图片',
      'image': '图片',
      'screen': '屏幕',
      'adaptive': '自适应',
      'displayFirstPageAlone': '单独展示首页',
      'showThumbnails': '显示缩略图',
      'showScrollBar': '显示滚动条',
      'showStatusInfo': '底部显示状态信息',
      'keepScreenAwakeWhenReading': '阅读时屏幕不自动锁定',
      'enableCustomReadBrightness': '阅读页自定义亮度',
      'customBrightness': '亮度',
      'webCustomReadBrightnessHint': '使用网页遮罩调暗阅读器，不会修改设备系统亮度。',
      'gestureRegionWidthRatio': '菜单手势区域宽度比例',
      'imageRegionWidthRatio': '图片区域宽度比例',
      'spaceBetweenImages': '图片间隔',
      'defaultTab': '启动时默认菜单',
      'enablePasswordAuth': '开启密码认证',
      'enableAuthOnResume': '切换至后台后重新认证',
      'enableAuthOnResumeHints': '切至后台超过 3 秒后重新锁定',
      'setPasswordHint': '请输入您的密码',
      'confirmPasswordHint': '请再次输入您的密码',
      'passwordNotMatchHint': '密码不匹配，请重试',

      // setup
      'setup.title': 'JHenTai 服务器设置',
      'setup.description': '请输入服务器日志中显示的 API Token 以连接。',
      'setup.tokenLabel': 'API Token',
      'setup.connect': '连接',
      'setup.emptyToken': '请输入 Token',
      'setup.invalidToken': 'Token 无效，请查看服务器日志获取正确的 Token。',
      'setup.tokenHint': 'Token 为一行共 64 位十六进制字符，请完整复制日志中的整行，不要只复制前半段。',
      'setup.tokenPasteHint': '请粘贴日志中的完整 64 位 Token',
      'setup.tokenCharCount': '已输入 @current / @total 位',
      'setup.tokenWrongLength': 'Token 必须为 64 位十六进制字符（请从 docker logs 完整复制一行）。',
      'setup.tokenHelpTitle': '如何从日志中查找 Token',
      'setup.tokenHelpP1': '在运行 Docker 的主机上打开终端，执行：',
      'setup.tokenHelpP2':
          '找到以 [JHenTai] API token for web UI 开头的行，复制冒号后的 64 位十六进制字符（整段 Token，不要截断）。若容器名不是 jhentai，请将下方命令中的名称改为你的容器名。',
      'setup.tokenHelpAlt': '若没有该行，可从服务端数据库读取（默认容器名 jhentai，数据目录 /data）：',

      // home
      'home.title': 'JHenTai',
      'home.search': '搜索画廊...',
      'home.advancedSearch': '高级搜索',
      'home.searchFilterSheetTitle': '分类与筛选',
      'home.leftPaneWidthPx': '@w px',
      'home.twoPaneDividerTooltip': '左栏 @w px · 双击分隔条恢复默认宽度',
      'home.downloads': '下载',
      'home.localGalleries': '本地画廊',
      'home.settings': '设置',
      'home.subtitle': 'E-Hentai 客户端',
      'home.home': '首页',
      'home.popular': '热门',
      'home.favorites': '收藏',
      'home.watched': '关注',
      'home.noGalleries': '未找到画廊',
      'home.previous': '上一页',
      'home.next': '下一页',
      'home.jumpDate': '跳转到日期',
      'home.page': '第 @page 页',
      'home.loadFailed': '加载失败: @error',
      'home.favSortTitle': '收藏排序',
      'home.favSortFavorited': '按收藏时间',
      'home.favSortPublished': '按发布时间',
      'home.favAllFolders': '全部',
      'home.favSlotShort': '夹 @n',
      // advanced search
      'home.categoryFilter': '分类筛选',
      'home.minimumRating': '最低评分',
      'home.ratingAny': '不限',
      'home.searchIn': '搜索范围',
      'home.galleryName': '画廊名称',
      'home.tags': '标签',
      'home.description': '描述',
      'home.showExpunged': '显示已删除',
      'home.onlyShowGalleriesWithTorrents': '只显示有种子的画廊',
      'home.pageRange': '页数范围',
      'home.pageAtLeast': '页数至少',
      'home.pageAtMost': '页数最多',
      'home.language': '语言',
      'home.languageNone': '无',
      'home.disableFilterForLanguage': '禁用语言过滤',
      'home.disableFilterForUploader': '禁用上传者过滤',
      'home.disableFilterForTags': '禁用标签过滤',
      'home.applySearch': '应用并搜索',
      // category names
      'category.doujinshi': '同人志',
      'category.manga': '漫画',
      'category.artistCg': '插画',
      'category.gameCg': '游戏CG',
      'category.western': '西方',
      'category.nonH': '非H',
      'category.imageSet': '图集',
      'category.cosplay': 'Cosplay',
      'category.asianPorn': '亚洲',
      'category.misc': '杂项',

      // gallery detail
      'detail.copyUrl': '复制画廊链接',
      'detail.copied': '已复制',
      'detail.switchToSite': '切换到 @site',
      'detail.removeFromFav': '从收藏中移除',
      'detail.addToFav': '添加到收藏',
      'detail.addToFavTitle': '添加到收藏',
      'detail.favRemoved': '已移除',
      'detail.favRemovedMsg': '已从收藏中移除',
      'detail.favAdded': '已添加',
      'detail.favAddedMsg': '已添加到 @name',
      'detail.favError': '收藏操作失败: @error',
      'detail.favSlot': '收藏夹 @n',
      'detail.favNoteHint': '收藏备注（可选）',
      'detail.favQuickAddTooltip': '加入默认收藏夹（长按）',
      'detail.rateTitle': '为画廊评分',
      'detail.rateSubmit': '提交',
      'detail.rated': '已评分',
      'detail.ratedMsg': '你的评分: @rating',
      'detail.rateFailed': '评分失败: @error',
      'detail.rateLoginRequired': '无法评分 — 需要登录',
      'detail.ratingCount': '@count 次评分',
      'detail.favoriteCount': '@count 次收藏',
      'detail.readOnline': '在线阅读',
      'detail.readOnlineResume': '在线阅读（上次第 @page 页）',
      'detail.downloadGallery': '下载画廊',
      'detail.archiveResample': '归档（压缩）',
      'detail.archiveOriginal': '归档（原图）',
      'detail.downloadArchive': '下载归档',
      'detail.downloadStarted': '下载已开始',
      'detail.galleryQueued': '画廊下载已加入队列',
      'detail.archiveQueued': '归档下载已加入队列',
      'detail.downloadFailed': '下载失败: @error',
      'detail.archiveFailed': '归档下载失败: @error',
      'detail.loadArchiveInfoFailed': '加载归档信息失败：@error',
      'detail.noArchive': '没有可用的归档',
      'detail.tags': '标签',
      'detail.comments': '评论 (@count)',
      'detail.anonymous': '匿名',
      'detail.loadFailed': '加载画廊详情失败: @error',
      'detail.metadataOnly': '完整详情页不可用，当前显示 EH API 元数据。',

      // reader
      'reader.loading': '加载画廊中...',
      'reader.loadingGalleryMeta': '正在加载页面列表...',
      'reader.resolvingFirstPages': '正在解析图片页...',
      'reader.resolvingImagePage': '正在解析页面...',
      'reader.loadingImage': '加载图片中...',
      'reader.loadFailed': '加载画廊失败: @error',
      'reader.imageFailed': '图片加载失败',
      'reader.noImages': '没有提供图片',
      'reader.directionLabel': '阅读方向: @dir',
      'reader.ltr': '从左到右',
      'reader.rtl': '从右到左',
      'reader.vertical': '上下滚动',
      'reader.shortcuts': '快捷键',
      'reader.shortcutRightKeys': '→ / ↓ / D',
      'reader.shortcutLeftKeys': '← / ↑ / A',
      'reader.shortcutNext': '下一页',
      'reader.shortcutPrev': '上一页',
      'reader.shortcutToggleMenu': '显示/隐藏菜单',
      'reader.shortcutBack': '返回',
      'reader.wheelAction': '图片上的鼠标滚轮',
      'reader.wheelActionPage': '翻页',
      'reader.wheelActionZoom': '缩放图片',
      'reader.wheelActionVerticalHint':
          '竖向与适应宽度模式始终滚动列表；本选项仅作用于从左到右、从右到左与双页模式。',
      'reader.wheelInvertPageTurn': '反转滚轮翻页方向',
      'reader.wheelInvertPageTurnSubtitle': '交换滚轮/触控板滚动时「下一页」与「上一页」的对应方向。',
      'reader.wheelScrollSpeed': '鼠标滚轮速度',
      'reader.wheelScrollSpeedSubtitle': '控制竖向与适应宽度阅读模式中的鼠标滚轮滚动速度。',
      'wheelScrollSpeed': '鼠标滚轮速度',

      // downloads
      'downloads.title': '下载',
      'downloads.gallery': '画廊',
      'downloads.archive': '归档',
      'downloads.noGallery': '没有画廊下载',
      'downloads.noArchive': '没有归档下载',
      'downloads.read': '阅读',
      'downloads.pause': '暂停',
      'downloads.resume': '继续',
      'downloads.deleteTitle': '删除下载',
      'downloads.deleteConfirm': '请选择是否保留已下载文件。',
      'downloads.loadFailed': '加载任务失败: @error',
      'downloads.wsConnected': '下载实时连接正常',
      'downloads.wsConnecting': '正在连接下载实时状态...',
      'downloads.wsReconnecting': '下载实时连接已断开，正在重连；成功后会自动同步任务状态。',
      'downloads.wsDisconnected': '下载实时连接不可用，可以手动刷新任务列表。',
      // gallery statuses
      'downloads.gStatus0': '无',
      'downloads.gStatus1': '下载中',
      'downloads.gStatus2': '已暂停',
      'downloads.gStatus3': '已完成',
      'downloads.gStatus4': '失败',
      // archive statuses
      'downloads.aStatus0': '无',
      'downloads.aStatus1': '解锁中',
      'downloads.aStatus2': '解析链接',
      'downloads.aStatus3': '下载中',
      'downloads.aStatus4': '已下载',
      'downloads.aStatus5': '解压中',
      'downloads.aStatus6': '已完成',
      'downloads.aStatus7': '已暂停',
      'downloads.aStatus8': '失败',

      // local
      'local.title': '本地画廊',
      'local.noGalleries': '未找到本地画廊',
      'local.helpText': '将目录挂载到 Docker 容器中\n或将画廊放入 local_gallery 文件夹',
      'local.scanNow': '立即扫描',
      'local.scanFailed': '扫描本地画廊失败: @error',
      'local.scanProgress': '正在扫描，已发现 @count 个画廊，用时 @elapsed',
      'local.empty': '空',
      'local.noImages': '此画廊中没有图片',
      'local.loadFailed': '加载画廊图片失败: @error',
      'local.loadListFailed': '加载本地画廊失败: @error',
      'local.deleteTitle': '删除本地画廊',
      'local.deleteConfirm': '删除「@title」的本地文件？',
      'local.deleteSuccess': '本地画廊已删除',
      'local.deleteFailed': '删除本地画廊失败: @error',
      'local.parentDirectory': '上级目录',
      'local.copyPath': '复制路径',
      'local.copyAllPaths': '复制全部路径',
      'local.scanRoots': '扫描根目录',
      'local.scanRootsHint':
          '这里显示 Docker 服务端当前扫描的容器内路径。可以在此添加已挂载路径，也可以通过 Docker 挂载和 JH_EXTRA_SCAN_PATHS 配置。',
      'local.addScanRoot': '添加扫描根目录',
      'local.deleteScanRootTitle': '移除扫描根目录',
      'local.deleteScanRootConfirm': '确定从扫描根目录中移除「@path」？',
      'local.addScanRootFailed': '添加扫描根目录失败: @error',
      'local.deleteScanRootFailed': '移除扫描根目录失败: @error',
      'local.noScanRoots': '未配置扫描根目录',

      // settings
      'settings.title': '设置',
      'settings.account': '账号',
      'settings.loggedIn': '已登录: @user',
      'settings.logout': '退出登录',
      'settings.logoutConfirm': '确定要退出当前账号吗？',
      'settings.logoutSuccess': '已退出登录',
      'settings.logoutFailed': '退出登录失败: @error',
      'settings.cookieLogin': '使用 Cookie 登录（推荐）',
      'settings.cookieHint': 'EH 论坛登录在服务器环境中被 Cloudflare 拦截。'
          '请在浏览器中登录后复制 Cookie 到此处。\n'
          '步骤: 登录 e-hentai.org → F12 → 应用 → Cookie → 复制以下值。',
      'settings.cookiePlaceholder':
          'ipb_member_id=xxx; ipb_pass_hash=xxx; igneous=xxx',
      'settings.setCookies': '设置 Cookie',
      'settings.pasteCookies': '粘贴 Cookie',
      'settings.cookieSuccess': 'Cookie 设置成功',
      'settings.cookieFailed': '设置 Cookie 失败: @error',
      'settings.cookieEmpty': '请粘贴 Cookie',
      'settings.showCookies': '查看 Cookie',
      'settings.copyCookies': '复制 Cookie',
      'settings.copyKeyCookies': '复制登录 Cookie',
      'settings.refreshIgneous': '刷新 igneous',
      'settings.refreshIgneousSuccess': 'igneous 已刷新',
      'settings.refreshIgneousFailed': '刷新 igneous 失败',
      'settings.refreshIgneousFailedWithError': '刷新 igneous 失败: @error',
      'settings.credentialLogin': '使用账号密码登录（可能因 Cloudflare 失败）',
      'settings.username': '用户名',
      'settings.password': '密码',
      'settings.login': '登录',
      'settings.loginSuccess': '登录成功',
      'settings.loginFailed': '登录失败',
      'settings.loginError': '登录失败: @error',
      'settings.emptyCredentials': '请输入用户名和密码',
      'settings.site': '站点',
      'redirect2Eh': '优先重定向至表站',
      'redirect2EhHint': '优先尝试从表站加载画廊详情页，以获得更好的网络体验。',
      'settings.appearance': '外观',
      'settings.themeMode': '主题模式',
      'settings.system': '跟随系统',
      'settings.light': '浅色',
      'settings.dark': '深色',
      'settings.accentColor': '主题色',
      'settings.serverInfo': '服务器信息',
      'settings.dataDir': '数据目录',
      'settings.downloadDir': '下载目录',
      'settings.localGalleryDir': '本地画廊目录',
      'settings.extraScanPaths': '额外扫描路径',
      'settings.switchSiteFailed': '切换站点失败: @error',
      'settings.language': '语言',
      'settings.sectionData': '数据与工具',
      'settings.sectionStyle': '样式',
      'settings.sectionRead': '阅读',
      'settings.sectionTags': '标签与过滤',
      'settings.sectionOther': '其他',
      'settings.openDownloads': '下载任务',
      'settings.openHistory': '浏览记录',
      'settings.openLocal': '本地画廊',
      'settings.openQuickSearch': '快速搜索',
      'settings.networkNote': '网络与代理',
      'settings.networkWebBody':
          '代理等网络选项在服务器或 Docker 环境中配置；此页会显示当前运行时代理状态，便于排查 EH/EX 与 H@H 图片请求。',
      'settings.about': '关于',
      'settings.appVersion': '版本 @version（@build）',
      'settings.hubMenu': '设置菜单',
      'settings.menuWebDocker': '网页与服务器',
      'settings.menuWebDockerSubtitle':
          '下载入口、Docker 路径、网络/代理说明，以及性能与安全提示（仅 Web 版）。',
      'settings.menuEH': 'E-Hentai',
      'settings.menuStyle': '样式',
      'settings.menuRead': '阅读',
      'settings.menuPreference': '偏好',
      'settings.menuNetwork': '网络',
      'settings.menuDownload': '下载',
      'settings.menuPerformance': '性能',
      'settings.menuMouseWheel': '鼠标滚轮',
      'settings.menuAdvanced': '高级',
      'settings.menuSecurity': '安全',
      'settings.ehRequiresLogin': '请先在「账号」中登录后再修改站点与 Cookie 状态。',
      'settings.ehMyTags': '我的标签',
      'settings.ehMyTagsHint': '管理在线关注和隐藏的标签',
      'settings.ehSiteSetting': '站点设置',
      'settings.ehSiteSettingHint': '在新标签页打开 E-Hentai / ExHentai 设置页',
      'settings.ehProfile': 'Profile 设置',
      'settings.ehSelectedProfile': '当前 Profile',
      'settings.ehProfileHint':
          '当前站点: @site。与 App 一样通过 sp Cookie 切换当前站点使用的 Profile。',
      'settings.ehProfileEmpty': '未找到可用 Profile',
      'settings.ehProfileSaved': 'Profile 已切换',
      'settings.ehProfileSaveFailed': '切换 Profile 失败: @error',
      'settings.ehProfileLoadFailed': '加载 Profile 失败: @error',
      'settings.ehProfileAndQuota': '档案、配额与资产',
      'settings.ehProfileAndQuotaHint': '这些数据仍依赖站点页面解析；当前可在站点设置页中查看。',
      'settings.ehAssets': '资产',
      'settings.ehImageQuota': '图片配额',
      'settings.ehResetCost': '重置花费',
      'settings.ehQuotaUnavailable': '图片配额仅捐赠用户可查看',
      'settings.ehQuotaResetConfirm': '重置图片配额将花费 @cost GP，确定继续吗？',
      'settings.ehQuotaReset': '图片配额已重置',
      'settings.ehQuotaResetFailed': '重置图片配额失败: @error',
      'settings.ehStatusFailed': '加载 EH 状态失败: @error',
      'settings.galleryListStyle': '画廊列表样式',
      'pageListStyle': '画廊列表样式（页面）',
      'global': '全局',
      'settings.listModeGrid': '网格',
      'settings.listModeList': '列表',
      'settings.listModeCompact': '紧凑',
      'settings.gridColumns': '网格列数',
      'settings.gridColumnsAuto': '自动',
      'settings.downloadGridColumns': '下载页网格列数',
      'settings.downloadGridColumnsHint': '应用到当前浏览器中的下载任务网格。',
      'settings.localGridColumns': '本地库网格列数',
      'settings.localGridColumnsHint': '应用到当前浏览器中的本地库目录和画廊网格。',
      'settings.detailThumbnailColumns': '详情页缩略图列数',
      'settings.detailThumbnailColumnsHint': '应用到画廊详情页缩略图和完整缩略图页。',
      'moveCover2RightSide': '移动封面图至右侧',
      'settings.moveCoverWebHint': '应用到当前浏览器中的宽屏画廊详情页。',
      'settings.galleryListStyleHint': '会立即应用到 Web 首页画廊列表，并保存在当前浏览器。',
      'settings.showGalleryListTags': '在画廊列表中显示标签',
      'settings.showGalleryListTagsHint': '对应 App 中可隐藏标签的列表样式，让列表更清爽。',
      'settings.pageListStyleHint': '为各个 Web 页面单独覆盖画廊列表样式；全局表示使用上方样式。',
      'settings.networkWebSummary': '网络代理状态请在「网络」页查看；修改 Docker 环境变量后需重启服务端。',
      'settings.proxyRouting': '请求路由',
      'settings.ehProxyRoute': 'EH/EX 页面请求',
      'settings.hathProxyRoute': 'H@H 图片请求',
      'settings.hathProxyDedicatedHint':
          '已配置 JH_HATH_PROXY，*.hath.network 会优先走这个代理。',
      'settings.hathProxyFallbackHint':
          '未配置 JH_HATH_PROXY，*.hath.network 会沿用 HTTPS_PROXY/HTTP_PROXY；如果 H@H 仍直连失败，请单独设置 JH_HATH_PROXY。',
      'settings.proxyEnvironment': '代理环境变量',
      'settings.proxyEnvironmentEmpty': '未读取到代理环境变量。',
      'settings.proxyEnvironmentHint': '为安全起见，这里只显示协议、主机和端口，不显示账号密码。',
      'settings.copyProxyEnvTemplate': '复制 Docker 代理模板',
      'settings.proxyEnvTemplateCopied': '已复制 Docker 代理环境变量模板',
      'settings.proxyAuthConfigured': '已配置认证',
      'settings.copyNetworkDiagnostics': '复制网络诊断',
      'settings.networkTimeouts': '网络超时',
      'settings.networkTimeoutsSummary': '连接 @connect ms / 接收 @receive ms',
      'settings.networkTimeoutsHint':
          '会立即应用到 EH/EX 和 H@H 请求。范围：1000-600000 ms。',
      'connectTimeout': '连接超时',
      'receiveTimeout': '接收超时',
      'saveSuccess': '保存成功',
      'settings.networkRuntimeFlags': '网络诊断开关',
      'settings.networkRestartHint': '这些值来自服务端启动环境，修改后需要重启容器生效。',
      'settings.directConnection': '直连',
      'settings.configured': '已配置',
      'settings.notConfigured': '未配置',
      'settings.enabled': '已启用',
      'settings.disabled': '未启用',
      'settings.maintenanceCenter': '维护中心',
      'settings.maintenanceCenterSummary': '查看镜像版本、更新检查、SQLite 备份和容量摘要。',
      'settings.troubleshootingWorkbench': '排障工作台',
      'settings.troubleshootingWorkbenchSummary':
          '集中查看诊断、日志、代理和超分状态，并运行手动排障测试。',
      'settings.setupChecklist': '启动清单',
      'settings.setupChecklistSummaryHint': '检查首次部署和升级后的可用状态，不会自动运行外网探测。',
      'settings.setupChecklistHint':
          '此清单只读取本地运行状态；需要测试网络或 H@H 时，请到排障工作台手动运行主动测试。',
      'settings.setupChecklistSummary': '就绪状态总览',
      'settings.setupChecklistSummaryBody':
          '@total 项检查，@errors 个错误，@warnings 个警告。',
      'settings.setupChecklistLoadFailed': '加载启动清单失败: @error',
      'settings.copySetupChecklist': '复制启动清单',
      'settings.setupChecklistCopied': '启动清单已复制',
      'settings.maintenanceLoadFailed': '加载维护信息失败: @error',
      'settings.maintenanceRuntime': '当前运行版本',
      'settings.appVersionLabel': '应用版本',
      'settings.dockerImageTag': 'Docker 镜像标签',
      'settings.forkRevision': 'Fork 版本号',
      'settings.imageChannel': '镜像通道',
      'settings.maintenanceUpdate': '镜像更新',
      'settings.checkDockerUpdate': '检查更新',
      'settings.updateCheckManualHint': '不会自动访问外网；需要时手动检查 Docker Hub 最新标签。',
      'settings.currentImageTag': '当前标签',
      'settings.latestImageTag': '最新标签',
      'settings.maintenanceBackup': '更新前备份',
      'settings.sqliteBackupSensitiveHint':
          'SQLite 备份包含登录 Cookie、API Token、设置和下载任务，是敏感文件；不会包含图片、下载目录或本地图库。',
      'settings.downloadSqliteBackup': '下载 SQLite 备份',
      'settings.sqliteBackupDownloaded': 'SQLite 备份已开始下载',
      'settings.sqliteBackupFailed': 'SQLite 备份失败: @error',
      'settings.restoreSqliteBackup': '恢复 SQLite 备份',
      'settings.sqliteRestorePreviewTitle': '恢复 SQLite 备份？',
      'settings.sqliteRestorePreviewIntro':
          '将用所选备份替换当前 Web 数据。确认前会自动下载一次当前 SQLite 备份。',
      'settings.confirmRestoreSqliteBackup': '备份当前库并恢复',
      'settings.sqliteRestoreSuccess':
          'SQLite 备份已恢复；已暂停 @gallery 个画廊任务和 @archive 个归档任务。',
      'settings.sqliteRestoreFailed': 'SQLite 恢复失败: @error',
      'settings.sqliteRestoreGalleryDownloads': '画廊下载任务',
      'settings.sqliteRestoreArchiveDownloads': '归档下载任务',
      'settings.sqliteRestoreGalleryImages': '下载图片记录',
      'settings.sqliteRestoreWarnToken': '当前 API Token 会保留。',
      'settings.sqliteRestoreWarnCookies': 'EH 登录 Cookie 会从备份恢复。',
      'settings.sqliteRestoreWarnPageCache': '页面缓存不会恢复。',
      'settings.sqliteRestoreWarnDownloadsPaused': '备份中的下载中任务会改为暂停。',
      'settings.sqliteRestoreWarnNoDownloads': '该备份不包含下载任务。',
      'settings.maintenanceStorage': '容量摘要',
      'settings.databaseSize': '数据库大小',
      'settings.logsSize': '日志大小',
      'settings.pageCacheSize': '页面缓存大小',
      'settings.pageCacheCount': '页面缓存条目',
      'settings.maintenancePaths': '关键路径',
      'settings.maintenanceTips': '维护建议',
      'settings.maintenanceTipPinVersion':
          '更新 compose 时建议固定明确版本标签，不要长期使用 latest。',
      'settings.maintenanceTipBackup': '更新前至少下载一次 SQLite 备份，并保留当前 compose 配置。',
      'settings.maintenanceTipNoImageBackup':
          '图片和本地图库通常很大，请通过 NAS/宿主机快照或目录备份处理。',
      'settings.deploymentDiagnostics': '部署自检',
      'settings.deploymentDiagnosticsSummaryHint':
          '检查 API、WebSocket、目录权限、数据库、代理和日志状态。',
      'settings.copyDeploymentDiagnostics': '复制部署诊断',
      'settings.deploymentDiagnosticsSummary': '部署状态总览',
      'settings.deploymentDiagnosticsSummaryBody': '@errors 个错误，@warnings 个警告。',
      'settings.generatedAt': '生成时间',
      'settings.diagnosticsLoadFailed': '加载部署诊断失败: @error',
      'settings.diagnosticsGroupService': '服务入口',
      'settings.diagnosticsGroupStorage': '存储目录',
      'settings.diagnosticsGroupDatabase': '数据库',
      'settings.diagnosticsGroupLocalGallery': '本地图库',
      'settings.diagnosticsGroupNetwork': '网络代理',
      'settings.diagnosticsGroupLogs': '日志',
      'settings.diagnosticsStatusOk': '正常',
      'settings.diagnosticsStatusWarn': '警告',
      'settings.diagnosticsStatusError': '错误',
      'settings.websocketStatus': '下载 WebSocket',
      'settings.websocketConnecting': '正在连接下载实时状态通道。',
      'settings.websocketConnected': '下载实时状态通道已连接。',
      'settings.websocketReconnecting': '下载实时状态通道正在重连。',
      'settings.websocketDisconnected': '下载实时状态通道未连接，请检查反代 WebSocket 转发。',
      'settings.troubleshootingLoadFailed': '加载排障信息失败: @error',
      'settings.troubleshootingProbeFailed': '排障测试失败: @error',
      'settings.troubleshootingSummary': '排障总览',
      'settings.troubleshootingSummaryBody': '发现 @count 个需要关注的项目。',
      'settings.troubleshootingIssueList': '需要处理的问题',
      'settings.troubleshootingNoIssues': '当前没有需要处理的问题。',
      'settings.troubleshootingOpenTarget': '打开相关页面',
      'settings.troubleshootingRetest': '重新测试',
      'settings.troubleshootingCopyFix': '复制修复片段',
      'settings.troubleshootingRunAction': '执行修复',
      'settings.troubleshootingActionConfirm': '将对匹配的失败任务执行批量修复操作，是否继续？',
      'settings.troubleshootingActionDone': '修复操作已完成',
      'settings.troubleshootingActiveProbe': '手动主动测试',
      'settings.troubleshootingActiveProbeHint':
          '仅在点击后访问外网；可测试 EH/EX、H@H 图片节点和 GPU/超分运行环境。',
      'settings.troubleshootingHathUrl': 'H@H 图片 URL（可选）',
      'settings.runTroubleshootingProbe': '运行排障测试',
      'settings.troubleshootingProbe_network': 'EH/EX 网络',
      'settings.troubleshootingProbe_hath': 'H@H 图片节点',
      'settings.troubleshootingProbe_superResolution': 'GPU/超分环境',
      'settings.troubleshootingProbe_downloads': '下载失败',
      'settings.troubleshootingFailedJobs': '失败任务',
      'settings.troubleshootingGpuDevices': 'GPU 设备',
      'settings.copyGpuComposeSnippet': '复制 GPU compose 片段',
      'settings.troubleshootingRecentProblems': '最近问题日志',
      'settings.troubleshootingNoRecentProblems': '最近没有 warning/error 日志。',
      'settings.troubleshootingActions': '建议操作',
      'settings.troubleshootingSkipped': '已跳过',
      'settings.proxyHasCredentials': '已配置认证',
      'settings.logCount': '日志数量',
      'settings.logTotalSize': '日志大小',
      'settings.logLatestModified': '最近更新',
      'settings.downloadWebSummary': '设置下载默认分组与优先级，查看 Docker 下载路径和并发，并管理下载任务。',
      'settings.downloadWebIntro': '设置网页下载弹窗使用的默认分组和优先级，并查看服务端 Docker 下载参数。',
      'settings.downloadDefaults': '下载默认值',
      'settings.downloadDefaultsSaved': '下载默认值已保存',
      'settings.defaultGalleryDownload': '画廊下载',
      'settings.defaultArchiveDownload': '归档下载',
      'settings.customGroupName': '自定义分组名',
      'settings.archiveParseSource': '归档解析来源',
      'settings.archiveParseOfficial': '官方 EH 归档',
      'settings.archiveParseOfficialShort': '官方',
      'settings.archiveParseBot': 'Archive Bot / Archive-at-Home',
      'settings.archiveParseBotShort': 'Bot',
      'settings.archiveParseChangeHint': '切换解析来源会清空已解析链接并重新排队。',
      'speedLimit': '下载速度限制',
      'settings.speedLimitWebHint': '限制 Docker 服务端的画廊图片下载速度；选择 99 表示不限速。',
      'settings.speedLimitMaximum': '图片数',
      'settings.speedLimitPeriod': '每',
      'settings.unlimited': '不限速',
      'settings.restoreTasksLoadFailed': '加载任务自动恢复设置失败: @error',
      'settings.speedLimitLoadFailed': '加载下载速度限制失败: @error',
      'settings.downloadServerRuntime': '服务端运行参数',
      'settings.runtimeLoadFailed': '加载服务端运行参数失败: @error',
      'settings.galleryConcurrency': '画廊并发',
      'settings.archiveConcurrency': '归档并发',
      'settings.archiveBotTitle': 'Archive Bot / Archive-at-Home',
      'settings.archiveBotHint':
          '可选第三方归档解析服务，默认不会使用。配置 API key 后，归档任务可手动选择 Bot 解析来源。',
      'settings.archiveBotProtocol': '协议',
      'settings.archiveBotApiAddress': 'API 地址',
      'settings.archiveBotApiKey': 'API key',
      'settings.archiveBotApiKeyConfigured': '已保存 API key；留空保存会保留当前 key。',
      'settings.archiveBotApiKeyNotConfigured': '未配置 API key。',
      'settings.archiveBotTestBalance': '测试余额',
      'settings.archiveBotCheckIn': '签到',
      'settings.archiveBotSaved': 'Archive Bot 设置已保存',
      'settings.archiveBotBalanceResult': '当前余额: @balance',
      'settings.archiveBotLoadFailed': '加载 Archive Bot 设置失败: @error',
      'settings.archiveBotSaveFailed': '保存 Archive Bot 设置失败: @error',
      'settings.archiveBotActionFailed': 'Archive Bot 请求失败: @error',
      'settings.jhPublicApiBaseUrl': 'JH 公共 API',
      'settings.jhAppId': 'JH 应用 ID',
      'settings.jhApiSecretConfigured': 'JH API 密钥',
      'settings.downloadRuntimeHint': '并发与路径由 Docker 环境变量控制，修改后需重启服务端生效。',
      'settings.performanceWebSummary': '设置 Web 下载列表动画阈值，减少大列表展开/收起时的浏览器负担。',
      'settings.webPerformance': 'Web 性能',
      'settings.performanceWebIntro': 'Web 端在浏览器中运行，这里提供会影响大列表交互流畅度的本机浏览器设置。',
      'settings.performancePresetTitle': '性能预设',
      'settings.performancePresetHint': '一键调整阅读预加载和下载页动画阈值；应用后仍可在阅读设置中单独修改。',
      'settings.performancePresetNas': 'NAS 低负载',
      'settings.performancePresetBalanced': '均衡',
      'settings.performancePresetFast': '高速设备',
      'settings.performancePresetApplying': '正在应用 @preset...',
      'settings.performancePresetFailed': '应用性能预设失败：@error',
      'settings.webMaxGalleryNum4Animation': '下载分组动画阈值',
      'settings.webMaxGalleryNum4AnimationHint':
          '单个下载分组内任务数超过此值时，关闭展开/收起图标动画；0 表示始终关闭。',
      'settings.resetPerformanceDefaults': '恢复默认性能设置',
      'settings.performanceSaved': '性能设置已保存',
      'settings.advancedWebSummary': '开启无图模式，查看 Docker 路径信息并管理服务器日志。',
      'settings.advancedWebIntro': '管理当前 Web 实例的图片加载、服务器日志与 Docker 路径信息。',
      'settings.exportData': '导出数据',
      'settings.exportDataHint':
          '将设置、屏蔽规则、浏览历史、搜索历史和快速搜索导出为 JSON，不包含 Token 和 Cookie。',
      'settings.exportDataSuccess': '数据导出已下载',
      'settings.exportDataFailed': '导出数据失败：@error',
      'settings.exportAppData': '导出为 App 格式',
      'settings.exportAppDataHint':
          '下载 App 可导入的 JHenTaiConfig 文件，包含阅读进度、快速搜索、屏蔽规则、搜索历史和浏览历史。',
      'settings.exportAppDataSuccess': 'App 兼容数据导出已下载',
      'settings.importData': '导入数据',
      'settings.importDataHint':
          '导入 Web 导出的 JSON 或 App 的 JHenTaiConfig 文件并合并到当前服务端；设置和命名数据会覆盖，屏蔽规则会自动去重。',
      'settings.importDataTitle': '导入数据？',
      'settings.importDataConfirm':
          '请选择 JHenTai Web 导出的 JSON 或 App 的 JHenTaiConfig 文件。导入的设置可能覆盖当前值。',
      'settings.importDataSuccess': '已导入 @count 项数据',
      'settings.importDataFailed': '导入数据失败：@error',
      'settings.importPreviewTitle': '导入预检',
      'settings.importPreviewSource': '来源：@source',
      'settings.importSourceWeb': 'Web 导出',
      'settings.importSourceApp': 'App / 云端配置',
      'settings.importPreviewSummary':
          '可导入 @count 项，可能覆盖 @replace 项，跳过 @skip 项。',
      'settings.importPreviewBackupHint': '确认后会先自动下载当前 Web 数据备份，再执行导入。',
      'settings.importPreviewOverwriteHint':
          '导入会合并数据；配置、历史、搜索历史和快速搜索可能按相同 key / gid / keyword / name 覆盖。',
      'settings.importConfirmWithBackup': '备份并导入',
      'settings.importSectionSummary': '导入 @count · 覆盖 @replace · 跳过 @skip',
      'settings.importSectionConfig': '设置',
      'settings.importSectionBlockRules': '屏蔽规则',
      'settings.importSectionHistory': '浏览历史',
      'settings.importSectionSearchHistory': '搜索历史',
      'settings.importSectionQuickSearch': '快速搜索',
      'settings.importSectionReadProgress': '阅读进度',
      'settings.cloudSync': '云端配置同步',
      'settings.cloudSyncHint': '浏览 JHenTai 云端配置，通过分享码导入，并合并到当前 Docker 服务端。',
      'settings.cloudServiceAvailable': 'JHenTai 云端配置服务可用',
      'settings.cloudServiceUnavailable': 'JHenTai 云端配置服务不可用',
      'settings.cloudShareCode': '分享码',
      'settings.cloudConfigType': '配置类型',
      'settings.cloudConfigEmpty': '暂无云端配置',
      'settings.cloudConfigNotFound': '未找到对应分享码的配置',
      'settings.cloudConfigUnknownType': '未知配置',
      'settings.cloudConfigLoadFailed': '加载云端配置失败：@error',
      'settings.cloudShareCodeLoadFailed': '查询分享码失败：@error',
      'settings.uploadCloudConfig': '上传至云端',
      'settings.uploadCloudConfigTitle': '上传当前数据到云端？',
      'settings.uploadCloudConfigConfirm': '选择要上传到 JHenTai 云端配置服务的本地数据类型。',
      'settings.uploadCloudConfigSuccess': '云端配置已上传',
      'settings.uploadCloudConfigFailed': '上传云端配置失败：@error',
      'settings.deleteCloudConfigTitle': '删除云端配置？',
      'settings.deleteCloudConfigConfirm': '这会从 JHenTai 云端配置服务删除该配置。',
      'settings.deleteCloudConfigFailed': '删除云端配置失败：@error',
      'settings.noImageMode': '无图模式',
      'settings.noImageModeHint': '在当前浏览器隐藏画廊封面、缩略图和阅读器图片。',
      'checkClipboard': '检测剪贴板中的画廊链接',
      'settings.checkClipboardHint': '首页打开时检测浏览器剪贴板中的画廊链接，并提示是否打开。',
      'settings.pageCache': '页面缓存',
      'settings.clearPageCache': '清理页面缓存',
      'settings.clearPageCacheTitle': '清理页面缓存？',
      'settings.clearPageCacheConfirm': '这会删除服务器上缓存的 EH 页面响应。',
      'settings.clearPageCacheFailed': '清理页面缓存失败：@error',
      'settings.loadPageCacheFailed': '加载页面缓存失败：@error',
      'settings.pageCacheSummary': '@count 个缓存页面 · @size',
      'settings.serverLogs': '服务器日志',
      'settings.clearLogsTitle': '清理服务器日志？',
      'settings.clearLogsConfirm': '这会删除当前所有服务器日志文件。',
      'settings.clearLogsFailed': '清理日志失败：@error',
      'settings.loadLogsFailed': '加载日志列表失败：@error',
      'settings.loadLogFailed': '加载日志失败：@error',
      'settings.noLogs': '暂无日志',
      'settings.copyLog': '复制日志',
      'settings.downloadLog': '下载日志',
      'settings.emptyLog': '此日志为空',
      'settings.searchLog': '搜索日志...',
      'settings.noLogMatches': '无匹配',
      'settings.logMatchCounter': '@current / @total',
      'settings.previousMatch': '上一个匹配',
      'settings.nextMatch': '下一个匹配',
      'settings.securityWebSummary':
          '查看当前浏览器保存的 API Token 状态，校验连接有效性，或断开后重新连接。',
      'settings.webTokenSecurity': 'Web 连接安全',
      'settings.webTokenSaved': '本机 Token',
      'settings.webTokenSavedYes': '已保存在当前浏览器',
      'settings.webTokenSavedNo': '当前浏览器未保存 Token',
      'settings.webTokenFingerprint': 'Token 指纹',
      'settings.webTokenVerifyStatus': '校验状态',
      'settings.webTokenValid': '当前 Token 可用',
      'settings.webTokenInvalid': '当前 Token 无效或已轮换',
      'settings.securityWebBody':
          'Web 端使用浏览器本地保存的 API Token 连接服务端。这里不会显示完整 Token，只用于确认当前浏览器连接状态。',
      'settings.verifyCurrentToken': '校验当前 Token',
      'settings.disconnectWebToken': '断开并重新连接',
      'settings.disconnectWebTokenTitle': '断开当前 Web 连接？',
      'settings.disconnectWebTokenConfirm':
          '这会清除当前浏览器保存的 API Token，并返回设置向导。服务端 Token 不会被删除。',
      'settings.webTokenRotateHint':
          '如果你已经在服务端轮换 Token，请先断开当前连接，然后在设置向导中粘贴新的 Token。',
      'settings.webPasswordAuthHint': '用当前浏览器本地保存的 4 位 PIN 保护 Web 会话。',
      'settings.lockNow': '立即锁定',
      'settings.disablePasswordAuthTitle': '关闭密码认证？',
      'settings.disablePasswordAuthConfirm': '这会删除当前浏览器保存的本地 PIN。',
      'settings.passwordAuthEnabled': '已开启密码认证',
      'settings.changeWebPin': '修改 PIN',
      'settings.currentWebPinHint': '请输入当前 PIN',
      'settings.newWebPinHint': '请输入新的 PIN',
      'settings.webPinChanged': 'PIN 已修改',
      'settings.mouseWheelIntro': '选择阅读器中鼠标滚轮在图片上的行为（横向翻页模式）。',
      'settings.webWheelScrollSpeedHint': '控制 Web 画廊列表中的鼠标滚轮滚动速度。',
      'settings.mouseWheelReadHint': '阅读方向、预加载等全部选项',
      'settings.loadWheelSettingsFailed': '加载鼠标滚轮设置失败：@error',
      'settings.saveWheelSettingsFailed': '保存鼠标滚轮设置失败：@error',
      'settings.aboutVersionLabel': '版本',
      'settings.aboutAuthorLabel': '作者',
      'settings.aboutTelegramTitle': 'Telegram（主要为中文）',
      'settings.aboutTelegramHint': '社群链接',
      'settings.aboutQA': '问答',
      'settings.aboutWebForkNote': '本网页界面由 JHenTai Docker 分支提供；上游项目见上方链接。',

      // history
      'history.title': '浏览记录',
      'history.empty': '暂无浏览记录',
      'history.clearAll': '清空全部',
      'history.clearTitle': '清空浏览记录',
      'history.clearConfirm': '确定要清空所有浏览记录吗？',
      'history.deleteTitle': '删除浏览记录',
      'history.deleteConfirm': '确定从浏览记录中删除「@title」？',
      'history.deleteSuccess': '浏览记录已删除',
      'history.deleteFailed': '删除浏览记录失败: @error',
      'history.clearSuccess': '浏览记录已清空',
      'history.clearFailed': '清空浏览记录失败: @error',
      'history.loadFailed': '加载浏览记录失败: @error',
      'history.loadMore': '加载更多',
      'history.search': '搜索浏览记录...',
      'history.jumpToPage': '跳转浏览记录页',
      'history.pageRange': '范围: 1 - @total，当前: @current',

      // search history
      'searchHistory.clearAll': '清除搜索记录',
      'searchHistory.clearTitle': '清除搜索记录',
      'searchHistory.clearConfirm': '确定要清除所有搜索记录吗？',
      'searchHistory.translate': '翻译搜索记录',
      'searchHistory.hide': '隐藏搜索历史',
      'searchHistory.show': '显示搜索历史',

      // comment
      'comment.placeholder': '写下评论...',
      'comment.send': '发送',
      'comment.posted': '评论已发送',
      'comment.postedMsg': '你的评论已发布',
      'comment.postFailed': '发送评论失败: @error',
      'comment.voteFailed': '投票失败: @error',
      'comment.scoreDetails': '评分明细',
      'lastEditedOn': '最后修改于',
      'comment.update': '更新评论',
      'comment.updated': '评论已更新',
      'comment.updatedMsg': '你的评论已更新',
      'comment.updateFailed': '更新评论失败: @error',
      'comment.tooShort': '评论过短',
      'comment.atLeast3Characters': '至少 3 个字符',

      // ranklist
      'ranklist.title': '排行榜',
      'ranklist.allTime': '历史总榜',
      'ranklist.year': '年度',
      'ranklist.month': '月度',
      'ranklist.yesterday': '昨日',

      // thumbnails
      'thumbnails.title': '缩略图 (@count)',
      'thumbnails.grid': '缩略图网格',
      'thumbnails.jumpToPage': '跳转页面',
      'thumbnails.pageRange': '范围: 1 - @total',
      'thumbnails.loadFailed': '加载缩略图失败: @error',

      // home additions
      'home.history': '浏览记录',
      'home.ranklist': '排行榜',

      // tag translation
      'tagInfo.title': '标签详情',
      'tagInfo.empty': '暂无标签详情',
      'tagInfo.loadFailed': '加载标签详情失败: @error',
      'showR18GImageDirectly': '标签数据中直接显示R18G图片',
      'warningImageHint': 'R18G图片，点击以显示',
      'tagTranslation.title': '标签翻译',
      'enableTagZHTranslation': '启用标签中文翻译',
      'settings.enableTagZHTranslationHint': '可用时翻译标签、标签搜索建议和搜索历史',
      'tagTranslation.loaded': '已加载 @count 个标签',
      'tagTranslation.notLoaded': '标签数据库未加载',
      'tagTranslation.lastUpdate': '最后更新: @time',
      'tagTranslation.refresh': '更新标签数据库',
      'tagTranslation.refreshSuccess': '已更新 @count 个标签',
      'tagTranslation.refreshFailed': '更新失败: @error',
      'zhTagSearchOrderOptimization': '标签补全排序规则',
      'zhTagSearchOrderOptimizationHint': '默认智能排序，启用后按画廊使用频次排序',
      'tagSearchOrder.loaded': '已加载 @count 条标签频次',
      'tagSearchOrder.notLoaded': '标签频次数据未加载',
      'tagSearchOrder.version': '版本: @version',
      'tagSearchOrder.refresh': '更新标签频次数据',
      'tagSearchOrder.refreshSuccess': '已更新 @count 条标签频次',
      'tagSearchOrder.refreshFailed': '更新失败: @error',

      // list mode
      'listMode.toggle': '切换显示模式',
      'listMode.grid': '网格',
      'listMode.list': '列表',
      'listMode.listCompact': '紧凑列表',

      // quick search
      'quickSearch.title': '快速搜索',
      'quickSearch.empty': '没有已保存的搜索',
      'quickSearch.saveCurrent': '保存当前搜索',
      'quickSearch.saveTitle': '保存快速搜索',
      'quickSearch.editTitle': '编辑快速搜索',
      'quickSearch.nameLabel': '名称',
      'quickSearch.addNew': '添加快速搜索',
      'quickSearch.keywordLabel': '关键词',
      'quickSearch.keywordHint': '与首页搜索栏相同',
      'quickSearch.saved': '已保存',
      'quickSearch.deleted': '已删除',
      'quickSearch.deleteTitle': '删除快速搜索',
      'quickSearch.deleteConfirm': '确定删除「@name」？',
      'quickSearch.orderSaveFailed': '保存快速搜索排序失败: @error',

      // tag suggest
      'tagSuggest.tag': '标签',

      // common extras
      'common.save': '保存',

      // reader enhancements
      'reader.fitWidth': '适应宽度',
      'reader.doubleColumn': '双页模式',
      'reader.autoStart': '自动阅读',
      'reader.autoStop': '停止自动阅读',

      'enableBottomMenu': '启用底部菜单',

      'enablePageTurnAnime': '开启翻页动画',
      'enableDoubleTapToScaleUp': '允许双击放大图片',
      'enableTapDragToScaleUp': '允许单击后拖拽放大图片',
      'reverseTurnPageDirection': '反转点击翻页方向',
      'disablePageTurningOnTap': '禁用点击翻页手势',
      // block rules
      'blockRule.title': '屏蔽规则',
      'blockRule.empty': '没有配置屏蔽规则',
      'blockRule.add': '添加规则',
      'blockRule.addCondition': '追加条件',
      'blockRule.edit': '编辑规则',
      'blockRule.manage': '管理屏蔽规则',
      'useBuiltInBlockedUsers': '使用内置用户屏蔽名单',
      'useBuiltInBlockedUsersHint': '过滤掉内置名单中的用户评论',
      'useBuiltInBlockedUsersLoadFailed': '加载内置用户屏蔽名单设置失败: @error',
      'blockRule.ruleCount': '@count 条规则',
      'blockRule.ungrouped': '未分组',
      'blockRule.deleteGroup': '删除分组',
      'blockRule.deleteGroupTitle': '删除屏蔽规则分组',
      'blockRule.deleteGroupConfirm': '确定删除分组「@group」及其中 @count 条规则？',
      'blockRule.deleteRuleTitle': '删除屏蔽规则',
      'blockRule.deleteRuleConfirm': '确定删除规则「@rule」？',
      'blockRule.loadFailed': '加载屏蔽规则失败: @error',
      'blockRule.saveFailed': '保存屏蔽规则失败: @error',
      'blockRule.deleteFailed': '删除屏蔽规则失败: @error',
      'blockRule.saveSuccess': '屏蔽规则已保存',
      'blockRule.deleteSuccess': '屏蔽规则已删除',
      'blockRule.target': '目标',
      'blockRule.attribute': '属性',
      'blockRule.pattern': '匹配模式',
      'blockRule.expression': '表达式',
      'blockRule.expressionHint': '要匹配的值',
      'blockRule.groupId': '分组 ID',
      'blockRule.groupIdHint': '可选的分组名称',
      'blockRule.blocked': '已屏蔽',
      'blockRule.tagBlocked': '标签 "@tag" 已被屏蔽',
      'blockRule.uploaderBlocked': '上传者 "@uploader" 已被屏蔽',
      'blockRule.blockTag': '屏蔽此标签',
      'blockRule.blockUploader': '屏蔽此上传者',
      'blockRule.blockCommentUser': '屏蔽评论用户',
      'blockRule.blockCommentUserConfirm': '屏蔽评论用户 "@user"？',
      'blockRule.commentUserBlocked': '评论用户 "@user" 已被屏蔽',

      // download enhancements
      'simpleSearch': '简单',
      'regexSearch': '正则',
      'downloads.search': '搜索下载...',
      'downloads.allGroups': '所有分组',
      'downloads.group': '分组',

      // tag voting
      'tagVote.search': '搜索',
      'tagVote.copyTag': '复制标签',
      'tagVote.searchUploader': '搜索上传者',
      'tagVote.voteUp': '投赞成票',
      'tagVote.voteDown': '投反对票',
      'tagVote.success': '已投票',
      'tagVote.votedUp': '已为 "@tag" 投赞成票',
      'tagVote.votedDown': '已为 "@tag" 投反对票',
      'tagVote.failed': '投票失败: @error',
      'tagVote.addTag': '添加标签',
      'tagVote.addTagHint': '输入新标签，多个用逗号分隔',
      'tagVote.addSuccess': '添加标签成功',
      'tagVote.addFailed': '添加标签失败：@error',

      // responsive layout
      'home.selectGallery': '选择一个画廊查看详情',
      'home.selectGalleryHint': '画廊详情会显示在这个面板中。',

      // gallery detail extras
      'detail.parentGallery': '父画廊',
      'detail.newerVersion': '有更新版本',
      'detail.versionHistory': '版本历史',
      'detail.currentVersion': '当前版本',
      'detail.torrents': '种子',
      'detail.torrentCount': '种子（@count）',
      'detail.noTorrents': '暂无种子',
      'detail.outdatedTorrents': '已过期',
      'detail.downloadTorrent': '下载种子',
      'detail.copyMagnet': '复制磁力链接',
      'detail.torrentSeeds': '种子 @count',
      'detail.torrentPeers': '连接 @count',
      'detail.torrentDownloads': '下载 @count',
      'detail.loadTorrentsFailed': '加载种子失败：@error',
      'detail.hhDownload': 'H@H 下载',
      'detail.noHHArchives': '暂无可用 H@H 归档',
      'detail.loadHHFailed': '加载 H@H 归档失败：@error',
      'detail.hhSubmitFailed': '提交 H@H 下载失败：@error',
      'detail.hhSubmitted': '已提交 H@H 下载请求',

      // settings extras
      'settings.cookieStatusFull': 'Cookie 正常（包含 igneous — 可访问 EX）',
      'settings.cookieStatusNoIgneous': 'Cookie 已设置但缺少 igneous — EX 可能无法使用',
      'settings.cookieStatusNone': '未设置登录 Cookie',
      'settings.siteSwitched': '已切换到 @site',

      // download progress in detail
      'detail.completed': '已完成',
      'detail.retryDownload': '重试',
      'detail.readDownloaded': '阅读已下载',
      'detail.deleteDownload': '删除下载',
      'detail.deleteDownloadConfirm': '删除此下载及其文件？',
      'detail.archiveCompleted': '归档就绪',

      // detail enhancements
      'detail.share': '分享',
      'detail.jumpToPage': '跳转到页',
      'detail.jumpToThumbnail': '跳到缩略图',
      'detail.similarSearch': '相似搜索',
      'detail.blockGallery': '屏蔽画廊',
      'detail.allComments': '全部评论',
      'detail.thumbnails': '缩略图 (@count)',
      'detail.viewAllThumbnails': '查看全部缩略图',
      'detail.galleryBlocked': '画廊已被屏蔽',
      'detail.jumpPageHint': '输入页码 (1-@max)',

      // reader enhancements
      'reader.saveImage': '保存图片',
      'reader.openInNewTab': '在新标签页打开',
      'reader.reloadImage': '重新加载',
      'reader.interval': '间隔',
      'reader.preload': '预加载',
      'reader.imageSpacing': '图片间距',
      'reader.autoInterval': '自动阅读间隔',
      'reader.startAutoMode': '开始',
      'reader.saveFailed': '保存图片失败',
      'reader.redownloadHint': '请打开「下载」页面重试或重新开始该画廊下载。',
      'reader.deviceOrientation': '设备方向',
      'reader.deviceOrientationWebHint': '网页版无法像客户端一样锁定屏幕方向。请使用浏览器全屏或系统旋转锁定。',
      'toggleFullScreen': '切换全屏',

      // settings reader
      'settings.defaultFavoriteSlot': '默认收藏夹',
      'settings.defaultFavoriteNone': '无（每次询问）',
      'settings.defaultFavoriteHint': '启用后点击心形按钮会使用默认收藏夹，长按可重新选择。',
      'settings.usertags': '关注 / 隐藏标签',
      'settings.readerSettings': '阅读器设置',
      'settings.loadReadSettingsFailed': '加载阅读器设置失败: @error',
      'settings.defaultDirection': '默认方向',
      'settings.imageSpacing': '图片间距',
      'settings.preloadPages': '预加载页数（在线）',
      'settings.preloadPagesLocal': '预加载页数（本地）',
      'preloadPageCount': '预载图片数量（在线模式）',
      'preloadPageCountInLocalMode': '预载图片数量（本地模式）',
      'preloadDistanceInOnlineMode': '预载距离（在线模式）',
      'preloadDistanceInLocalMode': '预载距离（本地模式）',
      'ScreenHeight': '屏幕',
      'settings.imageRegionWidthRatioHint': '仅影响纵向阅读；适应宽度模式仍使用完整视口宽度。',
      'settings.autoInterval': '自动阅读间隔',
      'settings.fitWidth': '适应宽度',
      'hideScroll2TopButton': '快速回顶按钮',
      'whenScrollUp': '向上滚动时',
      'whenScrollDown': '向下滚动时',
      'never': '从不',
      'always': '总是',
      'preloadGalleryCover': '预载画廊封面',
      'preloadGalleryCoverHint': '预先加载还未显示在页面上的画廊封面',
      'simpleDashboardMode': '精简主页面',
      'simpleDashboardModeHint': '隐藏排行榜和热门模块',
      'showDawnInfo': '展示黎明之时事件',
      'showEncounterMonster': '展示 HV 遭遇战事件',

      // home enhancements
      'home.scrollToTop': '回到顶部',
      'home.imageSearch': '以图搜图',
      'home.imageSearchFailed': '以图搜图失败: @error',
      'home.imageSearchMode': '图搜结果',

      // stats page
      'stats.title': '访问统计',
      'stats.totalVisits': '总访问量: @n',
      'stats.allTime': '全部',
      'stats.year': '年',
      'stats.month': '月',
      'stats.day': '日',
      'stats.period': '周期',
      'stats.ranking': '排名',
      'stats.score': '分数',
      'stats.visits': '访问',
      'stats.hits': '点击',
      'stats.noSeries': '暂无图表数据',

      // usertags
      'usertags.title': '关注 / 隐藏标签',
      'usertags.loadFailed': '加载失败: @error',
      'usertags.add': '添加标签',
      'usertags.tagHint': '格式 namespace:key',
      'usertags.watch': '关注',
      'usertags.hidden': '隐藏',
      'usertags.watchInSet': '选择标签集关注',
      'usertags.hiddenInSet': '选择标签集隐藏',
      'usertags.manage': '管理标签集',
      'usertags.watchAdded': '已添加到关注标签',
      'usertags.hiddenAdded': '已添加到隐藏标签',
      'usertags.defaultTagSet': '默认标签集',
      'usertags.defaultTagSetNone': '无（每次询问）',
      'usertags.none': '未标记',
      'usertags.weight': '权重',
      'usertags.editTitle': '编辑标签',
      'usertags.delete': '删除',
      'usertags.deleteTitle': '删除标签',
      'usertags.deleteConfirm': '确定从当前标签集中删除「@tag」？',
      'usertags.added': '已添加',
      'usertags.updated': '已更新',
      'usertags.deleted': '已删除',
      'usertags.currentList': '已配置标签',
      'usertags.tagColor': '标签颜色',
      'usertags.tagSetColor': '标签集颜色',
      'usertags.changeColor': '更改颜色',
      'usertags.colorDefault': '使用默认颜色',
      'enableDefaultTagSet': '关注标签时使用默认标签集',
      'enableDefaultTagSetHint': '默认直接关注，长按重新选择',
      'disableDefaultTagSetHint': '手动选择',
      'chooseTagSet': '选择标签集',
      'asYourDefault': '作为默认选择',

      // downloads queue
      'downloads.sortBy': '排序',
      'downloads.sortPriority': '优先级',
      'downloads.sortTime': '时间',
      'downloads.sortTitle': '标题',
      'downloads.sortStatus': '状态',
      'downloads.allCategories': '全部分类',
      'downloads.categoryFilter': '站点分类',
      'downloads.setPriority': '优先级',
      'downloads.setGroup': '分组',
      'downloads.priorityLabel': '优先级 @n',
      'downloads.groupLabel': '分组',
      'downloads.defaultGroup': '默认',
      'downloads.groupActions': '分组操作',
      'downloads.renameGroup': '重命名分组',
      'downloads.renameGroupConfirm': '将分组“@group”重命名为：',
      'downloads.groupRenamed': '已重命名 @count 个任务的分组',
      'downloads.clearGroup': '清空分组',
      'downloads.clearGroupConfirm': '将“@group”中的 @count 个任务移回默认分组？',
      'downloads.groupCleared': '已将 @count 个任务移回默认分组',
      'downloads.superseded': '已升级至 gid @gid',
      'downloads.editTask': '编辑任务',
      'downloads.selectTasks': '选择任务',
      'downloads.selectVisible': '选择当前列表任务',
      'downloads.pauseVisible': '暂停当前列表任务',
      'downloads.resumeVisible': '恢复当前列表任务',
      'downloads.reDownloadVisible': '重新下载当前列表画廊',
      'downloads.reUnlockVisible': '重新解锁当前列表归档',
      'downloads.reDownloadConfirm': '删除此画廊已下载文件并重新开始下载？',
      'downloads.reDownloadVisibleConfirm': '删除当前可见的 @count 个画廊文件并重新下载？',
      'downloads.reDownloadBatchConfirm': '删除文件并重新开始 @scope？',
      'downloads.reUnlockArchive': '重新解锁归档',
      'downloads.reUnlockArchiveConfirm': '清空当前归档下载链接并重新解锁？',
      'downloads.changeVisibleGroup': '修改当前列表分组',
      'downloads.changeVisibleGroupConfirm': '将当前可见的 @count 个任务移动到此分组。',
      'downloads.changeBatchGroup': '修改任务分组',
      'downloads.changeBatchGroupConfirm': '将 @scope 移动到此分组。',
      'downloads.changeVisiblePriority': '修改当前列表优先级',
      'downloads.changeBatchPriority': '修改任务优先级',
      'downloads.changeBatchPriorityConfirm': '将 @scope 的优先级改为：',
      'downloads.deleteVisible': '删除当前列表任务',
      'downloads.deleteVisibleConfirm': '请选择如何删除当前可见的 @count 个任务。',
      'downloads.deleteBatchConfirm': '请选择如何删除 @scope。',
      'downloads.visibleTaskCount': '当前可见的 @count 个任务',
      'downloads.selectedTaskCount': '已选择 @count 个任务',
      'downloads.noBatchTargets': '当前列表没有可操作任务',
      'downloads.batchPaused': '已暂停 @count 个任务',
      'downloads.batchResumed': '已恢复 @count 个任务',
      'downloads.batchRedownloaded': '已重新开始 @count 个任务',
      'downloads.batchReUnlocked': '已重新解锁 @count 个归档任务',
      'downloads.batchGroupChanged': '已修改 @count 个任务的分组',
      'downloads.batchPriorityChanged': '已修改 @count 个任务的优先级',
      'downloads.batchDeleted': '已删除 @count 个任务',
      'downloads.failedIssueSummary':
          '发现 @total 个失败任务（画廊 @gallery，归档 @archive）。',
      'downloads.retryFailedGallery': '重试失败画廊',
      'downloads.retryFailedArchive': '重试失败归档',
      'downloads.retryFailed': '重试失败任务',
      'downloads.reUnlockFailedArchive': '重新解锁失败归档',
      'downloads.failedGalleryRetried': '已重试 @count 个失败画廊任务',
      'downloads.failedArchiveRetried': '已重试 @count 个失败归档任务',
      'downloads.failedArchiveReUnlocked': '已重新解锁 @count 个失败归档任务',
      'downloads.issue_hath': '@count 个 H@H/代理失败',
      'downloads.issue_hath_hint': '检查 H@H URL、JH_HATH_PROXY 和反代网络路径。',
      'downloads.issue_quota': '@count 个配额/509 限制',
      'downloads.issue_quota_hint': '等待配额恢复或在 EH 状态页重置图片限制后再重试。',
      'downloads.issue_imagePage': '@count 个图片页解析/下载失败',
      'downloads.issue_imagePage_hint': '通常可直接重试；若持续失败，请跑 H@H 主动测试。',
      'downloads.issue_archiveUnlock': '@count 个归档解锁失败',
      'downloads.issue_archiveUnlock_hint': '重新解锁归档，必要时检查登录 Cookie 和网络代理。',
      'downloads.issue_archiveDownload': '@count 个归档下载/解压失败',
      'downloads.issue_archiveDownload_hint': '重试归档任务；若下载链接过期，先重新解锁。',
      'downloads.issue_archiveBot': '@count 个 Archive Bot 解析失败',
      'downloads.issue_archiveBot_hint':
          '检查 Archive Bot / Archive-at-Home API 地址、API key 和余额，或切回官方归档解析。',
      'downloads.issue_localFile': '@count 个本地文件异常',
      'downloads.issue_localFile_hint': '检查下载目录挂载、权限和 NAS 磁盘状态。',
      'downloads.issue_unknown': '@count 个未知失败',
      'downloads.issue_unknown_hint': '打开排障工作台复制诊断包，并查看最近服务器日志。',

      // detail download dialog
      'detail.startDownloadTitle': '开始下载',
      'detail.downloadGroup': '分组',
      'existingGroup': '现有分组',
      'groupName': '分组名称',
      'detail.downloadPriority': '优先级（越大越优先）',
      'detail.stats': '统计',
      'detail.similarByTitle': '相似标题',
      'detail.upgradeDownload': '更新到新版本',
      'detail.upgradeOk': '已开始下载新版本',
      'detail.upgradeFailed': '升级失败: @error',
      'detail.archiveNewVersionHint': '存在新版本画廊，请在新版页面重新下载归档。',
      'detail.openNewVersion': '打开新版本',
    };
  }
}
