class WebKoKR {
  static Map<String, String> keys() {
    return {
      // common
      'common.cancel': '취소',
      'common.ok': '확인',
      'common.error': '오류',
      'common.success': '성공',
      'common.failed': '실패',
      'common.retry': '재시도',
      'common.delete': '삭제',
      'common.reset': '초기화',
      'common.unknown': '알 수 없음',
      'common.images': '@count장',
      'common.pages': '@count 페이지',

      // setup
      'setup.title': 'JHenTai 서버 설정',
      'setup.description': '서버 로그에 표시된 API 토큰을 입력하여 연결하세요.',
      'setup.tokenLabel': 'API 토큰',
      'setup.connect': '연결',
      'setup.emptyToken': '토큰을 입력하세요',
      'setup.invalidToken': '유효하지 않은 토큰입니다. 서버 로그에서 올바른 토큰을 확인하세요.',

      // home
      'home.title': 'JHenTai',
      'home.search': '갤러리 검색...',
      'home.advancedSearch': '고급 검색',
      'home.downloads': '다운로드',
      'home.localGalleries': '로컬 갤러리',
      'home.settings': '설정',
      'home.subtitle': 'E-Hentai 클라이언트',
      'home.home': '홈',
      'home.popular': '인기',
      'home.favorites': '즐겨찾기',
      'home.watched': '구독',
      'home.noGalleries': '갤러리를 찾을 수 없습니다',
      'home.previous': '이전',
      'home.next': '다음',
      'home.page': '@page 페이지',
      'home.loadFailed': '로드 실패: @error',
      // advanced search
      'home.categoryFilter': '카테고리 필터',
      'home.minimumRating': '최소 평점',
      'home.ratingAny': '전체',
      'home.searchIn': '검색 범위',
      'home.galleryName': '갤러리 이름',
      'home.tags': '태그',
      'home.description': '설명',
      'home.showExpunged': '삭제된 항목 표시',
      'home.applySearch': '적용 및 검색',
      // category names
      'category.doujinshi': '동인지',
      'category.manga': '만화',
      'category.artistCg': '아티스트 CG',
      'category.gameCg': '게임 CG',
      'category.western': '서양',
      'category.nonH': '비-H',
      'category.imageSet': '이미지 세트',
      'category.cosplay': '코스프레',
      'category.asianPorn': '아시안',
      'category.misc': '기타',

      // gallery detail
      'detail.copyUrl': '갤러리 URL 복사',
      'detail.copied': '복사됨',
      'detail.removeFromFav': '즐겨찾기에서 제거',
      'detail.addToFav': '즐겨찾기에 추가',
      'detail.addToFavTitle': '즐겨찾기에 추가',
      'detail.favRemoved': '제거됨',
      'detail.favRemovedMsg': '즐겨찾기에서 제거되었습니다',
      'detail.favAdded': '추가됨',
      'detail.favAddedMsg': '@name에 추가되었습니다',
      'detail.favError': '즐겨찾기 작업 실패: @error',
      'detail.favSlot': '즐겨찾기 @n',
      'detail.rateTitle': '갤러리 평가',
      'detail.rateSubmit': '제출',
      'detail.rated': '평가됨',
      'detail.ratedMsg': '당신의 평점: @rating',
      'detail.rateFailed': '평가 실패: @error',
      'detail.rateLoginRequired': '평가할 수 없음 — 로그인 필요',
      'detail.readOnline': '온라인 보기',
      'detail.downloadGallery': '갤러리 다운로드',
      'detail.archiveResample': '아카이브 (리샘플)',
      'detail.archiveOriginal': '아카이브 (원본)',
      'detail.downloadStarted': '다운로드 시작',
      'detail.galleryQueued': '갤러리 다운로드가 대기열에 추가되었습니다',
      'detail.archiveQueued': '아카이브 다운로드가 대기열에 추가되었습니다',
      'detail.downloadFailed': '다운로드 시작 실패: @error',
      'detail.archiveFailed': '아카이브 다운로드 시작 실패: @error',
      'detail.noArchive': '사용 가능한 아카이브 없음',
      'detail.tags': '태그',
      'detail.comments': '댓글 (@count)',
      'detail.anonymous': '익명',
      'detail.loadFailed': '갤러리 세부 정보 로드 실패: @error',

      // reader
      'reader.loading': '갤러리 로드 중...',
      'reader.loadingImage': '이미지 로드 중...',
      'reader.loadFailed': '갤러리 로드 실패: @error',
      'reader.imageFailed': '이미지 로드 실패',
      'reader.noImages': '이미지가 없습니다',
      'reader.directionLabel': '보기 방향: @dir',
      'reader.ltr': '왼쪽→오른쪽',
      'reader.rtl': '오른쪽→왼쪽',
      'reader.vertical': '세로 스크롤',

      // downloads
      'downloads.title': '다운로드',
      'downloads.gallery': '갤러리',
      'downloads.archive': '아카이브',
      'downloads.noGallery': '갤러리 다운로드 없음',
      'downloads.noArchive': '아카이브 다운로드 없음',
      'downloads.read': '보기',
      'downloads.pause': '일시정지',
      'downloads.resume': '재개',
      'downloads.deleteTitle': '다운로드 삭제',
      'downloads.deleteConfirm': '이 다운로드와 파일을 삭제하시겠습니까?',
      'downloads.loadFailed': '작업 로드 실패: @error',
      // gallery statuses
      'downloads.gStatus0': '없음',
      'downloads.gStatus1': '다운로드 중',
      'downloads.gStatus2': '일시정지',
      'downloads.gStatus3': '완료',
      'downloads.gStatus4': '실패',
      // archive statuses
      'downloads.aStatus0': '없음',
      'downloads.aStatus1': '잠금 해제 중',
      'downloads.aStatus2': 'URL 분석 중',
      'downloads.aStatus3': '다운로드 중',
      'downloads.aStatus4': '다운로드됨',
      'downloads.aStatus5': '압축 해제 중',
      'downloads.aStatus6': '완료',
      'downloads.aStatus7': '일시정지',
      'downloads.aStatus8': '실패',

      // local
      'local.title': '로컬 갤러리',
      'local.noGalleries': '로컬 갤러리를 찾을 수 없습니다',
      'local.helpText': 'Docker 컨테이너에 디렉토리를 마운트하거나\nlocal_gallery 폴더에 갤러리를 넣으세요',
      'local.scanNow': '지금 스캔',
      'local.empty': '비어 있음',
      'local.noImages': '이 갤러리에 이미지가 없습니다',
      'local.loadFailed': '갤러리 이미지 로드 실패: @error',
      'local.loadListFailed': '로컬 갤러리 로드 실패: @error',

      // settings
      'settings.title': '설정',
      'settings.account': '계정',
      'settings.loggedIn': '로그인됨: @user',
      'settings.logout': '로그아웃',
      'settings.logoutSuccess': '로그아웃되었습니다',
      'settings.logoutFailed': '로그아웃 실패: @error',
      'settings.cookieLogin': '쿠키로 로그인 (권장)',
      'settings.cookieHint': 'EH 포럼 로그인은 서버 환경에서 Cloudflare에 의해 차단됩니다. '
          '브라우저에서 로그인한 후 쿠키를 여기에 복사하세요.\n'
          '단계: e-hentai.org 로그인 → F12 → 애플리케이션 → 쿠키 → 아래 값 복사.',
      'settings.cookiePlaceholder': 'ipb_member_id=xxx; ipb_pass_hash=xxx; igneous=xxx',
      'settings.setCookies': '쿠키 설정',
      'settings.cookieSuccess': '쿠키가 설정되었습니다',
      'settings.cookieFailed': '쿠키 설정 실패: @error',
      'settings.cookieEmpty': '쿠키를 붙여넣으세요',
      'settings.credentialLogin': '자격 증명으로 로그인 (Cloudflare로 인해 실패할 수 있음)',
      'settings.username': '사용자 이름',
      'settings.password': '비밀번호',
      'settings.login': '로그인',
      'settings.loginSuccess': '로그인 성공',
      'settings.loginFailed': '로그인 실패',
      'settings.loginError': '로그인 실패: @error',
      'settings.emptyCredentials': '사용자 이름과 비밀번호를 입력하세요',
      'settings.site': '사이트',
      'settings.appearance': '외관',
      'settings.themeMode': '테마 모드',
      'settings.system': '시스템',
      'settings.light': '라이트',
      'settings.dark': '다크',
      'settings.accentColor': '강조 색상',
      'settings.serverInfo': '서버 정보',
      'settings.dataDir': '데이터 디렉토리',
      'settings.downloadDir': '다운로드 디렉토리',
      'settings.localGalleryDir': '로컬 갤러리 디렉토리',
      'settings.extraScanPaths': '추가 스캔 경로',
      'settings.switchSiteFailed': '사이트 전환 실패: @error',
      'settings.language': '언어',

      // history
      'history.title': '방문 기록',
      'history.empty': '방문 기록 없음',
      'history.clearAll': '전체 삭제',
      'history.clearTitle': '방문 기록 삭제',
      'history.clearConfirm': '모든 방문 기록을 삭제하시겠습니까?',
      'history.loadFailed': '방문 기록 로드 실패: @error',

      // search history
      'searchHistory.clearAll': '검색 기록 삭제',

      // comment
      'comment.placeholder': '댓글 작성...',
      'comment.send': '전송',
      'comment.posted': '댓글 게시됨',
      'comment.postedMsg': '댓글이 게시되었습니다',
      'comment.postFailed': '댓글 게시 실패: @error',
      'comment.voteFailed': '투표 실패: @error',

      // ranklist
      'ranklist.title': '랭킹',
      'ranklist.allTime': '역대',
      'ranklist.year': '연간',
      'ranklist.month': '월간',
      'ranklist.yesterday': '어제',

      // thumbnails
      'thumbnails.title': '썸네일 (@count)',
      'thumbnails.grid': '썸네일 그리드',
      'thumbnails.loadFailed': '썸네일 로드 실패: @error',

      // home additions
      'home.history': '방문 기록',
      'home.ranklist': '랭킹',

      // tag translation
      'tagTranslation.title': '태그 번역',
      'tagTranslation.loaded': '@count개 태그 로드됨',
      'tagTranslation.notLoaded': '태그 데이터베이스가 로드되지 않음',
      'tagTranslation.lastUpdate': '마지막 업데이트: @time',
      'tagTranslation.refresh': '태그 데이터베이스 새로고침',
      'tagTranslation.refreshSuccess': '@count개 태그 업데이트됨',
      'tagTranslation.refreshFailed': '새로고침 실패: @error',

      // list mode
      'listMode.toggle': '보기 모드 전환',
      'listMode.grid': '그리드',
      'listMode.list': '목록',
      'listMode.listCompact': '간략 목록',

      // quick search
      'quickSearch.title': '빠른 검색',
      'quickSearch.empty': '저장된 검색 없음',
      'quickSearch.saveCurrent': '현재 검색 저장',
      'quickSearch.saveTitle': '빠른 검색 저장',
      'quickSearch.nameLabel': '이름',

      // tag suggest
      'tagSuggest.tag': '태그',

      // common extras
      'common.save': '저장',

      // reader enhancements
      'reader.fitWidth': '너비 맞춤',
      'reader.doubleColumn': '두 페이지 보기',
      'reader.autoStart': '자동 넘기기',
      'reader.autoStop': '자동 넘기기 중지',

      // block rules
      'blockRule.title': '차단 규칙',
      'blockRule.empty': '차단 규칙이 없습니다',
      'blockRule.add': '규칙 추가',
      'blockRule.edit': '규칙 편집',
      'blockRule.manage': '차단 규칙 관리',
      'blockRule.ruleCount': '@count개 규칙',
      'blockRule.ungrouped': '그룹 없음',
      'blockRule.deleteGroup': '그룹 삭제',
      'blockRule.target': '대상',
      'blockRule.attribute': '속성',
      'blockRule.pattern': '패턴',
      'blockRule.expression': '표현식',
      'blockRule.expressionHint': '일치할 값',
      'blockRule.groupId': '그룹 ID',
      'blockRule.groupIdHint': '선택적 그룹 이름',
      'blockRule.blocked': '차단됨',
      'blockRule.tagBlocked': '태그 "@tag"가 차단되었습니다',
      'blockRule.uploaderBlocked': '업로더 "@uploader"가 차단되었습니다',
      'blockRule.blockTag': '이 태그 차단',
      'blockRule.blockUploader': '이 업로더 차단',

      // download enhancements
      'downloads.search': '다운로드 검색...',
      'downloads.allGroups': '모든 그룹',
      'downloads.group': '그룹',

      // tag voting
      'tagVote.search': '검색',
      'tagVote.searchUploader': '업로더 검색',
      'tagVote.voteUp': '추천',
      'tagVote.voteDown': '비추천',
      'tagVote.success': '투표 완료',
      'tagVote.votedUp': '"@tag"에 추천했습니다',
      'tagVote.votedDown': '"@tag"에 비추천했습니다',
      'tagVote.failed': '투표 실패: @error',
    };
  }
}
