class WebZhTW {
  static Map<String, String> keys() {
    return {
      // common
      'common.cancel': '取消',
      'common.ok': '確定',
      'common.confirm': '確定',
      'common.error': '錯誤',
      'common.success': '成功',
      'common.failed': '失敗',
      'common.retry': '重試',
      'common.delete': '刪除',
      'common.reset': '重設',
      'common.unknown': '未知',
      'common.images': '@count 張圖片',
      'common.pages': '@count 頁',

      'share': '分享',
      'save': '儲存',
      'reload': '重新載入',
      'cancel': '取消',
      'resampleImage': '壓縮圖',
      'originalImage': '原圖',
      'reDownload': '重新下載',
      'hasCopiedToClipboard': '已複製到剪貼簿',
      'displayFirstPageAlone': '單獨顯示首頁',

      // setup
      'setup.title': 'JHenTai 伺服器設定',
      'setup.description': '請輸入伺服器記錄中顯示的 API Token 以連線。',
      'setup.tokenLabel': 'API Token',
      'setup.connect': '連線',
      'setup.emptyToken': '請輸入 Token',
      'setup.invalidToken': 'Token 無效，請查看伺服器記錄取得正確的 Token。',
      'setup.tokenHint': 'Token 為一行共 64 位十六進位字元，請完整複製記錄中的整行，不要只複製前半段。',
      'setup.tokenPasteHint': '請貼上記錄中的完整 64 位 Token',
      'setup.tokenCharCount': '已輸入 @current / @total 位',
      'setup.tokenWrongLength': 'Token 必須為 64 位十六進位字元（請從 docker logs 完整複製一行）。',
      'setup.tokenHelpTitle': '如何從記錄中查找 Token',
      'setup.tokenHelpP1': '在執行 Docker 的主機上開啟終端機，執行：',
      'setup.tokenHelpP2':
          '找到以 [JHenTai] API token for web UI 開頭的那一行，複製冒號後的 64 位十六進位字元（整段 Token，不要截斷）。若容器名稱不是 jhentai，請將下方指令中的名稱改為你的容器名稱。',
      'setup.tokenHelpAlt': '若沒有該行，可從伺服器資料庫讀取（預設容器名 jhentai，資料目錄 /data）：',

      // home
      'home.title': 'JHenTai',
      'home.search': '搜尋畫廊...',
      'home.advancedSearch': '進階搜尋',
      'home.searchFilterSheetTitle': '分類與篩選',
      'home.leftPaneWidthPx': '@w px',
      'home.twoPaneDividerTooltip': '左欄 @w px · 雙擊分隔條恢復預設寬度',
      'home.downloads': '下載',
      'home.localGalleries': '本機畫廊',
      'home.settings': '設定',
      'home.subtitle': 'E-Hentai 客戶端',
      'home.home': '首頁',
      'home.popular': '熱門',
      'home.favorites': '收藏',
      'home.watched': '關注',
      'home.noGalleries': '未找到畫廊',
      'home.previous': '上一頁',
      'home.next': '下一頁',
      'home.page': '第 @page 頁',
      'home.loadFailed': '載入失敗: @error',
      'home.favSortTitle': '收藏排序',
      'home.favSortFavorited': '依收藏時間',
      'home.favSortPublished': '依發布時間',
      'home.favAllFolders': '全部',
      'home.favSlotShort': '資料夾 @n',
      'home.categoryFilter': '分類篩選',
      'home.minimumRating': '最低評分',
      'home.ratingAny': '不限',
      'home.searchIn': '搜尋範圍',
      'home.galleryName': '畫廊名稱',
      'home.tags': '標籤',
      'home.description': '描述',
      'home.showExpunged': '顯示已刪除',
      'home.language': '語言',
      'home.languageNone': '無',
      'home.disableFilterForLanguage': '停用語言過濾',
      'home.applySearch': '套用並搜尋',
      'home.history': '瀏覽記錄',
      'home.ranklist': '排行榜',

      // category names
      'category.doujinshi': '同人誌',
      'category.manga': '漫畫',
      'category.artistCg': '插畫',
      'category.gameCg': '遊戲CG',
      'category.western': '西方',
      'category.nonH': '非H',
      'category.imageSet': '圖集',
      'category.cosplay': 'Cosplay',
      'category.asianPorn': '亞洲',
      'category.misc': '雜項',

      // gallery detail
      'detail.copyUrl': '複製畫廊連結',
      'detail.copied': '已複製',
      'detail.removeFromFav': '從收藏中移除',
      'detail.addToFav': '新增至收藏',
      'detail.addToFavTitle': '新增至收藏',
      'detail.favRemoved': '已移除',
      'detail.favRemovedMsg': '已從收藏中移除',
      'detail.favAdded': '已新增',
      'detail.favAddedMsg': '已新增至 @name',
      'detail.favError': '收藏操作失敗: @error',
      'detail.favSlot': '收藏夾 @n',
      'detail.favNoteHint': '收藏備註（選填）',
      'detail.favQuickAddTooltip': '加入預設收藏夾（長按）',
      'detail.rateTitle': '為畫廊評分',
      'detail.rateSubmit': '提交',
      'detail.rated': '已評分',
      'detail.ratedMsg': '你的評分: @rating',
      'detail.rateFailed': '評分失敗: @error',
      'detail.rateLoginRequired': '無法評分 — 需要登入',
      'detail.readOnline': '線上閱讀',
      'detail.downloadGallery': '下載畫廊',
      'detail.archiveResample': '封存（壓縮）',
      'detail.archiveOriginal': '封存（原圖）',
      'detail.downloadStarted': '下載已開始',
      'detail.galleryQueued': '畫廊下載已加入佇列',
      'detail.archiveQueued': '封存下載已加入佇列',
      'detail.downloadFailed': '下載失敗: @error',
      'detail.archiveFailed': '封存下載失敗: @error',
      'detail.noArchive': '沒有可用的封存',
      'detail.tags': '標籤',
      'detail.comments': '評論 (@count)',
      'detail.anonymous': '匿名',
      'detail.loadFailed': '載入畫廊詳情失敗: @error',

      // reader
      'reader.loading': '載入畫廊中...',
      'reader.loadingImage': '載入圖片中...',
      'reader.loadFailed': '載入畫廊失敗: @error',
      'reader.imageFailed': '圖片載入失敗',
      'reader.noImages': '沒有提供圖片',
      'reader.directionLabel': '閱讀方向: @dir',
      'reader.ltr': '從左到右',
      'reader.rtl': '從右到左',
      'reader.vertical': '上下捲動',
      'reader.wheelAction': '圖片上的滑鼠滾輪',
      'reader.wheelActionPage': '翻頁',
      'reader.wheelActionZoom': '縮放圖片',
      'reader.wheelActionVerticalHint': '直向與適應寬度模式一律捲動清單；本選項僅適用於由左至右、由右至左與雙頁模式。',
      'reader.wheelInvertPageTurn': '反轉滾輪翻頁方向',
      'reader.wheelInvertPageTurnSubtitle': '交換滾輪／觸控板捲動時「下一頁」與「上一頁」的對應方向。',

      // downloads
      'downloads.title': '下載',
      'downloads.gallery': '畫廊',
      'downloads.archive': '封存',
      'downloads.noGallery': '沒有畫廊下載',
      'downloads.noArchive': '沒有封存下載',
      'downloads.read': '閱讀',
      'downloads.pause': '暫停',
      'downloads.resume': '繼續',
      'downloads.deleteTitle': '刪除下載',
      'downloads.deleteConfirm': '刪除此下載及其檔案？',
      'downloads.loadFailed': '載入任務失敗: @error',
      'downloads.gStatus0': '無',
      'downloads.gStatus1': '下載中',
      'downloads.gStatus2': '已暫停',
      'downloads.gStatus3': '已完成',
      'downloads.gStatus4': '失敗',
      'downloads.aStatus0': '無',
      'downloads.aStatus1': '解鎖中',
      'downloads.aStatus2': '解析連結',
      'downloads.aStatus3': '下載中',
      'downloads.aStatus4': '已下載',
      'downloads.aStatus5': '解壓中',
      'downloads.aStatus6': '已完成',
      'downloads.aStatus7': '已暫停',
      'downloads.aStatus8': '失敗',

      // local
      'local.title': '本機畫廊',
      'local.noGalleries': '未找到本機畫廊',
      'local.helpText': '將目錄掛載到 Docker 容器中\n或將畫廊放入 local_gallery 資料夾',
      'local.scanNow': '立即掃描',
      'local.empty': '空',
      'local.noImages': '此畫廊中沒有圖片',
      'local.loadFailed': '載入畫廊圖片失敗: @error',
      'local.loadListFailed': '載入本機畫廊失敗: @error',

      // settings
      'settings.title': '設定',
      'settings.account': '帳號',
      'settings.loggedIn': '已登入: @user',
      'settings.logout': '登出',
      'settings.logoutSuccess': '已登出',
      'settings.logoutFailed': '登出失敗: @error',
      'settings.cookieLogin': '使用 Cookie 登入（建議）',
      'settings.cookieHint': 'EH 論壇登入在伺服器環境中被 Cloudflare 攔截。'
          '請在瀏覽器中登入後複製 Cookie 到此處。\n'
          '步驟: 登入 e-hentai.org → F12 → 應用程式 → Cookie → 複製以下值。',
      'settings.cookiePlaceholder': 'ipb_member_id=xxx; ipb_pass_hash=xxx; igneous=xxx',
      'settings.setCookies': '設定 Cookie',
      'settings.cookieSuccess': 'Cookie 設定成功',
      'settings.cookieFailed': '設定 Cookie 失敗: @error',
      'settings.cookieEmpty': '請貼上 Cookie',
      'settings.credentialLogin': '使用帳號密碼登入（可能因 Cloudflare 失敗）',
      'settings.username': '使用者名稱',
      'settings.password': '密碼',
      'settings.login': '登入',
      'settings.loginSuccess': '登入成功',
      'settings.loginFailed': '登入失敗',
      'settings.loginError': '登入失敗: @error',
      'settings.emptyCredentials': '請輸入使用者名稱和密碼',
      'settings.site': '站點',
      'settings.appearance': '外觀',
      'settings.themeMode': '主題模式',
      'settings.system': '跟隨系統',
      'settings.light': '淺色',
      'settings.dark': '深色',
      'settings.accentColor': '主題色',
      'settings.serverInfo': '伺服器資訊',
      'settings.dataDir': '資料目錄',
      'settings.downloadDir': '下載目錄',
      'settings.localGalleryDir': '本機畫廊目錄',
      'settings.extraScanPaths': '額外掃描路徑',
      'settings.switchSiteFailed': '切換站點失敗: @error',
      'settings.language': '語言',
      'settings.sectionData': '資料與工具',
      'settings.sectionStyle': '樣式',
      'settings.sectionRead': '閱讀',
      'settings.sectionTags': '標籤與過濾',
      'settings.sectionOther': '其他',
      'settings.openDownloads': '下載任務',
      'settings.openHistory': '瀏覽記錄',
      'settings.openLocal': '本機畫廊',
      'settings.openQuickSearch': '快速搜尋',
      'settings.networkNote': '網路與代理',
      'settings.networkWebBody': '代理等網路選項在伺服器或 Docker 環境中設定，不在此網頁內。部署說明見文件（反向代理、HTTPS、Cookie 登入等）。',
      'settings.about': '關於',
      'settings.appVersion': '版本 @version（@build）',
      'settings.hubMenu': '設定選單',
      'settings.menuWebDocker': '網頁與伺服器',
      'settings.menuWebDockerSubtitle': '下載捷徑、Docker 路徑、網路／代理說明，以及效能與安全提示（僅 Web 版）。',
      'settings.menuEH': 'E-Hentai',
      'settings.menuStyle': '樣式',
      'settings.menuRead': '閱讀',
      'settings.menuPreference': '偏好',
      'settings.menuNetwork': '網路',
      'settings.menuDownload': '下載',
      'settings.menuPerformance': '效能',
      'settings.menuMouseWheel': '滑鼠滾輪',
      'settings.menuAdvanced': '進階',
      'settings.menuSecurity': '安全性',
      'settings.ehRequiresLogin': '請先在「帳號」登入後再變更站台與 Cookie 狀態。',
      'settings.ehWebMoreSoon': '畫廊檔案、配額、我的標籤等將在伺服器 API 就緒後逐步提供。',
      'settings.styleWebMoreSoon': '列表版面等選項可能在後續版本加入。',
      'settings.networkWebStub': '單次請求代理、網域前置、逾時等暫不可在此介面設定。',
      'settings.downloadWebStub': '進行中與已完成的下載請在「下載工作」頁管理；進階下載選項尚未在網頁端開放。',
      'settings.performanceWebStub': 'CPU、記憶體等效能調校針對原生用戶端；網頁端在瀏覽器中執行。',
      'settings.advancedWebStub': '桌面端的日誌與實驗性功能在網頁端不可用。',
      'settings.securityWebStub': '首次連線時使用了 API Token。更換 Token 請更新伺服器後在設定精靈貼上新 Token，或清除網站資料後重新連線。',
      'settings.mouseWheelIntro': '選擇閱讀器中滑鼠滾輪在圖片上的行為（橫向翻頁模式）。',
      'settings.mouseWheelReadHint': '閱讀方向、預載入等全部選項',
      'settings.aboutVersionLabel': '版本',
      'settings.aboutAuthorLabel': '作者',
      'settings.aboutTelegramTitle': 'Telegram（主要為中文）',
      'settings.aboutTelegramHint': '社群連結',
      'settings.aboutQA': '問答',
      'settings.aboutWebForkNote': '本網頁介面由 JHenTai Docker 分支提供；上游專案見上方連結。',

      // history
      'history.title': '瀏覽記錄',
      'history.empty': '暫無瀏覽記錄',
      'history.clearAll': '清除全部',
      'history.clearTitle': '清除瀏覽記錄',
      'history.clearConfirm': '確定要清除所有瀏覽記錄嗎？',
      'history.loadFailed': '載入瀏覽記錄失敗: @error',

      // search history
      'searchHistory.clearAll': '清除搜尋記錄',

      // comment
      'comment.placeholder': '寫下評論...',
      'comment.send': '傳送',
      'comment.posted': '評論已傳送',
      'comment.postedMsg': '你的評論已發佈',
      'comment.postFailed': '傳送評論失敗: @error',
      'comment.voteFailed': '投票失敗: @error',

      // ranklist
      'ranklist.title': '排行榜',
      'ranklist.allTime': '歷史總榜',
      'ranklist.year': '年度',
      'ranklist.month': '月度',
      'ranklist.yesterday': '昨日',

      // thumbnails
      'thumbnails.title': '縮圖 (@count)',
      'thumbnails.grid': '縮圖網格',
      'thumbnails.loadFailed': '載入縮圖失敗: @error',

      // tag translation
      'tagTranslation.title': '標籤翻譯',
      'tagTranslation.loaded': '已載入 @count 個標籤',
      'tagTranslation.notLoaded': '標籤資料庫未載入',
      'tagTranslation.lastUpdate': '最後更新: @time',
      'tagTranslation.refresh': '更新標籤資料庫',
      'tagTranslation.refreshSuccess': '已更新 @count 個標籤',
      'tagTranslation.refreshFailed': '更新失敗: @error',

      // list mode
      'listMode.toggle': '切換顯示模式',
      'listMode.grid': '網格',
      'listMode.list': '列表',
      'listMode.listCompact': '緊湊列表',

      // quick search
      'quickSearch.title': '快速搜尋',
      'quickSearch.empty': '沒有已儲存的搜尋',
      'quickSearch.saveCurrent': '儲存目前搜尋',
      'quickSearch.saveTitle': '儲存快速搜尋',
      'quickSearch.nameLabel': '名稱',
      'quickSearch.addNew': '新增快速搜尋',
      'quickSearch.keywordLabel': '關鍵字',
      'quickSearch.keywordHint': '與首頁搜尋欄相同',
      'quickSearch.saved': '已儲存',
      'quickSearch.deleted': '已刪除',
      'quickSearch.deleteTitle': '刪除快速搜尋',
      'quickSearch.deleteConfirm': '確定刪除「@name」？',

      // tag suggest
      'tagSuggest.tag': '標籤',

      // common extras
      'common.save': '儲存',

      // reader enhancements
      'reader.fitWidth': '適應寬度',
      'reader.doubleColumn': '雙頁模式',
      'reader.autoStart': '自動閱讀',
      'reader.autoStop': '停止自動閱讀',

      // block rules
      'blockRule.title': '封鎖規則',
      'blockRule.empty': '沒有設定封鎖規則',
      'blockRule.add': '新增規則',
      'blockRule.edit': '編輯規則',
      'blockRule.manage': '管理封鎖規則',
      'blockRule.ruleCount': '@count 條規則',
      'blockRule.ungrouped': '未分組',
      'blockRule.deleteGroup': '刪除分組',
      'blockRule.target': '目標',
      'blockRule.attribute': '屬性',
      'blockRule.pattern': '匹配模式',
      'blockRule.expression': '運算式',
      'blockRule.expressionHint': '要匹配的值',
      'blockRule.groupId': '分組 ID',
      'blockRule.groupIdHint': '選填的分組名稱',
      'blockRule.blocked': '已封鎖',
      'blockRule.tagBlocked': '標籤 "@tag" 已被封鎖',
      'blockRule.uploaderBlocked': '上傳者 "@uploader" 已被封鎖',
      'blockRule.blockTag': '封鎖此標籤',
      'blockRule.blockUploader': '封鎖此上傳者',

      // download enhancements
      'downloads.search': '搜尋下載...',
      'downloads.allGroups': '所有分組',
      'downloads.group': '分組',

      // tag voting
      'tagVote.search': '搜尋',
      'tagVote.searchUploader': '搜尋上傳者',
      'tagVote.voteUp': '投贊成票',
      'tagVote.voteDown': '投反對票',
      'tagVote.success': '已投票',
      'tagVote.votedUp': '已為 "@tag" 投贊成票',
      'tagVote.votedDown': '已為 "@tag" 投反對票',
      'tagVote.failed': '投票失敗: @error',

      // responsive layout
      'home.selectGallery': '選擇一個畫廊查看詳情',

      // gallery detail extras
      'detail.parentGallery': '父畫廊',
      'detail.newerVersion': '有更新版本',

      // settings extras
      'settings.cookieStatusFull': 'Cookie 正常（包含 igneous — 可存取 EX）',
      'settings.cookieStatusNoIgneous': 'Cookie 已設定但缺少 igneous — EX 可能無法使用',
      'settings.cookieStatusNone': '未設定登入 Cookie',
      'settings.siteSwitched': '已切換到 @site',

      // download progress in detail
      'detail.completed': '已完成',
      'detail.retryDownload': '重試',
      'detail.readDownloaded': '閱讀已下載',
      'detail.deleteDownload': '刪除下載',
      'detail.deleteDownloadConfirm': '刪除此下載及其檔案？',
      'detail.archiveCompleted': '歸檔就緒',

      // detail enhancements
      'detail.share': '分享',
      'detail.jumpToPage': '跳轉到頁',
      'detail.similarSearch': '相似搜尋',
      'detail.blockGallery': '封鎖畫廊',
      'detail.allComments': '全部評論',
      'detail.thumbnails': '縮圖 (@count)',
      'detail.viewAllThumbnails': '查看全部縮圖',
      'detail.galleryBlocked': '畫廊已被封鎖',
      'detail.jumpPageHint': '輸入頁碼 (1-@max)',

      // reader enhancements
      'reader.saveImage': '儲存圖片',
      'reader.openInNewTab': '在新標籤頁開啟',
      'reader.reloadImage': '重新載入',
      'reader.interval': '間隔',
      'reader.preload': '預載入',
      'reader.imageSpacing': '圖片間距',
      'reader.autoInterval': '自動閱讀間隔',
      'reader.startAutoMode': '開始',
      'reader.saveFailed': '無法儲存圖片',
      'reader.redownloadHint': '請開啟「下載」頁面重試或重新開始此畫廊下載。',
      'reader.deviceOrientation': '裝置方向',
      'reader.deviceOrientationWebHint':
          '網頁版無法像應用程式一樣鎖定螢幕方向。請使用瀏覽器全螢幕或系統旋轉鎖定。',

      // settings reader
      'settings.defaultFavoriteSlot': '預設收藏夾',
      'settings.defaultFavoriteNone': '無（每次詢問）',
      'settings.readerSettings': '閱讀器設定',
      'settings.defaultDirection': '預設方向',
      'settings.imageSpacing': '圖片間距',
      'settings.preloadPages': '預載入頁數',
      'settings.autoInterval': '自動閱讀間隔',
      'settings.fitWidth': '適應寬度',

      // home enhancements
      'home.scrollToTop': '回到頂部',
      'home.imageSearch': '以圖搜圖',
      'home.imageSearchFailed': '以圖搜圖失敗: @error',
      'home.imageSearchMode': '圖搜結果',

      'stats.title': '造訪統計',
      'stats.totalVisits': '總造訪: @n',
      'stats.allTime': '全部',
      'stats.year': '年',
      'stats.month': '月',
      'stats.day': '日',
      'stats.period': '週期',
      'stats.ranking': '排名',
      'stats.score': '分數',
      'stats.visits': '造訪',
      'stats.hits': '點擊',
      'stats.noSeries': '暫無圖表資料',

      'usertags.title': '關注 / 隱藏標籤',
      'usertags.loadFailed': '載入失敗: @error',
      'usertags.add': '新增標籤',
      'usertags.tagHint': '格式 namespace:key',
      'usertags.watch': '關注',
      'usertags.hidden': '隱藏',
      'usertags.delete': '刪除',
      'usertags.added': '已新增',
      'usertags.deleted': '已刪除',
      'usertags.currentList': '已設定標籤',

      'downloads.sortBy': '排序',
      'downloads.sortPriority': '優先級',
      'downloads.sortTime': '時間',
      'downloads.sortTitle': '標題',
      'downloads.sortStatus': '狀態',
      'downloads.setPriority': '優先級',
      'downloads.setGroup': '分組',
      'downloads.priorityLabel': '優先級 @n',
      'downloads.groupLabel': '分組',
      'downloads.superseded': '已升級至 gid @gid',
      'downloads.editTask': '編輯任務',

      'detail.startDownloadTitle': '開始下載',
      'detail.downloadGroup': '分組',
      'detail.downloadPriority': '優先級（越大越優先）',
      'detail.stats': '統計',
      'detail.similarByTitle': '相似標題',
      'detail.upgradeDownload': '更新到新版本',
      'detail.upgradeOk': '已開始下載新版本',
      'detail.upgradeFailed': '升級失敗: @error',
      'detail.archiveNewVersionHint': '存在新版本畫廊，請在新版頁面重新下載歸檔。',
      'detail.openNewVersion': '開啟新版本',

      'settings.usertags': '關注 / 隱藏標籤',
    };
  }
}
