class WebPtBR {
  static Map<String, String> keys() {
    return {
      // common
      'common.cancel': 'Cancelar',
      'common.ok': 'OK',
      'common.error': 'Erro',
      'common.success': 'Sucesso',
      'common.failed': 'Falhou',
      'common.retry': 'Tentar novamente',
      'common.delete': 'Excluir',
      'common.reset': 'Redefinir',
      'common.unknown': 'Desconhecido',
      'common.images': '@count imagens',
      'common.pages': '@count páginas',

      // setup
      'setup.title': 'Configuração do Servidor JHenTai',
      'setup.description': 'Insira o token API mostrado nos logs do servidor para conectar.',
      'setup.tokenLabel': 'Token API',
      'setup.connect': 'Conectar',
      'setup.emptyToken': 'Por favor, insira um token',
      'setup.invalidToken': 'Token inválido. Verifique os logs do servidor para o token correto.',
      'setup.tokenHint': 'O token tem 64 caracteres hex em uma linha — copie a linha inteira.',
      'setup.tokenPasteHint': 'Cole o token completo de 64 caracteres dos logs',
      'setup.tokenCharCount': '@current / @total caracteres',
      'setup.tokenWrongLength': 'O token deve ter exatamente 64 caracteres hexadecimais (linha completa do docker logs).',
      'setup.tokenHelpTitle': 'Como encontrar o token nos logs',
      'setup.tokenHelpP1': 'No host onde o Docker está em execução, abra um terminal e execute:',
      'setup.tokenHelpP2':
          'Procure a linha que começa com [JHenTai] API token for web UI. Copie os 64 caracteres hexadecimais após os dois pontos (o token inteiro em uma linha). Se o nome do contêiner não for jhentai, substitua nos comandos abaixo.',
      'setup.tokenHelpAlt': 'Se essa linha não existir, leia o token no banco de dados do servidor (nome padrão do contêiner jhentai, diretório de dados /data):',

      // home
      'home.title': 'JHenTai',
      'home.search': 'Pesquisar galerias...',
      'home.advancedSearch': 'Pesquisa avançada',
      'home.searchFilterSheetTitle': 'Categorias e filtros',
      'home.leftPaneWidthPx': '@w px',
      'home.twoPaneDividerTooltip': 'Painel esquerdo @w px · clique duas vezes no divisor para largura padrão',
      'home.downloads': 'Downloads',
      'home.localGalleries': 'Galerias Locais',
      'home.settings': 'Configurações',
      'home.subtitle': 'Cliente E-Hentai',
      'home.home': 'Início',
      'home.popular': 'Popular',
      'home.favorites': 'Favoritos',
      'home.watched': 'Acompanhados',
      'home.noGalleries': 'Nenhuma galeria encontrada',
      'home.previous': 'Anterior',
      'home.next': 'Próximo',
      'home.page': 'Página @page',
      'home.loadFailed': 'Falha ao carregar: @error',
      'home.favSortTitle': 'Ordenação dos favoritos',
      'home.favSortFavorited': 'Por data de favorito',
      'home.favSortPublished': 'Por data de publicação',
      'home.favAllFolders': 'Todas',
      'home.favSlotShort': 'Pasta @n',
      'home.categoryFilter': 'Filtro de Categoria',
      'home.minimumRating': 'Avaliação Mínima',
      'home.ratingAny': 'Qualquer',
      'home.searchIn': 'Pesquisar em',
      'home.galleryName': 'Nome da Galeria',
      'home.tags': 'Tags',
      'home.description': 'Descrição',
      'home.showExpunged': 'Mostrar Excluídos',
      'home.language': 'Language',
      'home.languageNone': 'None',
      'home.disableFilterForLanguage': 'Disable language filter',
      'home.applySearch': 'Aplicar e Pesquisar',
      'home.history': 'Histórico',
      'home.ranklist': 'Ranking',

      // category names
      'category.doujinshi': 'Doujinshi',
      'category.manga': 'Manga',
      'category.artistCg': 'CG de Artista',
      'category.gameCg': 'CG de Jogo',
      'category.western': 'Ocidental',
      'category.nonH': 'Non-H',
      'category.imageSet': 'Conjunto de Imagens',
      'category.cosplay': 'Cosplay',
      'category.asianPorn': 'Asiático',
      'category.misc': 'Diversos',

      // gallery detail
      'detail.copyUrl': 'Copiar URL da galeria',
      'detail.copied': 'Copiado',
      'detail.removeFromFav': 'Remover dos favoritos',
      'detail.addToFav': 'Adicionar aos favoritos',
      'detail.addToFavTitle': 'Adicionar aos favoritos',
      'detail.favRemoved': 'Removido',
      'detail.favRemovedMsg': 'Removido dos favoritos',
      'detail.favAdded': 'Adicionado',
      'detail.favAddedMsg': 'Adicionado a @name',
      'detail.favError': 'Operação de favoritos falhou: @error',
      'detail.favSlot': 'Favoritos @n',
      'detail.favNoteHint': 'Nota (opcional)',
      'detail.favQuickAddTooltip': 'Adicionar à pasta padrão (pressione longo)',
      'detail.rateTitle': 'Avaliar esta galeria',
      'detail.rateSubmit': 'Enviar',
      'detail.rated': 'Avaliado',
      'detail.ratedMsg': 'Sua avaliação: @rating',
      'detail.rateFailed': 'Falha na avaliação: @error',
      'detail.rateLoginRequired': 'Não é possível avaliar — login necessário',
      'detail.readOnline': 'Ler Online',
      'detail.downloadGallery': 'Baixar Galeria',
      'detail.archiveResample': 'Arquivo (Comprimido)',
      'detail.archiveOriginal': 'Arquivo (Original)',
      'detail.downloadStarted': 'Download Iniciado',
      'detail.galleryQueued': 'Download da galeria foi enfileirado',
      'detail.archiveQueued': 'Download do arquivo foi enfileirado',
      'detail.downloadFailed': 'Falha ao iniciar download: @error',
      'detail.archiveFailed': 'Falha ao iniciar download do arquivo: @error',
      'detail.noArchive': 'Nenhum arquivo disponível',
      'detail.tags': 'Tags',
      'detail.comments': 'Comentários (@count)',
      'detail.anonymous': 'Anônimo',
      'detail.loadFailed': 'Falha ao carregar detalhes da galeria: @error',

      // reader
      'reader.loading': 'Carregando galeria...',
      'reader.loadingImage': 'Carregando imagem...',
      'reader.loadFailed': 'Falha ao carregar galeria: @error',
      'reader.imageFailed': 'Falha ao carregar imagem',
      'reader.noImages': 'Nenhuma imagem fornecida',
      'reader.directionLabel': 'Direção de leitura: @dir',
      'reader.ltr': 'Esquerda→Direita',
      'reader.rtl': 'Direita→Esquerda',
      'reader.vertical': 'Vertical',

      // downloads
      'downloads.title': 'Downloads',
      'downloads.gallery': 'Galeria',
      'downloads.archive': 'Arquivo',
      'downloads.noGallery': 'Sem downloads de galeria',
      'downloads.noArchive': 'Sem downloads de arquivo',
      'downloads.read': 'Ler',
      'downloads.pause': 'Pausar',
      'downloads.resume': 'Retomar',
      'downloads.deleteTitle': 'Excluir Download',
      'downloads.deleteConfirm': 'Excluir este download e seus arquivos?',
      'downloads.loadFailed': 'Falha ao carregar tarefas: @error',
      'downloads.gStatus0': 'Nenhum',
      'downloads.gStatus1': 'Baixando',
      'downloads.gStatus2': 'Pausado',
      'downloads.gStatus3': 'Concluído',
      'downloads.gStatus4': 'Falhou',
      'downloads.aStatus0': 'Nenhum',
      'downloads.aStatus1': 'Desbloqueando',
      'downloads.aStatus2': 'Analisando URL',
      'downloads.aStatus3': 'Baixando',
      'downloads.aStatus4': 'Baixado',
      'downloads.aStatus5': 'Descompactando',
      'downloads.aStatus6': 'Concluído',
      'downloads.aStatus7': 'Pausado',
      'downloads.aStatus8': 'Falhou',

      // local
      'local.title': 'Galerias Locais',
      'local.noGalleries': 'Nenhuma galeria local encontrada',
      'local.helpText': 'Monte diretórios no contêiner Docker\nou coloque galerias na pasta local_gallery',
      'local.scanNow': 'Escanear Agora',
      'local.empty': 'Vazio',
      'local.noImages': 'Nenhuma imagem encontrada nesta galeria',
      'local.loadFailed': 'Falha ao carregar imagens: @error',
      'local.loadListFailed': 'Falha ao carregar galerias locais: @error',

      // settings
      'settings.title': 'Configurações',
      'settings.account': 'Conta',
      'settings.loggedIn': 'Conectado como: @user',
      'settings.logout': 'Sair',
      'settings.logoutSuccess': 'Desconectado',
      'settings.logoutFailed': 'Falha ao sair: @error',
      'settings.cookieLogin': 'Login com cookies (recomendado)',
      'settings.cookieHint': 'O login no fórum EH é bloqueado pelo Cloudflare em ambientes de servidor. '
          'Faça login pelo navegador e copie os cookies aqui.\n'
          'Passos: Login em e-hentai.org → F12 → Aplicação → Cookies → copie os valores abaixo.',
      'settings.cookiePlaceholder': 'ipb_member_id=xxx; ipb_pass_hash=xxx; igneous=xxx',
      'settings.setCookies': 'Definir Cookies',
      'settings.cookieSuccess': 'Cookies definidos com sucesso',
      'settings.cookieFailed': 'Falha ao definir cookies: @error',
      'settings.cookieEmpty': 'Por favor, cole os cookies',
      'settings.credentialLogin': 'Login com credenciais (pode falhar devido ao Cloudflare)',
      'settings.username': 'Usuário',
      'settings.password': 'Senha',
      'settings.login': 'Entrar',
      'settings.loginSuccess': 'Login bem-sucedido',
      'settings.loginFailed': 'Falha no login',
      'settings.loginError': 'Falha no login: @error',
      'settings.emptyCredentials': 'Por favor, insira usuário e senha',
      'settings.site': 'Site',
      'settings.appearance': 'Aparência',
      'settings.themeMode': 'Modo de Tema',
      'settings.system': 'Sistema',
      'settings.light': 'Claro',
      'settings.dark': 'Escuro',
      'settings.accentColor': 'Cor de Destaque',
      'settings.serverInfo': 'Informações do Servidor',
      'settings.dataDir': 'Diretório de Dados',
      'settings.downloadDir': 'Diretório de Downloads',
      'settings.localGalleryDir': 'Dir. Galerias Locais',
      'settings.extraScanPaths': 'Caminhos Extras de Scan',
      'settings.switchSiteFailed': 'Falha ao trocar site: @error',
      'settings.language': 'Idioma',

      // history
      'history.title': 'Histórico',
      'history.empty': 'Sem histórico de navegação',
      'history.clearAll': 'Limpar Tudo',
      'history.clearTitle': 'Limpar Histórico',
      'history.clearConfirm': 'Tem certeza que deseja limpar todo o histórico?',
      'history.loadFailed': 'Falha ao carregar histórico: @error',

      // search history
      'searchHistory.clearAll': 'Limpar histórico de pesquisa',

      // comment
      'comment.placeholder': 'Escreva um comentário...',
      'comment.send': 'Enviar',
      'comment.posted': 'Comentário Publicado',
      'comment.postedMsg': 'Seu comentário foi publicado',
      'comment.postFailed': 'Falha ao publicar comentário: @error',
      'comment.voteFailed': 'Falha ao votar: @error',

      // ranklist
      'ranklist.title': 'Ranking',
      'ranklist.allTime': 'Todos os Tempos',
      'ranklist.year': 'Último Ano',
      'ranklist.month': 'Último Mês',
      'ranklist.yesterday': 'Ontem',

      // thumbnails
      'thumbnails.title': 'Miniaturas (@count)',
      'thumbnails.grid': 'Grade de Miniaturas',
      'thumbnails.loadFailed': 'Falha ao carregar miniaturas: @error',

      // tag translation
      'tagTranslation.title': 'Tradução de Tags',
      'tagTranslation.loaded': '@count tags carregadas',
      'tagTranslation.notLoaded': 'Banco de tags não carregado',
      'tagTranslation.lastUpdate': 'Última atualização: @time',
      'tagTranslation.refresh': 'Atualizar Banco de Tags',
      'tagTranslation.refreshSuccess': '@count tags atualizadas',
      'tagTranslation.refreshFailed': 'Falha ao atualizar: @error',

      // list mode
      'listMode.toggle': 'Alternar modo de visualização',
      'listMode.grid': 'Grade',
      'listMode.list': 'Lista',
      'listMode.listCompact': 'Lista Compacta',

      // quick search
      'quickSearch.title': 'Pesquisa Rápida',
      'quickSearch.empty': 'Nenhuma pesquisa salva',
      'quickSearch.saveCurrent': 'Salvar pesquisa atual',
      'quickSearch.saveTitle': 'Salvar Pesquisa Rápida',
      'quickSearch.nameLabel': 'Nome',

      // tag suggest
      'tagSuggest.tag': 'Tag',

      // common extras
      'common.save': 'Salvar',

      // reader enhancements
      'reader.fitWidth': 'Ajustar Largura',
      'reader.doubleColumn': 'Duas Colunas',
      'reader.autoStart': 'Leitura Automática',
      'reader.autoStop': 'Parar Leitura Automática',

      // block rules
      'blockRule.title': 'Regras de Bloqueio',
      'blockRule.empty': 'Nenhuma regra de bloqueio configurada',
      'blockRule.add': 'Adicionar Regra',
      'blockRule.edit': 'Editar Regra',
      'blockRule.manage': 'Gerenciar Regras de Bloqueio',
      'blockRule.ruleCount': '@count regras',
      'blockRule.ungrouped': 'Sem grupo',
      'blockRule.deleteGroup': 'Excluir Grupo',
      'blockRule.target': 'Alvo',
      'blockRule.attribute': 'Atributo',
      'blockRule.pattern': 'Padrão',
      'blockRule.expression': 'Expressão',
      'blockRule.expressionHint': 'Valor para comparar',
      'blockRule.groupId': 'ID do Grupo',
      'blockRule.groupIdHint': 'Nome do grupo opcional',
      'blockRule.blocked': 'Bloqueado',
      'blockRule.tagBlocked': 'Tag "@tag" foi bloqueada',
      'blockRule.uploaderBlocked': 'Uploader "@uploader" foi bloqueado',
      'blockRule.blockTag': 'Bloquear esta tag',
      'blockRule.blockUploader': 'Bloquear este uploader',

      // download enhancements
      'downloads.search': 'Pesquisar downloads...',
      'downloads.allGroups': 'Todos os Grupos',
      'downloads.group': 'Grupo',

      // tag voting
      'tagVote.search': 'Pesquisar',
      'tagVote.searchUploader': 'Pesquisar uploader',
      'tagVote.voteUp': 'Votar Positivo',
      'tagVote.voteDown': 'Votar Negativo',
      'tagVote.success': 'Votado',
      'tagVote.votedUp': 'Votou positivo para "@tag"',
      'tagVote.votedDown': 'Votou negativo para "@tag"',
      'tagVote.failed': 'Falha ao votar: @error',

      // responsive layout
      'home.selectGallery': 'Selecione uma galeria para ver detalhes',

      // gallery detail extras
      'detail.parentGallery': 'Galeria Pai',
      'detail.newerVersion': 'Versão Mais Nova Disponível',

      // settings extras
      'settings.cookieStatusFull': 'Cookies OK (inclui igneous — EX pronto)',
      'settings.cookieStatusNoIgneous': 'Cookies definidos mas falta igneous — EX pode não funcionar',
      'settings.cookieStatusNone': 'Nenhum cookie de login definido',
      'settings.siteSwitched': 'Alterado para @site',

      // download progress in detail
      'detail.completed': 'Concluído',
      'detail.retryDownload': 'Tentar novamente',
      'detail.readDownloaded': 'Ler baixado',
      'detail.deleteDownload': 'Excluir download',
      'detail.deleteDownloadConfirm': 'Excluir este download e seus arquivos?',
      'detail.archiveCompleted': 'Arquivo pronto',

      // detail enhancements
      'detail.share': 'Compartilhar',
      'detail.jumpToPage': 'Ir para Página',
      'detail.similarSearch': 'Pesquisa Similar',
      'detail.blockGallery': 'Bloquear Galeria',
      'detail.allComments': 'Todos os Comentários',
      'detail.thumbnails': 'Miniaturas (@count)',
      'detail.viewAllThumbnails': 'Ver Todas as Miniaturas',
      'detail.galleryBlocked': 'Galeria foi bloqueada',
      'detail.jumpPageHint': 'Insira o número da página (1-@max)',

      // reader enhancements
      'reader.saveImage': 'Salvar Imagem',
      'reader.openInNewTab': 'Abrir em Nova Aba',
      'reader.reloadImage': 'Recarregar Imagem',
      'reader.interval': 'Intervalo',
      'reader.preload': 'Pré-carregar',
      'reader.imageSpacing': 'Espaçamento de Imagem',
      'reader.autoInterval': 'Intervalo Auto-leitura',
      'reader.startAutoMode': 'Iniciar',

      // settings reader
      'settings.defaultFavoriteSlot': 'Pasta de favoritos padrão',
      'settings.defaultFavoriteNone': 'Nenhuma (perguntar sempre)',
      'settings.readerSettings': 'Configurações do Leitor',
      'settings.defaultDirection': 'Direção Padrão',
      'settings.imageSpacing': 'Espaçamento de Imagem',
      'settings.preloadPages': 'Páginas Pré-carregadas',
      'settings.autoInterval': 'Intervalo Auto-leitura',
      'settings.fitWidth': 'Ajustar Largura',

      // home enhancements
      'home.scrollToTop': 'Voltar ao Topo',
      'home.imageSearch': 'Search by image',
      'home.imageSearchFailed': 'Image search failed: @error',
      'home.imageSearchMode': 'Image search results',
      'stats.title': 'Visitor statistics',
      'stats.totalVisits': 'Total visits: @n',
      'stats.allTime': 'All time',
      'stats.year': 'Year',
      'stats.month': 'Month',
      'stats.day': 'Day',
      'stats.period': 'Period',
      'stats.ranking': 'Ranking',
      'stats.score': 'Score',
      'stats.visits': 'Visits',
      'stats.hits': 'Hits',
      'stats.noSeries': 'No chart data',
      'usertags.title': 'Watched / hidden tags',
      'usertags.loadFailed': 'Load failed: @error',
      'usertags.add': 'Add tag',
      'usertags.tagHint': 'Format namespace:key',
      'usertags.watch': 'Watch',
      'usertags.hidden': 'Hidden',
      'usertags.delete': 'Delete',
      'usertags.added': 'Added',
      'usertags.deleted': 'Deleted',
      'usertags.currentList': 'Configured tags',
      'downloads.sortBy': 'Sort',
      'downloads.sortPriority': 'Priority',
      'downloads.sortTime': 'Time',
      'downloads.sortTitle': 'Title',
      'downloads.sortStatus': 'Status',
      'downloads.setPriority': 'Priority',
      'downloads.setGroup': 'Group',
      'downloads.priorityLabel': 'Priority @n',
      'downloads.groupLabel': 'Group',
      'downloads.superseded': 'Upgraded to gid @gid',
      'downloads.editTask': 'Edit task',
      'detail.startDownloadTitle': 'Start download',
      'detail.downloadGroup': 'Group',
      'detail.downloadPriority': 'Priority (higher runs first)',
      'detail.stats': 'Statistics',
      'detail.similarByTitle': 'Similar title',
      'detail.upgradeDownload': 'Update to new version',
      'detail.upgradeOk': 'New version download started',
      'detail.upgradeFailed': 'Upgrade failed: @error',
      'detail.archiveNewVersionHint':
          'A newer gallery version exists. Download archive from the new gallery page.',
      'detail.openNewVersion': 'Open new version',
      'settings.usertags': 'Watched / hidden tags',
    };
  }
}
